### ISSUE TITLE
tel:  and  mailto:   links not working.

### ISSUE THREAD

**Issue by Dialoz** [myflashlab/webView-ANE#100]
Hi,   I recently purchased a commercial copy of your richWebView and have just exported apk from adobe Animate cc & then installed a working example.apk of webView sucessfully.

however, for some reason when tel:   or   mailto: links are clicked I just shows a page not found error?

Please help.  I must have tel:  and mailto: links working for my app to function as required.

Thank you in advance.

**Comment by Dialoz** [comment]
And / or, also what is the reference to the uri / url of _ex.openWebViewURL,  

so maybe I could use it to override uri if tel: or mailto: link clicked?

ie. how could I integrate something like an old webView solution i used in the past for standard old webView 
eg..
 'public boolean shouldOverrideUrlLoading(WebView view, String url) {
    if (url.startsWith("tel:")) { 
        Intent intent = new Intent(Intent.ACTION_DIAL, Uri.parse(url)); 
        startActivity(intent);
        view.reload();
        return true;
    }

    view.loadUrl(url);
    return true;
}'

IF NEEDED! 
As this is supposed to be an advanced richWebView I would assume handling tel: & mailto: links is part of your richWebView source.??? 

Please help.!!!

**Comment by myflashlab** [comment]
We have not yet been able to find a way to prevent the initiated load progress but we are working on it hard.

about the tel or mailto links, would you please post the html sample content your are having trouble with? So we can test it locally and make sure if it works fine on all scenarios... Thanks.

**Comment by Dialoz** [comment]
Thank you for your response,  the html code I use on my webpages is simple html which works on my Androids web browser however they return a url not found within richWebView?
the html is simply. eg.

`  <span class="PhTStyle">Phone:</span>
          <span class="PhStyle"><a onclick="_gaq.push(['_trackEvent', 'Phone', 'Click to Call', document.title])" href="tel:5555555"> 555 5555 <img src="img/callButton.png"></a></span>` 

also

`  <span class="EmlTStyle">Phone:</span>
          <span class="EmlStyle"><a onclick="_gaq.push(['_trackEvent', 'Phone', 'Click to Email', document.title])" href="mailto:email@emaildomain.tld"> email@emaildomain.tld <img src="img/callButton.png"></a></span>` 

Cheers.

**Comment by myflashlab** [comment]
We will look into this and update you a.s.a.p Thanks.

**Comment by Dialoz** [comment]
Thank you,    I await your response.
Also please note that I have also removed from my onclick"....     from links and tested also and still returns a url not found within richWebView app so its definitely not related to onclick function.

**Comment by myflashlab** [comment]
Please update yourself to V6.3.0 and read the [changelog](https://github.com/myflashlab/webView-ANE#changelog) to learn how you can handle this.

**Comment by Dialoz** [comment]
Thanks Heaps. Legends. :D 

Update works great.   :)

the code I used based on example you provided in update detail to make tel: mailto: and sms: word is:
`import flash.net.navigateToURL;
	 
_ex.addEventListener(RichWebViewEvent.PAGE_STARTING, onPageStarting);

    function onPageStarting(e:RichWebViewEvent):void
    {
    if (String(e.param).indexOf("mailto:") == 0 || String(e.param).indexOf("tel:") == 0 ||      String(e.param).indexOf("sms:") == 0)
    {	
		var specialStr:String=String(e.param);
		var mysurl:URLRequest= new URLRequest(specialStr);
		navigateToURL(mysurl);		
    }

    else
    {
        // allow other link types to load normally
        _ex.shouldContinueLoadingTheURL();
    }
}`

Thank Again for your help & fast response time.
Kind Regards.
