### ISSUE TITLE
ajax calls not working

### ISSUE THREAD

**Issue by shpe11** [myflashlab/webView-ANE#101]
in xhttp I'm geting 
readyState=1 / status=0
readyState=4 / status=0
and should be
readyState=1 / status=0
readyState=2 / status=200
readyState=3 / status=200
readyState=4 / status=200
tried with jquery and plain javascript, results: not working...

**Comment by myflashlab** [comment]
That would be great if you can send us the xhttp you are playing with, or a demo representing the problem so we can do some tests here and make the ANE work better.

Please consider that this WebView ANE is highly depended on the OS WebView and it has many/many settings and we are always trying to improve the ANE by hearing users show cases. Your feedback will help us improve the ANE. Thanks.

**Comment by shpe11** [comment]
function loadDoc() {
  var xhttp = new XMLHttpRequest();
  xhttp.onreadystatechange = function() {
	  document.getElementById("dContent").innerHTML+="...";
	  document.getElementById("dContent").innerHTML+=xhttp.readyState;
	  document.getElementById("dContent").innerHTML+=xhttp.status;
    if (xhttp.readyState == 4 && xhttp.status == 200) {
      //document.getElementById("dContent").innerHTML+= xhttp.responseText;
    }
  };
  xhttp.open("GET","iGalerie.txt", true);
  xhttp.send();
}
loadDoc();


also
function stiriLoad(){
	if(iStiri<iStiriMax&&iStiri<urlStiri.length-1)
		$.ajax({
			url:urlStiri[iStiri],
			type:'GET',
			success:function(data){ 
				$("#dContent").html($("#dContent").html()+data);
				iStiri++;
				stiriLoad();
			},
			error:function(xhr,ajaxOptions,thrownError) {
				iStiri++;
				stiriLoad();
			}
		});
	if(iStiri>=urlStiri.length-1)$("#bMORE").html(' ');
}
stiriLoad();



the files are in File.cacheDirectory
the paths are good because if I make links they work when I click on them

could it be that the webview somehow see the request and try to handle it in another context?

I also mention that this code works without problems in adobe webView (I have a finished an application but realize that the filepicker doesn't work in clasic webview)

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
