### ISSUE TITLE
softkeyboard hide on focus android 4.2.2

### ISSUE THREAD

**Issue by Cyrillix** [myflashlab/webView-ANE#103]
Hi,

On samsung gt9060 , with android 4.2.2 softkeyboard auto hide on input focus and we have cursor displayed in our input, blur event is not dispatched on html side .

Our webview working well with phone's browser.

Thanks for any help

Cyrille

**Comment by Cyrillix** [comment]
I have more information about the issue.

Softkeyboard disappear after a js call from as3. in log cat i have the followig logs :

06-21 12:07:14.035: D/WebView(14017): loadUrlImpl: called
06-21 12:07:14.035: D/webcore(14017):  CORE loadUrl: called
06-21 12:07:14.035: D/webkit(14017): Firewall not null
06-21 12:07:14.035: D/webkit(14017): euler: isUrlBlocked = false
06-21 12:07:14.045: D/WebView(14017): onSizeChanged - w:480 h:762

So in this android version your js call are done with load url , and  load url cause softkeyboard to disappear

**Comment by Cyrillix** [comment]
the solution should be to use sendJavascript method instead

**Comment by myflashlab** [comment]
You're right. That's the problem with WebView. even the native coders are having a hard time with the very same problem. [check this out for example](http://stackoverflow.com/questions/4536530/keyboard-in-html-text-input-disappear-when-webview-call-loadurl-again)

> the solution should be to use sendJavascript method instead

I'm not sure if I'm right, but is that a method in Android API? we had never seen that before and can't find it! Please advice.

**Comment by Cyrillix** [comment]
Hi , first thanks for your answer.

So sendJavascript is a function form cordova/phonegap. 

After a quick look in their code, they build a message queue , and poll this queue from js side.

I have also found this : http://stackoverflow.com/questions/2727763/communication-between-android-java-and-phonegap-javascript?lq=1

Build of an interface on java side to your web view and call queue from js with a timer to get message from the queue.

With this kind of system, on as3 side we could continue to use callJs , but this function build the queue when is needed with old android version

**Comment by myflashlab** [comment]
hmm, That makes sense. maybe we can do that but if we do, we should add that as a new method because I'm not sure it would work as fast as the original method. Anyway, I'll mark this and add it to the to-do list table. Thanks for the input.

**Comment by Cyrillix** [comment]
Great,  one last thing,  there is also loadurl call when we use
Airbridge.evoke.

So you migth need to have queue in both ways.

On our side, we have temporaly fix the issue by creating a queue on AS3
while keyboard is open,  and send it when softkeyboard hide.

With this we can test our app,but we wait for your changes.

Thanks

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
