### ISSUE TITLE
On Android, when soft keyboard shows, the web content doesn't move up.

### ISSUE THREAD

**Issue by jalendai** [myflashlab/webView-ANE#104]
Here are my observations.
- Using RichWebView, when a input text field has focus, the soft keyboard shows, the web content automatically moves up on iOS. But not on Android.
- Using StageWebView, under the same condition, the web content automatically moves up on both iOS and Android.

Anyone else has experienced similar issue? Is there a setting in RichWebView in order to make it work? I've looked through the reference docs already, couldn't find anything. Any advice please?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
