### ISSUE TITLE
Third part cookie

### ISSUE THREAD

**Issue by PrarthanaHegde** [myflashlab/webView-ANE#105]
How to enable third party cookie in rich stage web view?.. i was trying to access third party url inside iframe... it is not setting cookies to the webview.

**Comment by myflashlab** [comment]
Cookies and iframes... let me guess, this is working on iOS but not on Android, right? And if you are not using iFrames, cookies are working fine on Android too. Please confirm this and let us know.

If so, I think we just found the problem and we will quickly fix this issue in a fast release. Thanks for reporting this problem.

**Comment by PrarthanaHegde** [comment]
Hi, the problem is on IOS, not Android. The problem is not there if iframes
are not used.

We are loading a local page, then accessing our server page via  a iframe.
Cookies are not being set on calls to the server. We resolved a similar
problem by setting "Enable 3rd party cookies"- we think, this issue might
be similar.

**Comment by myflashlab** [comment]
I see, alright, let us do some tests on this and will update you a.s.a.p

**Comment by PrarthanaHegde** [comment]
Thank you for your prompt reply. As this matter is urgent, I would
appreciate a reply as soon as possible.

**Comment by PrarthanaHegde** [comment]
Any update?

On Fri, Aug 5, 2016 at 12:38 PM, Prarthana Hegde <prarthana@vpersonalize.com

**Comment by myflashlab** [comment]
Working on it... :) please be patience.

**Comment by myflashlab** [comment]
Alright, here are the results:

V6.4.0 is now ready to be downloaded. [Changelog can be found here](https://github.com/myflashlab/webView-ANE#changelog). However, in regard to the problem you raised in this issue, you need to consider another workaround for the iOS side! This seems to be a limit imposed by Apple. Some workarounds are mentioned [here](http://stackoverflow.com/questions/9930671/safari-3rd-party-cookie-iframe-trick-no-longer-working)

Nonetheless, we have added a new setting property for the Android side which will fix this problem on Android. ```RichWebViewSettings.ENABLE_THIRD_PARTY_COOKIES = true;```

I'm closing this issue now as it seems we have done all possible solutions related to this issue but if you think you have other information to add to this, please let us know. Thanks.
