### ISSUE TITLE
Pages Unresponsive in stage webview  - orientation issue 

### ISSUE THREAD

**Issue by sirishetty** [myflashlab/webView-ANE#107]
I'm facing a problem on  IOS.
After Coming back from camera UI (either cancel or complete event), stage web view become unresponsive.

Issue details:
1. Invoked camera UI from stage web view button, using HTML 5 or flash camera UI. (stage web view was in landscape mode(default app render mode is landscape)
2. took a photo in portrait mode.
3. on success of image load, back to app, page become unresponsive.
   stagewebview is responsive if you manually change the orientation.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
