### ISSUE TITLE
cookies ?

### ISSUE THREAD

**Issue by gabole** [myflashlab/webView-ANE#108]
Hello
looks like cookies are not working, can somebody confirm ?

thank you !

**Comment by myflashlab** [comment]
are you sure you have enabled cookies? especially on the Android side?

```actionscript
RichWebViewSettings.ENABLE_COOKIES = true;
RichWebViewSettings.ENABLE_THIRD_PARTY_COOKIES = true;
```

**Comment by myflashlab** [comment]
would you please update this ticket if the problem is solved?
