### ISSUE TITLE
get information from richwebview

### ISSUE THREAD

**Issue by bimkute** [myflashlab/webView-ANE#112]
hi myflashlab, i using rich webview lastest, but i don't know how to get information when user logged google account, thanks

**Comment by myflashlab** [comment]
Richwebview is just a tool for displaying html content/webpages. You can use JavaScript to control your pages or to use different RestAPIs which is out of the scope of our help. instead you should look in Stackoverflow or JS forums to know how you can work with different RestAPIs.

**Comment by bimkute** [comment]
i using as3 to make mobile app, i can't search RestAPIs and as3 work together

**Comment by myflashlab** [comment]
hmm, I'm not sure I'm understanding your question entirely. will you please explain more about what you are trying to achieve and maybe we can give some guidelines?

**Comment by bimkute** [comment]
:D i using action script 3 to make app and richwebview ane to show login. Now, i want to get information of user logged. My language can't work with RestAPIs, so what tool can help me get that information???

**Comment by gabole** [comment]
as3 can work with rest api, it's just a http call to a webpage resulting in formatted datas...
see this page: http://stackoverflow.com/questions/8180515/how-to-access-rest-service-in-actionscript-3

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
