### ISSUE TITLE
Web page is not allowed on Android

### ISSUE THREAD

**Issue by DenisSokoloff** [myflashlab/webView-ANE#113]
`public function WebView()
		{
			super();
			
			// support autoOrients
			stage.align = StageAlign.TOP_LEFT;
			stage.scaleMode = StageScaleMode.NO_SCALE;
			
			
			richWebView = new RichWebView(this.stage);
			
			RichWebViewSettings.ENABLE_BITMAP_CAPTURE 		= true;
			RichWebViewSettings.ENABLE_COOKIES 				= true;
			RichWebViewSettings.ENABLE_THIRD_PARTY_COOKIES 	= true;
			RichWebViewSettings.ENABLE_GPS 					= true;
			RichWebViewSettings.ENABLE_ZOOM 				= true;
			RichWebViewSettings.ENABLE_SCROLL_BOUNCE 		= false;
			RichWebViewSettings.BG_COLOR_HEX 				= "#FFFFFFFF"; // AARRGGBB
			
			initEvents()
			richWebView.openWebViewLocal(0, 0, stage.stageWidth, stage.stageHeight, File.applicationStorageDirectory.resolvePath("src/index.html"));

			
		}`

I viewed in APK and /assest/src/index.html exist
but I see ERROR http://prntscr.com/c7t11i

Manifest for iOS and Android was copied from demo

**Comment by princekero** [comment]
This problem also happen to me. As you see the url on that pic, it contained "air" before your app ID by default. So, the openWebViewLocal() function just never open the right url until you put "air." before your app ID. :-1:

**Comment by myflashlab** [comment]
@DenisSokoloff the [link](http://prntscr.com/c7t11i) does not open! However if the problem is similar to what @princekero has suggested, please test the [new ANE V6.5.0 from here](https://github.com/myflashlab/webView-ANE/issues/118)
