### ISSUE TITLE
width and height of rich webview do not fit to screen event set width height to stageheight and stagewidth

### ISSUE THREAD

**Issue by XeerSoft** [myflashlab/webView-ANE#114]
Hi, as title, I face this issue on IOS, IPad mini 4. Below is my code:

var _html_4_load:File;
_ex = new RichWebView(Starling.current.nativeStage);
_ex.addEventListener(RichWebViewEvent.BACK_CLICKED, onBackClicked);
_ex.addEventListener(RichWebViewEvent.PAGE_STARTED, onPageStarted);
_ex.addEventListener(RichWebViewEvent.PAGE_PROGRESS, onPageProgress);
_ex.addEventListener(RichWebViewEvent.PAGE_FINISHED, onPageFinished);
_ex.addEventListener(RichWebViewEvent.RECEIVED_MESSAGE_FROM_JS, onReceivedMessage);
_ex.addEventListener(RichWebViewEvent.RECEIVED_SSL_ERROR, onReceivedError);
RichWebViewSettings.ENABLE_BITMAP_CAPTURE = false;
RichWebViewSettings.ENABLE_COOKIES = false;
RichWebViewSettings.ENABLE_GPS = false;
RichWebViewSettings.ENABLE_ZOOM = false;
RichWebViewSettings.ENABLE_SCROLL_BOUNCE = false;
RichWebViewSettings.BG_COLOR_HEX = "#FFFFFF00"; // AARRGGBB
RichWebViewSettings.USER_AGENT = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.36 (KHTML, like Gecko) Chrome/13.0.766.0 Safari/534.36"; 
var _html_loader:URLLoader = new URLLoader();
_html_loader.addEventListener(flash.events.Event.COMPLETE, onLoaded);
function onLoaded(e:flash.events.Event):void {
    var _html_content:String = e.target.data;
    _html_content = _html_content.replace(/{VIDEOID}/g,link);
    _html_content = _html_content.replace(/{VIDEO_TITLE}/g,title);
    _html_4_load = File.documentsDirectory.resolvePath("htdocs/temp.html");
    if(_html_4_load.exists){
        _html_4_load.deleteFile();
    }
    var stream:FileStream = new FileStream();
    stream.open(_html_4_load, FileMode.WRITE);
    stream.writeUTFBytes(_html_content);
    stream.close();
    //_ex.visible = false;
    _ex.openWebViewLocal(0, 0, Starling.current.nativeStage.stageWidth,Starling.current.nativeStage.stageHeight, _html_4_load);
    //_ex.openWebViewLocal(0, 0,2750,1155, _html_4_load); **<---this is the resolution I slowly adjust so can fit to screen, but it bigger than actual stagewidth and smaller than actual stageheight**
    //var veiwPort:Rectangle = new Rectangle(0, 0, Starling.current.nativeStage.stageWidth,Starling.current.nativeStage.stageHeight);
    //_ex.setViewPort(veiwPort);
}
_html_loader.load(new URLRequest("htdocs/index.html"));

Thank you, I purchased MyFlashClub membership, I use contact us for rise this issue, but do not get any feedback for more than 3 days

**Comment by Dialoz** [comment]
I had this problem especially when testing on different devices,  
I found I had to created a few equations to calculate the Pixel Height and Width of stage "when stage loads on device" then from H & W values  I then convert them into percentages and set heights & widths of RichWebView as percentages.  
I found it to be much more accurate to display the same look on multiple devices.  

The Hard part is if like me, you need to inset the WebView window.   ie.   you have a header and footer above and below webview.   this is a little more complex but I used the same method except IMPORTANTLY first figure out your Header, WebView & Footer height(s) in percentages then load accordingly.  
once you figure your height percentages then you can calculate then y positions for each element.

x positions should load perfect if (after device load)  the x val is set to 0 or 1 (whatever suits) 
widths should load perfect if set to 100%;  

hope this helps.

**Comment by XeerSoft** [comment]
Hi, thank you for reply, the issue still the same, I try trace out fullScreenWidth and fullScreenHeight:
this.stage.fullScreenWidth-->2048
this.stage.fullScreenHeight-->1536
Below is the screenshot:
![photo 8-26-16 6 27 09 pm](https://cloud.githubusercontent.com/assets/8054411/18003972/38bbe972-6bbb-11e6-8e22-c490ab2d42aa.png)


Please advice, thank you

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
