### ISSUE TITLE
ios app was rejected? saying i need to use "Safari View Controller API"

### ISSUE THREAD

**Issue by Dialoz** [myflashlab/webView-ANE#115]
Hi I purchased RichWebView because when using standard web view for my ios apps, apple never approves any webview apps for me so far and say  "all buttons that launch instances of RichWebView are launching to mobile Safari app."

However after submitting my app that uses RichWebView apple has rejected my app they still say all buttons / that use instances of RichWebView are launching to mobile Safari app.
but then they say and I quote:
"we recommend implementing the Safari View Controller API to display web content within your app. 
The Safari View Controller allows the display of a URL and inspection of the certificate from an embedded browser in an app so that customers can verify the webpage URL.."

I bloody hate apple submissions its a nightmare, but is there a way that you know to use " Safari View Controller API" in flash / adobe animate.  or an update / option within RichWebView you could add to enable use of " Safari View Controller API"   

Thank You in Advance.

**Comment by mrgoonie** [comment]
Does anyone have a look on this? How is your app status now?

**Comment by Dialoz** [comment]
Still REJECTED, 
tried a few other builds and minimized screens that use webView.
and Still got Rejected. 

Apple pretty much says ANY and ALL apps that use WebVIEW, RichWebView, NativeWebView does Not make a difference, app still gets rejected.    they just keep saying use "Safari View Controller API" which is just a full screen browser with full controls (CAN'T CHANGE SIZE), so totally voids integration with App.  Although apple do not believe so.    

I have spend $600 dollars so far for my apple developer account and has been a Total waste of money!   Apple seems to have the view that web based apps should be web apps ONLY. 
so there seems to be no way to EVER get a web app in the apple store.    
Thus I believe this WebView Ane Useless for my needs.  
I paid for this because I thought It would be different than using normal webView (Maybe it is?) however to apple submission team its exactly the same as any other webView and Apple rejects my apps with exactly the same rejection message as when app was created using standard as3 webView.     

Anyways  I haven't had the chance to test the JSON functionalities so maybe this "RichWebView" ane could be a solution for ios submission rejections for someone knowledgeable enough to load external data & build pages in app. but I don't know as I haven't tested this.   

however to be honest Apple won't be getting another cent out of me.
I have developed 30 other games for Android platforms and I am deploying them all seamlessly to the windows store whilst most of theses apps would probably get accepted to itunes store, due to constant arrogance and disrespect Apple have shown me & many other developers from what i have heard, I will not be submitting Any of my other games or apps to itunes store EVER!  
not worth the headache anymore.

**Comment by myflashlab** [comment]
Thanks for giving details about your experience. Apple is usually too strict about these things and if an app is doing essential functionalities inside Webview, they would say it needs to be a web app. However, we successfully have got apps approved when using the Webview was not essential in how the app/game works. 

Nonetheless, we are putting this on the board so we can gather some more information about this and how apple is rejecting apps in this regard. As soon as we have our investigation finished, we'll update this issue. Thanks.

**Comment by mrgoonie** [comment]
Hi @Dialoz, I would say that I'm very sorry for your case, I can totally feel you since I got headache with appstore submissions all the time, the review team of Apple is borned to make people crazy, I believe so...

But can you share a bit more about how you use the richwebview in your app? Did you use it for displaying a web based app or what?

Just thought that it might help others to avoid this or keep wasting time on building something similar.

Thanks,

**Comment by Dialoz** [comment]
Hey guys, my app is a clone of my android app: https://play.google.com/store/apps/details?id=air.au.com.thecd.app  

in my apple development I used RichwebView instead.

the required functionality of my app is very simple.
We have 1000+ client html pages on our mobile site & and existing search page. 

The only use in my app of webView is  to display the users search result & client html pages.

Also Apple said when they click ANY / ALL buttons inside my app they load an external safari browser. 
what anoys me most is some of the buttons they specifically listed are simple as3 actions which invoke navigateTo  tel: mailto: geo:  and 2 of the button functions are even goto(frameno.) ect. within stage.?

But what bugged me the most is them saying my app does not appeal to a broad enough audience.
Our business is a local community & business telephone directory for a very small region in Victoria, Australia. We don't have or wan't a broad audience.

I re-iterated this to them and they then responded with there generic response again about ALL buttons in app opening up an external safari window. 

I really appreciate your help & input, 
but I'm done with apple, they gave me serious heart palpitations from all the stress.  

whilst our apple users can use our webApp like apple suggested, they unfortunately miss out on a few extra features. But... Apple say my app should be a webapp only.  
maybe they are right.  
I don't know... Maybe i'm stupid.
Anyway.. 
as for install-able apps and app stores gonna have to stick to Android & Windows Phone Only. 
I have never had any issues developing or deploying on either platform

Thanks Again Guys.
I appreciate all your help.

**Comment by Dialoz** [comment]
Also, when I specifically mentioned my app was now using NativeWebView they brushed over that fact and re-iterated now ios blah blah blah... will no longer support nativeWebView in app store apps... blah blah blah... instead we encourage developers to use the  "Safari View Controller API"....    not sure if this helps the investigation.  but from what i have read about " Safari View Controller API" its only Full Screen and you can't hide url bar or native safari buttons?  anyway the fullscreen thing is a deal breaker for me as my webView windows when loaded are never bigger than 1/3 of the screen height.

**Comment by mrgoonie** [comment]
Thanks for the detail information @Dialoz ! It must be very helpful to everyone.

And you know what, don't give up. "What doesn't kill you, make you stronger"

Cheers,

**Comment by arsyad** [comment]
I am intending to use this ANE for my application as well to load google map with geolocation detection. Will it likely to get rejected?

**Comment by myflashlab** [comment]
@arsyad I don't think so because the Webview is not going to play the main role in your app functionality. To load Google maps in your app is just a tool in your app. I think it will pass the review. However, that would be great if you contact them directly in regard to your specific case and update us here.

**Comment by Dialoz** [comment]
> arsyad commented 5 days ago
I am intending to use this ANE for my application as well to load google map with geolocation detection. Will it likely to get rejected?
> 
I'm not sure if its an apple thing against anything / all things Google, however apple did mention to me in previous builds submissions of my app  "in which i was using google maps as in my android app" and apple said in previous submission "We recommend integrating native ios maps instead of using google maps."
I ended up removing maps feature from ios app.   still did't pass.

**Comment by arsyad** [comment]
Hi Dialoz, that's such a worry. I am about to release a game using Google Maps with the webview. And there are some interactions from maps. Unfortunately, I don't think we can use native apple maps on Starling and Adobe air which will be a huge problem if they don't allow it.

Was the Google maps a huge part of your application?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
