### ISSUE TITLE
can't access camera :(

### ISSUE THREAD

**Issue by gabole** [myflashlab/webView-ANE#116]
hello

i need to be able to access the camera to take a photo using html:

<input id="file" type="file" accept="image/*" capture="camera" name="photo">
or
<input type="file" accept="image/*;capture=camera">

are not working. i believe this is related to webkit, but as apparently the webkit version used is the one included in the device, it should work...any thoughs ? are you able to access the camera using html5 tags from an air app ?

thank you

**Comment by myflashlab** [comment]
Can you write an html file which can open the camera if we open the page using the default device browser? or the chrome browser? If you are posting that sample html page, we'll try to investigate on this more and see if we can bring that functionality into the RichWebview.

**Comment by gabole** [comment]
Hello
thank you for your reply
you can test a page here: http://www.monpersonalcoach.ch/mobile/test.php
this test is working when opened with chrome or the default android browser, it also work with the stageWebView on IOS. it's not working with stageWebView/richerWebView on android
thanks !
regards
Gabriel

Date: Wed, 31 Aug 2016 22:49:05 -0700

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
