### ISSUE TITLE
Remove "air" prefix by openWebViewLocal()

### ISSUE THREAD

**Issue by princekero** [myflashlab/webView-ANE#118]
This function always added air. as application id prefix which included in its url.
Since my Flashdevelop Packager.bat set android-config to...
`set AIR_NOANDROIDFLAIR=true`
For example, if my app id is "com.myapp.xxx"
this function will not work because an error "file not found" with this always "air prefix" id
> file:///data/data/user/0/**air.**com.myapp.xxx/com.myapp.xxx/Local Store/

then I turned air prefix back
`set AIR_NOANDROIDFLAIR=false`

yes, it's work. but I didn't need that "air" prefix on my application id.

Can you fix this please? Thanks.

![Image SS](http://s.pictub.club/2016/09/14/mccGM.png)

**Comment by myflashlab** [comment]
Please test this demo version and tell us if the problem is fixed?
[richWebView-demo-6.5.0.zip](https://github.com/myflashlab/webView-ANE/files/471567/richWebView-demo-6.5.0.zip)

**Comment by myflashlab** [comment]
I forgot to mention. There is a new property which you should set to false ```RichWebViewSettings.ENABLE_AIR_PREFIX = false``` to make sure the prefix is disabled.

**Comment by princekero** [comment]
@myflashlab solved! it's work fine now. 
when the paid version of 6.5.0 available to download?

**Comment by myflashlab** [comment]
It is available right now! http://www.myflashlabs.com/product/rich-webview-ane-adobe-air-native-extension/
