### ISSUE TITLE
WebRTC

### ISSUE THREAD

**Issue by varadig** [myflashlab/webView-ANE#119]
With webView ANE I can use webRTC?

**Comment by myflashlab** [comment]
We haven't tested that! But if Android WebView and iOS UIWebview support that, then we can have that too. I did a quick check and it seems that Android supports that but not iOS. Could you do more study in this? We'd be happy to add that.

**Comment by Karaptor** [comment]
Hello!

I just did a quick check with the ANE, using targetSdkVersion 23
and it seems there is no matter what I do with android permissions, 
So I cant access camera and mic, so I fail to init webRTC.

try at a https page...
```
if (navigator.webkitGetUserMedia) {
    navigator.webkitGetUserMedia({
       audio: true,
        video: true
    }, function (stream) {
        if(console){ console.log('stream available');}
    }, function (err) {
       if(console){ console.error('could not connect stream ', err);}
    });
}
```

On normal chrome browser, it asks for permission of the camera and mic, but not in the app.

Can you investigate?

Cheers!

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
