### ISSUE TITLE
Does not work with Starling

### ISSUE THREAD

**Issue by 62316e** [myflashlab/webView-ANE#12]
1. Create startling instance
2. Add some sprites
3. Create new WebView instance
4. Close webview

Starling sprites disappears, or black or random...

AIR18/19 (beta)
This project is not ready for commercial use.

**Comment by myflashlab** [comment]
You should see this problem when building  with Starling on iOS, right? well, that's a common issue happening on iOS while having Starling. to fix that, you should handle context lost on Starling... we will also have a closer look and update you.

**Comment by 62316e** [comment]
It happens on Android and i'm handling context lost.

**Comment by myflashlab** [comment]
will you be able to send us a sample project? we don't seem to be able to duplicate the problem...

**Comment by myflashlab** [comment]
Read here:
http://forum.starling-framework.org/topic/ane-fix-for-blackblank-screen-bug-when-returning-to-air-android-apps

On Wednesday, August 5, 2015, 62316e <notifications@github.com> wrote:

> It happens on Android and i'm handling context lost.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/webView-ANE/issues/12#issuecomment-127962414>
> .
>


-- 
Sent from iPhone
