### ISSUE TITLE
loard several URLs into RichWebView  

### ISSUE THREAD

**Issue by RacheliGolan** [myflashlab/webView-ANE#121]
Hi, 
I have a project where I am using the RichWebView  a lot. Is there a way to loard a URL into without creating a new RichWebView  every time?
whenever I use the openWebViewURL function the player reloads itself what causes a delay.
thank you,

**Comment by myflashlab** [comment]
Well, initializing the ANE ```var _ex = new RichWebView(this.stage);``` takes some time and we can't do anything about it. However, you can init the ANE only once and then [hide it when you don't need it](http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/webView/RichWebView.html#visible).

**Comment by RacheliGolan** [comment]
thank you1
