### ISSUE TITLE
Listening to events and messages from page

### ISSUE THREAD

**Issue by Guarionex** [myflashlab/webView-ANE#122]
Is there a way to have the ANE listen to events or messages been sent by a page? We have a game that is both on Facebook and mobile, for the Facebook one, we have a site where we hide the FB Java SDK and make all our calls through there. With this ANE we are able to hook up the mobile to the same site and do the java script calls that we need, i.e., apprequest. The problem is that we aren't able to listen to any events, response, or messages from FB, since the ANE only listens to basic browser actions. Also we want to avoid changing our site's code as much as possible. Is there a way around this problem? Thanks in advance!

**Comment by myflashlab** [comment]
Will you please be able to create a sample html file with the kind of actions/events you like so we can first duplicate the issue here locally? Then we can find a solution and possibly update the ANE somehow that would solve the problem.

**Comment by Guarionex** [comment]
Well I found out that FB Java SDK won't trigger the callback function that you pass into it when on a mobile browser. So here is my situation: I'm trying to send a user to user app request through FB Java SDK. When my JS function gets call and the FB function gets called in it, I will get a redirect that makes the  apprequest. If it's the first time the user A sends user B a request, I will get a dialog from FB asking to submit or cancel and also asking if I want to show this dialog again for this user. When I click submit or cancel I get another redirect from which I cue of and turn off the webview. Now here is the problem: If user A check the don't display dialog again box for user B, the first redirect to the apprequest takes me to a blank page and automatically sends the apprequest without the seconds redirect that confirms if something happen. The url for the dialog and the blank page are the exact same. Is there a way to check the content of the page I'm viewing to know if I ended up with the blank page and just close the webview?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
