### ISSUE TITLE
error NSURLErrorDomain after allowing insecure connections

### ISSUE THREAD

**Issue by galaxybeing** [myflashlab/webView-ANE#124]
I'm getting an error on iOS 9:

"The operation couldn’t be completed. (NSURLErrorDomain error -999.) "

This is after I added following to infoAdditions to allow insecure http requests

```
        <key>NSAppTransportSecurity</key>
          <dict>
            <key>NSAllowsArbitraryLoads</key>
            <true/>
          </dict>
```

which I added because I was getting this error:
"The resource could not be loaded because the App Transport Security policy requires the use of a secure connection. "

**Comment by myflashlab** [comment]
Would you please provide more information about this? for example if this happens on all URLs you are testing? Are you using the latest released version of the ANE? Are you using the latest AIR SDK?

**Comment by galaxybeing** [comment]
I can't find any info on this error and it sounds like you can't either.  Let me give you some background.  This is an app that contains multiple games and starts off showing the client's full website in the webview.  The app loads the login page, the user logs in.  They go to the games menu page, click on a button to play a game.  The Javascript passes the gameID to the app, the app puts the webview off screen and plays the game.  When the user hits the back button in the game, the app moves the webview back on the screen.  So this is in the app store working fine and I just need to add a few more games, but now I'm running into these problems... first the App Transport Security issue that requires inserting some lines in the app.xml file to allow http.  But now I'm receiving delays when clicking the "play game" buttons (on both iOS and Android) and also getting this NSURLErrorDomain on iOS.

So in an effort to not change anything that doesn't need changing, I've kept the same version of the WebView, 6.2.  I had to update the AIR sdk from 22 to 23 for an unrelated reason.  

So it only calls openWebViewURL once at the beginning to load the log in page.  But then I find I have to click on the "play game" button several times before it will send the gameID to the app.  When the game finally is loaded, I can get into the app screen and view the log, which looks something like this before the gameID is sent:

[TitleScreen:instance67] onPageFinished: http://portal.mybrainfitlife.com/new/index.php/trainmybrain
[TitleScreen:instance67] onPageFinished: http://portal.mybrainfitlife.com/new/index.php/trainmybrain
[TitleScreen:instance67] error = The operation couldn’t be completed. (NSURLErrorDomain error -999.) 
[TitleScreen:instance67] error = The operation couldn’t be completed. (NSURLErrorDomain error -999.) 
[TitleScreen:instance67] onPageFinished: http://portal.mybrainfitlife.com/new/index.php/trainmybrain
[TitleScreen:instance67] error = The operation couldn’t be completed. (NSURLErrorDomain error -999.) 
[TitleScreen:instance67] error = The operation couldn’t be completed. (NSURLErrorDomain error -999.) 
[TitleScreen:instance67] error = The operation couldn’t be completed. (NSURLErrorDomain error -999.) 
[TitleScreen:instance67] onPageFinished: http://portal.mybrainfitlife.com/new/index.php/trainmybrain
[TitleScreen:instance67] onPageFinished: http://portal.mybrainfitlife.com/new/index.php/trainmybrain
[TitleScreen:instance67] onPageFinished: http://portal.mybrainfitlife.com/new/index.php/trainmybrain
[TitleScreen:instance67] onReceivedMassage: gameID=eThinkBalance 

So the error isn't caused by a call from the app but when a page is loaded by Javascript or something happening within the page.  It seems to keep loading the page, getting the error, before finally sending the gameID.  I was just hoping maybe you have seen this NSURLErrorDomain error and can shed some light on it and where it is coming from.

**Comment by galaxybeing** [comment]
It looks like there is are issues with the Javascript in the website which is probably causing the repeated page finished events.  Still would like to know what NSURLErrorDomain means.  Let me see if they resolve their web page issues and if so I'll close this issue.

**Comment by DanielLeblancRenful** [comment]
I also had this issue on iOS.
The NSURLErrorDomain error -999 was caused when opening a page whose data was rebuilt every time a dropdown was changed.
I noticed in the logs that onPageStarting was called immediately after the redirect to the page and it tried to open an empty page.  I added a condition in onPageStarting and onPageStarted:
if (e.param=="about:blank") {_ex.stopLoad();return;}
Then, the page that was supposed to load continued loading correctly.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
