### ISSUE TITLE
adt Error creating files...

### ISSUE THREAD

**Issue by mesaglam** [myflashlab/webView-ANE#125]
Hi,

I've got this message on Flash CC Win10  (Sdk Version 22.0.0.153 for Android)

![headache](https://cloud.githubusercontent.com/assets/7021706/19035343/abdd8a36-8971-11e6-9968-1f6ae6b321be.jpg)

This is my descriptor file.

[descriptor.zip](https://github.com/myflashlab/webView-ANE/files/506056/descriptor.zip)

I couldn't solve the problem...

**Comment by myflashlab** [comment]
@mesaglam 

1. Never share the .ane files even if they are demo ANEs. Please make sure you have read the [license pages](http://www.myflashlabs.com/licensing/) Of course it's clear that it was done unintentionally. Doing so might result in banning you permanently from MyFlashLabs.
2. I just ran your project and it successfully compiled and started on my device! I couldn't duplicate the error.
3. Is it probable that you are running on a simulator? Please use a real device instead.
4. We have an [Inspector ANE tool](https://github.com/myflashlab/ANE-Inspector-Tool) that you might find very interesting when using our ANEs.

**Comment by mesaglam** [comment]
Oh, i'm so sorry about that. That has escaped my attention...
Thanks for all...
