### ISSUE TITLE
openWebViewLocal() could not load on app that installed in SD card storage

### ISSUE THREAD

**Issue by princekero** [myflashlab/webView-ANE#127]
I just noticed this proplem...
It always work on other app which installed on internal storage.
_web.openWebViewLocal(x, y, w, h, File.applicationStorageDirectory.resolvePath("index.html"));

but not working on SD card storage with error message ERR_FILE_NOT_FOUND.

**Comment by myflashlab** [comment]
Are you sure your app has permissions to have access to the file location you are trying to load? If so, are you sure the file really exists at the location you are addressing?

**Comment by princekero** [comment]
The permission is  `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>` , right?

I used this code below. It always work on mobile internal storage.
```
src = File.applicationDirectory.resolvePath("html"); // the attracted html folder (in apk)
dis = File.applicationStorageDirectory.resolvePath("html");
```
![ss](https://i.imgsafe.org/48948aeb5b.png)

dis.nativePath of my file (on sd card) is
![ss2](https://i.imgsafe.org/492ddec03b.png)

your path where files not found is
![ss3](https://i.imgsafe.org/492df1d3c2.png)

**Comment by myflashlab** [comment]
1. In the image above, I can't see the full URL ```file:///data/data/air.com.test.greentea/com.test.g....``` Would you copy the full path here so we can see?

2. What Android devices have you check this on? What's the model and what's the Android version? Will you test it on other devices also? to see if that happens again?

**Comment by princekero** [comment]
1. `file:///data/data/air.com.test.greentea/com.test.greentea/Local%20Store/html/index.html`
2. I tested on Lenovo A700-a with Android 6.0 (with sd card)
not sure about other device... not tested yet. I will try to do this on other device.

**Comment by myflashlab** [comment]
Sure, while you test on other devices also, that would be helpful if you can send us a demo .apk file also. a simple demo which it runs the RichWebview so we can see the error message...

**Comment by princekero** [comment]
[here](https://mega.nz/#!TdhyTbIC!diebYQvDLjObfex5aME8SL6gZtm9v7qicfw-xrvVIh4) my apk file
it will show file.nativePath for my openWebViewLocal()
then if you press green button, it will switch to web view

**Comment by myflashlab** [comment]
![screenshot_20161018-125828](https://cloud.githubusercontent.com/assets/1692948/19472189/13475c20-9533-11e6-840b-82217567949d.png)

Tested on a few of our devices and when we hit the green button, the webview opened like the screenshot above. That means that the page has been loaded successfully?

If so, it means that there is something especial about your device. Have you checked the apk on other devices?

If the .apk works fine on other devices, which it seems to be, please let me know and I will prepare a test .apk for you to run on your device. The test .apk that I will build will help us determine the problem to see what could have gone wrong on that specific device. Waiting for your reply.

**Comment by princekero** [comment]
yes, this message show when the page has been loaded successfully.
did you move the app to sd card before test? 
sry, I'm not available to tested on other device (for now).
I will tell you later when I done the test.

**Comment by princekero** [comment]
@myflashlab  here, I tested on my device Moto X Style.
I moved the app to sd card storage and open app.
The problem seem occurred on this device too.

![s1](https://i.imgsafe.org/f1761317c9.png)

![s2](https://i.imgsafe.org/f17625884f.png)

![s3](https://i.imgsafe.org/f1762dae01.png)

**Comment by myflashlab** [comment]
So, this is happening when you move apps to the SD card, right? can you confirm if the same app works fine if you are not moving it to SD card?

**Comment by princekero** [comment]
I confirm, because I have many apps which contained this code. They always work fine if the mobile was not setup app installation location on sd card by default (or move it to sd card later too).

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
