### ISSUE TITLE
Displaying back button and toolbar

### ISSUE THREAD

**Issue by josephdecarie** [myflashlab/webView-ANE#128]
Hi,

How can I display the browser toolbar ? What are my options ?

Thanks,

**Comment by princekero** [comment]
I think. You should made one by yourself.

**Comment by myflashlab** [comment]
I've labeled this request as a feature enhancement in future versions. It's a good option to have although not directly related to the ANE. As an alternative, you can build one your self in JS or AS3 and use it along with the RichWebview

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
