### ISSUE TITLE
crash on ios Test Flight build.

### ISSUE THREAD

**Issue by hesapyonetimi** [myflashlab/webView-ANE#13]
WebView is working fine on ios test interpreter builds, but generates some crashes in release-testflight build. Line-by-line code testing shows the problem is certainly in webView, however the crashes are somewhat random, therefore we can't determine the exact reason.

**Comment by myflashlab** [comment]
can you post the error messages you are receiving?

**Comment by hesapyonetimi** [comment]
there is no message that occured. just closing the application and return to ios home screen. ps: tested on ios 8.3 iphone 6

**Comment by myflashlab** [comment]
we just doubled checked on iPhone 5 and iPhone 6+ with an adHoc build. it's working fine with all tests...

maybe you should look for the problem somewhere else? as a hint, check your manifest for

```xml
<key>MinimumOSVersion</key>
<string>6.1</string>
```

**Comment by hesapyonetimi** [comment]
is it a problem that we used the 5.1 version? we'll try with 6.1 version too.

**Comment by myflashlab** [comment]
Please reopen this issue if you are still having the problem after switching to min 6.1
