### ISSUE TITLE
intent error

### ISSUE THREAD

**Issue by ironynet** [myflashlab/webView-ANE#130]
sorry, my english skill is bad.

i get error that call credit card payment.
error page is

##############################################
Webpage not available
The webpage at
intent://cardName=............................................
could not be loaded because
net://ERR_UNKNOWN_URL_SCHEME
##############################################

and load 'market://' url scheme is same kind error.

Is that any way to fix it?
thanks adv.

PS. i find this code that overrirde shouldOverrideUrlLoading.

private class MyWebViewClient extends WebViewClient {
    @Override
    public boolean shouldOverrideUrlLoading(WebView view, String url) {
        if (url != null && url.startsWith("intent://")) {
            try {
                Intent intent = Intent.parseUri(url, Intent.URI_INTENT_SCHEME);
                Intent existPackage = getPackageManager().getLaunchIntentForPackage(intent.getPackage());
                if (existPackage != null) {
                    startActivity(intent);
                } else {
                    Intent marketIntent = new Intent(Intent.ACTION_VIEW);
                    marketIntent.setData(Uri.parse("market://details?id="+intent.getPackage()));
                    startActivity(marketIntent);
                }
                return true;
            }catch (Exception e) {
                e.printStackTrace();
            }
        } else if (url != null && url.startsWith("market://")) {
            try {
                Intent intent = Intent.parseUri(url, Intent.URI_INTENT_SCHEME);
                if (intent != null) {
                    startActivity(intent);
                }
                return true;
            } catch (URISyntaxException e) {
                e.printStackTrace();
            }
        }
        view.loadUrl(url);
        return false;
    }
}

**Comment by myflashlab** [comment]
I'm not sure if I understood your question entirely. However, if you wish to use a mechanisem similar to ```shouldOverrideUrlLoading``` thing in Native Android side of the API like the sample code you provided above, we do have a similar thing. Please read the complete guideline on the [changelog](https://github.com/myflashlab/webView-ANE#changelog) **Jun 15, 2016** where it described how you should use the ```RichWebViewEvent.PAGE_STARTING``` listener.
