### ISSUE TITLE
can't open market:// - intent://

### ISSUE THREAD

**Issue by ironynet** [myflashlab/webView-ANE#131]
first previous answer is thank you.

To explain my question again.

Using this code to call android market app page
_ex = new RichWebView(this.stage);
_ex.openWebViewURL("market://details?id=xxx.xxxxx.xxx"); 
or 
_ex.openWebViewURL("intent://xxxxxxxxxxxxxxxxxxxxxxx");

Unable to move to market page..
error page is
###### 

Webpage not available
The webpage at
market://details?id=xxx.xxxxx.xxx 
or 
intent://xxxxxxxxxxxxxxxxxxxxxxx
could not be loaded because
net://ERR_UNKNOWN_URL_SCHEME
###### 

In the previous answer, Have been overrided 'shouldOverrideUrlLoading' method in ANE.  
URL_SCHEME Is there already have been added, such as 'intent://', 'market://' ?

If so, do I need to check the other part?

thanks adv.

**Comment by princekero** [comment]
Hello guy, I have the same problem with market:// and I was read your previous topic.
What I did just use the navigateToURL() instead to call native browser.
here my code... hope it's help for now.
```
_ex.addEventListener(RichWebViewEvent.PAGE_STARTING, onPageStarting);

private function onPageStarting(e:RichWebViewEvent):void
{
      if(String(e.param).indexOf("market:") == 0){
        navigateToURL(new URLRequest(String(e.param)), "_blank");
      }else{
        _ex.shouldContinueLoadingTheURL();
      }
}
```

**Comment by myflashlab** [comment]
The ```_ex.openWebViewURL``` method is expecting an ```http(s)``` address. To open Google Play , what @princekero suggested could be helpful.

**Comment by ironynet** [comment]
@princekero thanks adv.
 indexOf("market:") perfect operation works.
but indexOf("intent:") is not working. Will there be any additional parts?

@myflashlab 
Is it possible to add ('intent://' and 'maket://' in shouldOverrideUrlLoading) to the next version?

**Comment by myflashlab** [comment]
> indexOf("intent:") is not working.

Try tracing out the ```e.param``` and see what String you are receiving when you send the ```intent:``` from JS. That should give you a clue on how to catch it.

> Is it possible to add ('intent://' and 'maket://' in shouldOverrideUrlLoading) to the next version?

I'm marking this as an enhancement. :)

**Comment by ironynet** [comment]
@myflashlab 
yes i test this code.
if (String(e.param).indexOf("market:") == 0){
    navigateToURL(new URLRequest(String(e.param)), "_blank");  ==> is working.
}
else if (String(e.param).indexOf("intent:") == 0){
    C.log("intent====>" + e.param);
    navigateToURL(new URLRequest(String(e.param)), "_blank");  ---> is no reaction.
}
Output certainly generates "intent====>intent://xxxxxxxxxxxxxx". 
But there is no reaction.

I will wait for the next version. 
thanks replay :)

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
