### ISSUE TITLE
AirBridge.evoke(utf8string) doesn't work

### ISSUE THREAD

**Issue by mrgoonie** [myflashlab/webView-ANE#132]
When I use JS to pass a string from rich WebView to my app, it worked like a charm with normal string. 

But with UTF-8 String, it displayed wrong characters. For example:

```
// in javascript:
AirBridge.evoke("Lâm Tâm Hiền");

// in AS3 receive:
"Lm Tm Hin"
```

All the utf8 characters had gone. Can you please double check?

Thanks

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
