### ISSUE TITLE
Html5 video display controls with out showing mp4 video formet, android.

### ISSUE THREAD

**Issue by rifaet** [myflashlab/webView-ANE#133]
hi!
i used your Rich Webview ANE (Android+iOS) × 1 in my project to play video tag from en html5 page.
the video playing but  in white screen, i can see the video controls but not the self video, this was in android mobil with last android OS 6.2.

Rifaat

**Comment by benedusi** [comment]
I have the same problem, I can rear the audio but only a black screen is show, with the default stagewebview the video play without any problem.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
