### ISSUE TITLE
How to pass non-string variables to JS in Rich Webview ANE

### ISSUE THREAD

**Issue by Bilbosax** [myflashlab/webView-ANE#134]
I just bought and downloaded the Rich Webview ANE.  I have a Flex project where I need to call Javascript functions, and I need to pass variables to the function.  How do I do this?  It looks like I can only pass strings.  The Javascript function looks like the following:

    function loadKeyMap(latitude, longitude, mapWidth, mapHeight) {
	    var myLatlng = new google.maps.LatLng(latitude, longitude);
	    var sheet = document.getElementById("map");
	    sheet.style.width = String(mapWidth)+"px";
	    sheet.style.height = String(mapHeight)+"px";
		
	    var mapOptions = {
		    zoom: 13,
		    center: myLatlng
	    }

	    map = new google.maps.Map(document.getElementById("map"), mapOptions);
    }

In my actionscript code, I want to call the function in a manner such as the following:

    myWebView.callJS("loadKeyMap(origLat, origLong, width, height)");

This of course will not work, so my question is, how do I pass variables to my Javascript functions using Rich Webview ANE?

Thanks!

**Comment by myflashlab** [comment]
You could try casting variables to Number in you js code?
http://www.w3schools.com/jsref/jsref_number.asp

**Comment by Bilbosax** [comment]
Thanks for the reply.  I assumed that I was probably going to have to cast the variables to the desired type.  I guess the bigger question is, do I need to parse the variables in Javascript as well.  In other words, does the ANE only allow you to send a single variable as a string that I would then have to parse and cast, or will it allow you to send several string variables separated by commas?

**Comment by myflashlab** [comment]
Using the ```callJS``` method you can send a String to your js content and yes, you need to parse the String on the JS side and cast variables from there. Maybe in future versions of the RichWebView ANE we add some other methods to simplify this process and allows you to send multiple variables but for now, we used just what the native Android/iOS APIs allows us to do. Anyhow, I am marking this issue as an enhancement so the dev team can see and add the feature to the list. It would be cool to be able to call JS functions by sending multiple params directly from the AIR side.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
