### ISSUE TITLE
Error in Samsung devices when hardwareAccelerated="true"

### ISSUE THREAD

**Issue by gameaccount** [myflashlab/webView-ANE#136]
Hi,

i'm getting this error in multiple Samsung devices when android:hardwareAccelerated="true"
This occur when trying to close the webview:

```
11-16 16:05:44.283: E/DataBuffer(21734): Internal data leak within a DataBuffer object detected!  Be sure to explicitly call release() on all DataBuffer extending objects when you are done with them. (internal object: com.google.android.gms.common.data.DataHolder@41ec61c8)
11-16 16:05:44.283: E/DataBuffer(21734): Internal data leak within a DataBuffer object detected!  Be sure to explicitly call release() on all DataBuffer extending objects when you are done with them. (internal object: com.google.android.gms.common.data.DataHolder@41f39620)
11-16 16:05:44.283: E/DataBuffer(21734): Internal data leak within a DataBuffer object detected!  Be sure to explicitly call release() on all DataBuffer extending objects when you are done with them. (internal object: com.google.android.gms.common.data.DataHolder@41e44a68)
11-16 16:05:44.773: I/InputReader(566): Touch event's action is 0x0 (deviceType=0) [pCnt=1, s=0.1335 ] when=41696697448000
11-16 16:05:44.773: I/InputDispatcher(566): Delivering touch to: action: 0x4, toolType: 1
11-16 16:05:44.773: I/InputDispatcher(566): Delivering touch to: action: 0x0, toolType: 1
11-16 16:05:44.813: I/InputReader(566): Touch event's action is 0x1 (deviceType=0) [pCnt=1, s=] when=41696731323000
11-16 16:05:44.813: I/InputDispatcher(566): Delivering touch to: action: 0x1, toolType: 1
11-16 16:05:44.843: W/ContextImpl(566): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1509 com.android.server.InputMethodManagerService$4.run:2684 java.lang.Thread.run:841 <bottom of call stack> <bottom of call stack> 
11-16 16:05:44.864: I/WEB_VIEW(10017): command = setPosition
11-16 16:05:44.864: I/WEB_VIEW(10017): command = closeWebView
11-16 16:05:44.864: D/v_gal(10017): [tid=10017] gl2mERROR: result=0x0502 @ glshBindTexture(1721)

11-16 16:05:44.864: D/v_gal(10017): [tid=10017] gl2mERROR: result=0x0501 @ glUseProgram(3015)
11-16 16:05:44.864: D/v_gal(10017): [tid=10017] gl2mERROR: result=0x0501 @ glDeleteProgram(1846)
11-16 16:05:44.864: D/v_gal(10017): [tid=10017] gl2mERROR: result=0x0501 @ glDeleteShader(351)
11-16 16:05:44.874: D/v_gal(10017): [tid=10017] gl2mERROR: result=0x0502 @ glshBindTexture(1721)
```
From Chromium i can see:
```
[ERROR:gles2_cmd_decoder.cc(1773)] [GroupMarkerNotSet(crbug.com/242999)!:F8C9E885]GL ERROR :GL_INVALID_OPERATION : BackFramebuffer::Destroy: <- error from previous GL command
and then v_gal [tid=9805] gl2mERROR: result=0x0501 @ glUseProgram(3015)
```
i'm able to replicate this issue in a Samsung Galaxy Tab 4 7.0'' 4.4.2 but have users having the same issue using 
Samsung Galaxy S4  
Samsung Galaxy Tab 3 (8 inch) – Running 4.4.2
Samsung Galaxy Tab 3(10 inch) – Running 4.4.2

**Comment by myflashlab** [comment]
Do you have this problem on specific web pages? Try loading a simple page and then try to close the webview. If it closes with no problem, then it means that there's something wrong on the loaded content on Samsung devices. If so, please give me a URL to the content you are trying to load and we will do some tests locally here.

**Comment by gameaccount** [comment]
i'm opening a simple page: https://m.betfaircasino.com/

after further investigation i found out that it doesn't crash if i remove the hardware accelerated tag.
This devices don't have the google webview, they have a modified webview and are not compatible with  android system webview.
At the moment i'm disabling the hardware accelerated if the device doesn't support system webview but it would be good to have a solution in the webview where if i don't have the check the app wouldn't crash.

**Comment by myflashlab** [comment]
Good finding. I'm marking this issue so we can do more investigation on this matter as soon as possible.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
