### ISSUE TITLE
ios inspect across Safari

### ISSUE THREAD

**Issue by inagun** [myflashlab/webView-ANE#138]
hi,
I can inspect the DOM across chrome developer (more tools / remote device) on android, but on a mac with ios and safari, developer tools can't see anything.

**Comment by myflashlab** [comment]
I'm not sure I am understanding what your question is.

**Comment by inagun** [comment]
To put it clearly, is it possible to connect an iphone running the ANE on a mac and inspect the dom with safari remote debug ? (Sorry for my poor english)

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
