### ISSUE TITLE
Need WKWebView to be used on IOS

### ISSUE THREAD

**Issue by gameaccount** [myflashlab/webView-ANE#139]
Hey,

I have a special requirement that needs me to use WKWebView on IOS. 

It would seem that this webView ANE uses UIWebView by default.

Is there currently a way to force the ANE to uses WKWebView on IOS if available ?

Thanks in advance for your answer.

**Comment by myflashlab** [comment]
The classic UIWebView should be able to take care of almost all occasions, however, we do have replacing it with the newer WKWebView object in our to-do list. I have marked this ticket so we can update you as soon as we released the new version with the new object.

**Comment by gameaccount** [comment]
The think is that UIWebView  seems to be not really supported by Apple anymore, and WKWebView  also seems to have better performance.

Any idea on the time estimate on when this could be added ?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
