### ISSUE TITLE
implementation not found for Android

### ISSUE THREAD

**Issue by josephdecarie** [myflashlab/webView-ANE#140]
I'm getting this message when trying to publish the Android version of my app that uses webView.

`An implementation for native extension 'com.myflashlab.air.extensions.webView' required by the application was not found for the target platform.`

Cheers

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
