### ISSUE TITLE
How to open an HTML file packaged with your application?

### ISSUE THREAD

**Issue by Bilbosax** [myflashlab/webView-ANE#141]
I wrote an AIR app for desktop that was using an htmlLoader to load a map into my application.  To do this, I had to include an HTML file that was packaged in a folder with the application.  I accessed the file and loaded the map using these commands:

var file:File = File.applicationDirectory.resolvePath("googleCode/Map.html");
var urlReq:URLRequest = new URLRequest(file.nativePath);
mapLoader = new HTMLLoader();				
mapLoader.load(urlReq);

I now need to be able to load a google map in AIR on mobile which does not support HTMLLoader but only StageWebView, and because I need to communicate with it in Javascript I decided to purchase your Rich WebView ANE.  The problem that I am seeing now is that your documentation says that you can only load HTML from either a URL or from an SD card.  I need to access an HTML file that I packaged in my app, which I would usually access by:

var file:File = File.applicationDirectory.resolvePath("googleCode/Map.html");

but your documentation says that I can only access data from the applicationStorageDirectory or the documentsDirectory.  Can I access data from the applicationDirectory, or is that forbidden in your ANE for some reason?

Thanks

**Comment by Bilbosax** [comment]
I solved this one on my own.  You actually can access data from the applicationDirectory in your ANE even though your documentation says that you can only access applicationStorageDirectory and documentsDirectory.  No need to reply.

**Comment by benedusi** [comment]
How you manged it to work? I get only a blank HTML file.

**Comment by Bilbosax** [comment]
I created a an html file called Maps.html and placed it in a folder called googleCode under the src directory.  Then I used this line of code to open it in my app:

    webView.openWebViewLocal(0, 0, mapWidth, mapHeight, File.applicationDirectory.resolvePath("googleCode/Maps.html"));

**Comment by benedusi** [comment]
I'm working with flash(animate) and exporting for android, I included the html file, it exists and the path is right as I can see with:
`var f:File = File.applicationDirectory.resolvePath("oed/index.html");`
` trace(f.exists)//true`

But calling the webview:
`_ex.openWebViewLocal(0, 0, stage.stageWidth, stage.stageHeight, desktop)`

I get a app:/oed/index.html
net::ERR_UNKNOWN_URL_SCHEME

**Comment by myflashlab** [comment]
@Bilbosax could you tell us what Android device you used? will you be able to send us a demo .apk to run locally on our own test devices?

**Comment by wigginsray** [comment]
I get the same error as benedusi. I also check for file exists and it exists on the device.
`_ex.openWebViewLocal(0, 0, 1400, 500, File.applicationDirectory.resolvePath("webview/index.html"));`
and
`_ex.openWebViewURL(0, 0, 1400, 500, File.applicationDirectory.resolvePath("webview/index.html").url); `
-- produces error "Webpage not available. The webpage at app:/webview/index.html could not be loaded because: net::ERR_UNKNOWN_URL_SCHEME" - first one works on IOS (second not tested)

`_ex.openWebViewURL(0, 0, 1400, 500, File.applicationDirectory.resolvePath("webview/index.html").nativePath);`
-- produces a blank page with no apparent error.

I was able to get the _ex.openData with HtmlDataSettings to work correctly.

My testing device: Galaxy Note 8 - Android 7.1.1

**Comment by wigginsray** [comment]
Update: I copied my files from the applicationDirectory to the applicationStorageDirectory and it works as expected.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
