### ISSUE TITLE
How to choose multiple files?

### ISSUE THREAD

**Issue by liugogal** [myflashlab/webView-ANE#142]
hi  boss:
How to choose multiple files? Thanks

\<input multiple="multiple" /\>  can't choose multiple files

**Comment by myflashlab** [comment]
This feature is in our to-do list and will be added in future versions.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
