### ISSUE TITLE
Web Content Being Rendered Too Small to be Used

### ISSUE THREAD

**Issue by Bilbosax** [myflashlab/webView-ANE#143]
I am using Rich WebView ANE to display a google map in my iPad mobile AIR app in portrait mode.  The WebView is set up in portrait mode at the top of the tablet with a width of 1536px and a height of 614px (30% of the height).  The map loads as expected, but the map and satellite buttons, the icons, the street names, the zoom in and out buttons are incredibly small, so small that you cannot click on them or hardly read anything.  It is almost as if Google is unable to tell that the target device is a mobile device and instead is rendering it for a desktop computer and squishing it down onto an iPad.  I have tried setting the USER_AGENT property as your documentation recommends, hoping that Google Maps would sniff out that the device was a mobile device and render accordingly.  That failed.  Is there anyway that you can think of that would allow me to scale what was displayed somehow using your ANE, or to get your ANE to identify itself as a mobile device to web servers so that they scale the content?  Here is the HTML/Javascript I am using to load the map into the ANE:

<!DOCTYPE html>
<html>
  <head>
	<meta name="viewport" content="width=1536">
  </head>
  <body>
    <div id="map"></div>
    <script>
		
		var map;
		var markers = [];
		var infoWindows = [];
		
      	function initMap() {
        	
      	}
		
	// Function for loading the map centered on the location we are interested in
	function loadMap(message) {
		var variableParts = message.split(";");
		var latitude = variableParts[0];
		var longitude = variableParts[1];
		var mapWidth = variableParts[2];
		var mapHeight = variableParts[3];
		var myLatlng = new google.maps.LatLng(latitude, longitude);
		var sheet = document.getElementById("map");
		sheet.style.width = String(mapWidth)+"px";
		sheet.style.height = String(mapHeight)+"px";
		var mapOptions = {
	  		zoom: 13,
	  		center: myLatlng
		}
		map = new google.maps.Map(document.getElementById("map"), mapOptions);
	}
        </script>
        <script async defer
               src="https://maps.googleapis.com/maps/api/js?v=3&key=[MyPersonalKey]&callback=initMap">
        </script>
    </body>
</html>

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
