### ISSUE TITLE
video can't play use Air 24.0

### ISSUE THREAD

**Issue by amihanya** [myflashlab/webView-ANE#144]
I change my app SDK to Air 24.0, and sence then the video on the page did not playing.
this is the link to video that i try to play:
[video plage link](https://www.toraland.org.il/%D7%A9%D7%99%D7%9E%D7%95%D7%A9%D7%95%D7%9F/%D7%94%D7%93%D7%A3-%D7%94%D7%99%D7%95%D7%9E%D7%99/%D7%9B%D7%97-%D7%97%D7%A9%D7%95%D7%95%D7%9F-%D7%94%D7%AA%D7%A9%D7%A2%D7%96-%D7%91%D7%91%D7%90-%D7%9E%D7%A6%D7%99%D7%A2%D7%90-%D7%A1%D7%93/)

**Comment by myflashlab** [comment]
We just tried AIR 23 and the video is not playing neither! Are you sure this is happening on AIR 24 only?

**Comment by amihanya** [comment]
I remember this works at AIR 23 Even so way the video didnt play? at the browser (safari, android browser and chrome) its work great.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
