### ISSUE TITLE
SoftKeyboardEvents not received while in webview

### ISSUE THREAD

**Issue by gameaccount** [myflashlab/webView-ANE#145]
Hi,

When having a webview screen where there is no extra as3 buttons and click on the webpage textinput, the softkeboardEvent is not triggered.
i read similar issue in here where the solution is to put stage.focus=null on the touch event of the webview.

That will work if the textinput is in flash, but i just want to know when the keyboard open or closes so i can resize the webview to display the entire webpage in the space available.

At the moment when i click on the textinput in the website the keyboard shows but the website content is not resized, so i have content behind the keyboard that i can't scroll to unless i close the keyboard.

The webview resize problem only happens on Android.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
