### ISSUE TITLE
Allow media files autoplay

### ISSUE THREAD

**Issue by MaximSpirin** [myflashlab/webView-ANE#146]
Hello,
can you please set WebSettings.setMediaPlaybackRequiresUserGesture to true in your implementation because its very bad that we can start video playback only on user's touch.

Thanks in advance,
Max

**Comment by myflashlab** [comment]
We are currently working on a very big update for this ANE. I have just marked this ticket to make sure we are adding this feature request in our next release.

**Comment by zgkaos** [comment]
Hi,
I've bought this extension for some private contractor work, and I have to say that everything is going smoothly, both on Android and IOS: nice job guys!

I am in need of the autoplay feature on videos too: is it possible to have an approximate date for the next release?

Thanks in advance
Timothy

**Comment by zgkaos** [comment]
Hi guys, 
since I've bought this extension it would be kind from you to at least give an estimate.
Any news?

**Comment by myflashlab** [comment]
Can't give an exact date but we're trying to make this happen very soon..

**Comment by zgkaos** [comment]
Hi guys,
any news?

**Comment by zgkaos** [comment]
Hi guys,
any news?

**Comment by myflashlab** [comment]
We are scheduling time for this. please wait for an update.

**Comment by zgkaos** [comment]
Hi guys! 
May I ask you any news on this update? 
We're got to a point when this has became an essential feature for our clients.

Thanks in advance.

**Comment by zgkaos** [comment]
It would surely be great to have a version with this enabled... In reality we'd need this on audio too, do you you think it would be possible to have a "dirty fix" on that too?
Thanks a lot for your support

**Comment by myflashlab** [comment]
Ok , here you go [richWebView.ane.zip V7.1.4](https://github.com/myflashlab/webView-ANE/files/1941671/richWebView.ane.zip), please checkout this hot version. just replace the ANE and while setting the webview settings, set this to false:

```
RichWebViewSettings.MEDIA_PLAYBACK_REQUIRES_USER_GESTURE = false;
```
This is added for iOS and Android but on iOS, when user is not on a wifi, the os force stops the autoplayback. This is what is considered by the iOS behavior if I'm not wrong.

Let me know if this works ok?

**Comment by myflashlab** [comment]
you guys needed this so badly, so we did the hot fix for you. we'd be happy to hear how it went?

**Comment by zgkaos** [comment]
Hi!
Here's the reality: we couldn't afford to wait 13 days for the hotfix, so to release we moved to another extension (wich has its own set of troubles too, expecially on Android).

I'm gonna test and see if it works, to at least let you know how it toruns out.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
