### ISSUE TITLE
Embed latest chromium into ANE

### ISSUE THREAD

**Issue by MaximSpirin** [myflashlab/webView-ANE#147]
Hello,
is it possible to embed the latest chromium webview into the ANE in the way like crosswalk(https://crosswalk-project.org/) does?

**Comment by myflashlab** [comment]
I'm not sure what they are doing, but we are currently working on a huge upgrade to RichWebView which will include [Chrome Custom Tabs](https://developer.chrome.com/multidevice/android/customtabs) which I think that's what you are referring to, right?

**Comment by MaximSpirin** [comment]
It allows developers to embed the latest version of chromium webview into the apk

**Comment by DigitalSkyline** [comment]
Any timeline for this enhancement? 

I ask because the current Android version is almost unusable on older versions of Android (anything older than 5 which is a sizable chunk of the market still). Trying to satisfy our client's needs and unfortunately having issues.

**Comment by myflashlab** [comment]
@DigitalSkyline We are doing our best to release it the soonest possible. We are currently heavily busy on empowering our ANEs with a whole new approach which makes ANE size smaller and make them work faster. When we finish that enhancement, probably in the coming week, we will start updating all our ANEs one by one while adding the extra requested features to them. Keep checking back for some awesome news. We're on it.

**Comment by MaximSpirin** [comment]
@DigitalSkyline It's possible to embed it manually into your own ANE - it took 3-4 days for me to build a demo AIR app that can create and display crosswalk window over the AIR display list. The app size grows by 40 Mb but it can handle almost all html5 features.

**Comment by DigitalSkyline** [comment]
@MaximSpirin Thanks, sounds interesting unfortunately the budget for this project is not going to allow me an additional 3-4 days of development. I have reverted to Air's StageWebView since at least it's not crashing on Android 4.4 and causing a horrible experience. 

@myflashlab Sounds great unfortunately, I can't wait for someday.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
