### ISSUE TITLE
cannot use lastest webview

### ISSUE THREAD

**Issue by bimkute** [myflashlab/webView-ANE#148]
Hi MyFlashLabs,
i using flash builder 4.6, air 24, richwebview version 6.6. When i run debugger, have error:
The extension com.myflashlab.air.extensions.webView has either a namespace version or library.swf with a version that is incompatible with the applications namespace or root SWF
Can you help me, thank you!

**Comment by myflashlab** [comment]
@bimkute this error means that you need to use newer AIR SDKs. While updating your AIR SDK, make sure your manifest .xml file is also pointing to that. the current latest AIR SDK is 24 so your manifest .xml file should read ```<application xmlns="http://ns.adobe.com/air/application/24.0">```

**Comment by bimkute** [comment]
i sure change my xml to 24.0, and this is error: Included native extension 'com.myflashlab.air.extensions.webView' includes a SWF version 25 which is greater than version of the root SWF of this application: 14
this is config in xml file
<application xmlns="http://ns.adobe.com/air/application/24.0">
<iPhone>  
        <InfoAdditions><![CDATA[
        	<key>UIStatusBarStyle</key>
		    <string>UIStatusBarStyleBlackOpaque</string>
		
		    <key>UIRequiresPersistentWiFi</key>
		    <string>NO</string>
		
		    <key>UIPrerenderedIcon</key>
		    <true />
		
		    
		    <key>NSLocationUsageDescription</key>
		    <string>I need location 1</string>
		    
        	<key>UIRequiresFullScreen</key> 
        	<true/>
		   <key>UIApplicationExitsOnSuspend</key>
            <false/>
        	<key>FacebookAppID</key>
			<string>252347141635661</string>
			<key>FacebookDisplayName</key>
			<string>SanhCo</string>
			<key>MinimumOSVersion</key> 
			<string>18.0</string>
			<key>UIDeviceFamily</key>
			<array>
				<string>1</string>
				<string>2</string>
			</array>
			<key>CFBundleURLTypes</key>
			 <array>
			  <dict>
			   <key>CFBundleURLSchemes</key>
			   <array>
			    <string>fb252347141635661sc</string>
			   </array>
			  </dict>
			 </array>
		]]></InfoAdditions>
        <requestedDisplayResolution>high</requestedDisplayResolution>
    </iPhone>

**Comment by princekero** [comment]
After update my app to 6.6.0, my webview not working too but without an error message (flash builder 4.7).  When I downgrade ane to 6.5.0 everything work fine again...

**Comment by myflashlab** [comment]
@bimkute when compiling your app, you need increase the ```-swf-version``` of your project to make sure your swf version is equal or higher than what is needed. search the ```-swf-version``` term on Google to know how it's set.

@princekero Since V6.6.0 the ANE is dependend on ```androidSupport.ane and overrideAir.ane``` Are you sure you have read the [changelog](https://github.com/myflashlab/webView-ANE#changelog)?

**Comment by bimkute** [comment]
i see properties of webview ane file, and swf version is: 25, because flash builder have error: 
Process terminated without establishing connection to debugger.
Error: The extension com.myflashlab.air.extensions.webView has either a namespace version or library.swf with a version that is incompatible with the applications namespace or root SWF.
my air version is 24

**Comment by myflashlab** [comment]
AIR SDK version is different from SWF version. Try this setting and tell us how it goes.
Use AIR SDK 24 and set your SWF version to 35.

More information about swf versioning can be found here: http://www.adobe.com/devnet/articles/flashplayer-air-feature-list.html

**Comment by myflashlab** [comment]
Let us know if you have overcome this problem?
