### ISSUE TITLE
Attempting to hide(true) until render, works first time, blank second time on Android 7.

### ISSUE THREAD

**Issue by PaulBaugher** [myflashlab/webView-ANE#149]
This works on iOS but of course when moving to Android there are unexpected issues.

Basically I have tried several things to hide the webview including the normal methods and even loading the page off stage (using x coordinate). But no matter what, after I hide the webview, after I call openWebViewURL to a new page, when I move it back on stage or make it visible, the screen is entirely black. 

Interestingly, it does continue to register clicks... I'm at a loss. Anything I can try?

Test device Nexus 6 with Android 7.

**Comment by myflashlab** [comment]
Hmm, Are you trying to load a new page while the webview window is hidden? does it make a difference if you first make the window visible and then try to load a new URL? Can you send us a simple demo project in FLashDevelop? and is this happening on all your other Android devices or it's just happening on Android 7?

**Comment by DigitalSkyline** [comment]
This never worked and had to move on. 

My work around was to close and dispose of the WebView object. Then re-initialize everything on demand, instead of simply hiding it as intended.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
