### ISSUE TITLE
webkitSpeechRecognition!

### ISSUE THREAD

**Issue by Dialoz** [myflashlab/webView-ANE#150]
Hi,  I'm not sure if this classifies as an issue, however I have recently integrated webkitSpeechRecognition scripts into my webpages & it works in chrome browser on desktop & mobile.
but webkitSpeechRecognition does Not work in my native android browser or in my app / richWebView.

Is there a setting in code I can set to enable webkitSpeechRecognition in my richWebView.
or Is it possible to use the java communication within richWebview to do this?

If so how would I achieve this.   

The code I use is ` <script>
function voice_recognition() {  
	  if (window.hasOwnProperty('webkitSpeechRecognition')) {
     var recognition = new webkitSpeechRecognition();  
     recognition.continuous = false;
     recognition.interimResults = false;
     recognition.lang = "en-US"; //language
     recognition.start();
     recognition.onresult = function(e) {
     document.getElementById('search_box').value = e.results[0][0].transcript;
     recognition.stop();
     document.getElementById('form_id').submit(); //form submit
   };
   recognition.onerror = function(e) {
     recognition.stop(); // error msg
    } 
  }
}
</script>`

and also an `  onclick="voice_recognition()"  `
within form to execute.

Is it possible to achieve webkitSpeechRecognition integration into my richWebview Adobe Animate app.

please help.
Thank You in Advance.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
