### ISSUE TITLE
HTTP Basic Authentication doesn't open when password authentication required

### ISSUE THREAD

**Issue by DanielSLeblanc** [myflashlab/webView-ANE#152]
There is a page I need to open which should open a HTTP Basic Authentication popup.  Instead I get an automatic failure for the authentication.

You can see an example of this at https://www.httpwatch.com/httpgallery/authentication/ if you go to the bottom of the page and click the "Display Image" button.

Basically, the http sends a 401 Unauthorized response, and instead of showing the password container it automatically throws a 403 Forbidden response.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
