### ISSUE TITLE
two issues

### ISSUE THREAD

**Issue by Dkvap** [myflashlab/webView-ANE#153]
1.  Add  camera  capture support for &lt;input type='file' / &gt;:
in “choose a file” popup window，please add camera channel.

2. download this v6.6.0 source ,and use the recent libs like overrideAir.ane，but it does not work

**Comment by myflashlab** [comment]
Try V7.0.0 released a few minutes ago and let us know if you still have a problem?

Camera capture support for html input files has been added to our to-do list.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
