### ISSUE TITLE
Open camera instead of pick file

### ISSUE THREAD

**Issue by Voltigeuse** [myflashlab/webView-ANE#155]
Hello,

When I click on my HTML button with openEmbeddedBrowser fonction, it opens box to chose camera. 
When I click on my HTML button with openWebViewURL fonction, it opens box to chose a file. 

How can I manage to open the camera with opeWebViexURL ?

**Comment by myflashlab** [comment]
I'm not sure I am understanding your question. please elaborate.

**Comment by Voltigeuse** [comment]
I developed an android app. This app open an html page with a button to download images.
When I click on this button in this html page with Chrome, a box to choose camera is coming.
When I click on this button in this html page with my app using openEmbeddedBrowser, a box to choose camera is coming also.
But I prefer to use openWebViewURL with my app, and when a click on the button, android open an explorer to chose a file in the mobile and I would like it open the box to chose the camera instead.

I hope my english will be understandable. Sorry for this.

**Comment by myflashlab** [comment]
Could you please send us your demo URL so we can test it on both the chrometab and the webview?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
