### ISSUE TITLE
Site not running

### ISSUE THREAD

**Issue by SherarVeRoked** [myflashlab/webView-ANE#156]
I use Rich WebView ANE on android.
This site http://malgames.com/travel/ does not work on the WebView in Galaxy 4.
On other devices (not Samsung) it works.
How can i fix it?
Thanks

**Comment by SherarVeRoked** [comment]
?

**Comment by myflashlab** [comment]
The job of the extension is to provide the AIR side with native libraries. If a webpage like the sample is not opening in a certain device, that would be very probable that the native library has problems on that specific device(s)

To be sure of that, please install a sample webview app https://play.google.com/store/search?q=android%20webview and try to load your URL in the targetted device. Let me know if that loads?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
