### ISSUE TITLE
loadString?

### ISSUE THREAD

**Issue by marcanw** [myflashlab/webView-ANE#157]
I'd like to buy Rich Webview ANE but I didn't find something similar to loadString from the standard StageWebView.
I'm using loadString intensively on StageWebView but I'd like use your Rich Webview ANE.
Is it difficult to do?
Is it planned for the next release?

**Comment by myflashlab** [comment]
yes, this is in our to-do list

**Comment by myflashlab** [comment]
V7.1.0 is released with this feature. https://github.com/myflashlab/webView-ANE#changelog
