### ISSUE TITLE
Is it possible to set Authorization header for HTTP requests sent by webView?

### ISSUE THREAD

**Issue by mnaumank** [myflashlab/webView-ANE#158]
Is it possible to set Authorization header for HTTP requests sent by webView?

I have a authorization bearer token that i want to set in the HTTP headers before the request is sent to server. How can I do that?

- NK

**Comment by myflashlab** [comment]
nice one. We will add this in our next releases.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
