### ISSUE TITLE
Exception with MyWebView constructor

### ISSUE THREAD

**Issue by Cyrillix** [myflashlab/webView-ANE#16]
We have bought the commercial version 3.0 and we have the following error after constructor call

_ex = new MyWebView(this.stage, true, true, true);

[Fault] exception, information=TypeError: Error #1009: Cannot access a property or method of a null object reference.

we have tried our ane with Demo and we have the same error

**Comment by Cyrillix** [comment]
is an issue with java version ?

**Comment by Cyrillix** [comment]
i use flash develop to build it

**Comment by Cyrillix** [comment]
Please help, I am issue other without issue

**Comment by Barendnu** [comment]
Have you tried:
- Using the newest version of Adobe AIR (for me it worked in AIR18, but not in AIR17)
- Be sure that you actually have a "stage" when initializing the webview.

With these two points in mind, the component works fine for me in Flash Professional.

**Comment by Cyrillix** [comment]
Thanks a lot, AIR18 solved the issue
