### ISSUE TITLE
Is it possible to read the current URL in embedded browser mode?

### ISSUE THREAD

**Issue by anupamverma170191** [myflashlab/webView-ANE#160]
I am using this ane and everything is working fine. The only issue am facing is not able to read the url in embedded mode. The url am using will work only on embedded mode but am not able to find a way to get a callback or  read a response url in this mode.
Please help me out and if there is a way out to this issue kindly update.

**Comment by myflashlab** [comment]
read this: http://stackoverflow.com/questions/35160635/check-which-url-is-opened-in-custom-chrome-tabs

> By design this is not possible with Chrome Custom Tabs. You can tell that a user has navigated but you can't tell where they've gone to....
