### ISSUE TITLE
AirBridge.evoke fails

### ISSUE THREAD

**Issue by notmark** [myflashlab/webView-ANE#161]
I've followed the examples, but AirBridge.evoke won't execute. It stops any javascript after it from executing. Am I missing something or is there a library I need to include on the web page?

**Comment by notmark** [comment]
Also it appears event listeners are not firing, either. Hmm. Money well spent!

**Comment by myflashlab** [comment]
@notmark you need to provide us with more information. for example if this is happening on iOS or Android? Are you testing with our sample project? and with our sample html file? Are you sure you have set everything correctly? Many devs are using this ANE and this is the first time anyone is reporting such a thing, have you considered that you might have missed something?!

**Comment by notmark** [comment]
Android Air. Sample project and my own project. There is no sample HTML file provided nor one that I have found in this repository. Even downloaded the club zip file again to make sure I didn't have a corrupted archive. And downloaded the recent ANE from this repository to see if that made a difference. Nothing is firing and there are no errors in the logcat in Android Studio.

**Comment by notmark** [comment]
I found the example HTML file and made a change from <script type="text/javascript"> to <script> "use strict"; and it started working. Welp. Ha.

**Comment by myflashlab** [comment]
> There is no sample HTML file provided nor one that I have found in this repository.

here it is! https://github.com/myflashlab/webView-ANE/tree/master/FD/bin

Anyway, please send us a demo/test project (not including the licensed or demo ANEs) so we can test this locally also. Give us something to play with. If we can see the problem, or duplicate the problem, we will fix it.

And by the way, make sure you are using the RichWebview V7.1.0, we have just recently updated the club package.

**Comment by myflashlab** [comment]
Glad it worked. However, just wanted to let you know that we are a very sensitive team, don't make decisions too fast 😃 

> ... Hmm. Money well spent!

**Comment by notmark** [comment]
<3 come here bb. I love you, sir and team.
