### ISSUE TITLE
Event EMBEDDED_BROWSER_ACTION not working on IOS 9.0.2

### ISSUE THREAD

**Issue by danyradu** [myflashlab/webView-ANE#164]
The event is never triggered

**Comment by danyradu** [comment]
Air 24, flash builder 4.7, flex sdk 4.6.0

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
