### ISSUE TITLE
long press gestures disabled but context menu still appears. 

### ISSUE THREAD

**Issue by tclugithub** [myflashlab/webView-ANE#166]
I've set long press gestures disabled 
but the android context menu when selecting text areas still comes up.
I need to create text selection event via the webview.
Please advise 
Thank you

**Comment by myflashlab** [comment]
Are you trying to disable text selection?  maybe you need to set ```-webkit-user-select: none;``` check this out: https://www.w3schools.com/cssref/css3_pr_user-select.asp

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
