### ISSUE TITLE
Strange problem with Google Play App Signing

### ISSUE THREAD

**Issue by princekero** [myflashlab/webView-ANE#168]
Hello, @myflashlab I just found this problem on 2 days ago. 
Since I bought this ANE, I created a template for ton of apps (webview app) that work fine on store for half-year. Then Google changed their developer console, added enroll app signing.

![enroll](http://i.imgur.com/IAnhatm.png)

All of my apps which "enrolled" Google Play App Signing. Can't load index page and show error, because they can't simply copy file from applicationDirectory to applicationStorageDirectory. But another apps with same code work fine if it not enrolled the google key signing. 

![not found](http://i.imgur.com/Bi9NGbx.png)

This strange thing happened on 13/JUN (I know this from my admob income suddenly low).
Almost all of my apps on store died even they lived on the store for 1-2 months. 
This nightmare just like remote bomb, it's detonated lot of my apps...
then I fixed them by turned into cordova/phonegap instead.

I don't know, maybe it's AIR problem? just want to let's you know about this. Thanks.

**Comment by madovsky** [comment]
so morality, do not ever trust google.

**Comment by princekero** [comment]
Yep, my fault. I was feel like they offer something better, so I clicked the blue button and now they are completely easier ruled my APKs.   :/

**Comment by madovsky** [comment]
btw it's maybe time to forget this corporation and subscribe to other phone app portals, there are plenty today

**Comment by myflashlab** [comment]
This is weird indeed! Do you mean that when you enrolled in the new app signing thing, AIR does not allow you to copy files to ```applicationStorageDirectory``` Have you tried to let Adobe know about this problem?

**Comment by princekero** [comment]
@myflashlab Yes, that what I mean.
No, I didn't post anything in Adobe. 
I have to changed all of my apps from AIR to cordova anyway, smaller and faster for webview.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
