### ISSUE TITLE
java.lang.NullPointerException Error in Flash Builder

### ISSUE THREAD

**Issue by Bilbosax** [myflashlab/webView-ANE#169]
I purchased the richWebView ANE from you, and I am trying to use it with Flash Builder 4.7 to write a mobile tablet app.  I am having a problem, and the problem lies with the ANE.  I added the ANE to a folder called libs. Then under Properties->Build Path->Native Extensions, I added the ANE.  Finally, under Properties->Flex Build Packaging->Apple iOS->Native Extensions, I clicked the checkbox to Package the ANE with the App.  Finally, I made sure that I included the proper iOS and Android descriptor file modifications. Now when I try to deploy the app to my iPad, Flash Builder breaks and I get a java.lang.NullPointerException error.  If I remove the ANE from the project, the problem goes away.  So the problem is definitely with the ANE.  I am using AIR 25.0.

I am very frustrated.  Any thoughts as to why an ANE might be causing this problem, or what you might try if you were me??? 

Thanks!

**Comment by myflashlab** [comment]
> I'm not sure the word "definitely" is correct because many devs have been using this and our other ANEs for years Anyway, please prepare a simple test demo project and send it back to us so we can test your setup and see what could have been wrong. 

**when sending over your demo/test apps, do NOT include the ANEs in them**

**Comment by Bilbosax** [comment]
I could send over a test project. Do I just export an .fxp project? And how do I send it to you?

**Comment by myflashlab** [comment]
there are many places you can upload your files to and send us download link! GoogleDrive for example. The demo project you are sending should include the manifest and any necessary files that we can open it in FlashBuilder of course.

**Comment by Bilbosax** [comment]
OK, here is the information that you will need.  I am using Flash Builder 4.7 on Windows 10.  My sample app is built using the Flex 4.16.0 SDK, AIR 25.0, Flash 25.0.  I have deleted all of the ANE files from the project, so you will need to add overrideAir.ane, androidSupport.ane, and richWebView.ane to the "libs" folder before you start.  When you try to install to an iPad, you will also need to change the certificate, provision file, and change the ID in the descriptor file of course.

The application does absolutely nothing.  It contains a button just to have something on the screen. I haven't added any code from any of the ANE's to the app.  I simply wanted to compile and upload an app containing the ANE's to my iPad after adding them to the project, and I get an error stating:

An internal error occurred during: "Launching Main".
java.lang.NullPointerException

The process that I used was to add the ANE's to the "libs" folder.  I then went to Properties->Build Path->Native Extensions, and I added the ANE's to the project.  Then, under Properties->Flex Build Packaging->Apple iOS->Native Extensions, I clicked to Package the ANE with the App. I made sure the proper extensions were added to the Main-app.xml descriptor file, and added your recommended manifest changes.  I then tried to compile and install the app onto my iPad, and it crashes with the error listed above.  I have added the .fxp file to Google Drive and you can download it from the link below.  Please let me know anything that you can, as I am a bit under the gun on time.  I really appreciate you help!!

https://drive.google.com/file/d/0B7Cws4y6B_MOaGItZGthX29hTVU/view?usp=sharing

**Comment by Bilbosax** [comment]
As an update, I also uninstalled Flash Builder and reinstalled it on my work computer, along with Flex 4.16.0 and AIR 25.  I also installed Flash Builder on an old Windows 7 machine with the same SDK as before.  In both cases, I am getting the same result, a java.lang.NullPointerException error.  So using your video on how to install the ANE, I am either doing something drastically wrong that I am unaware of, or there is a problem with this ANE.  Any updates on your part yet???

**Comment by myflashlab** [comment]
[RichWebView_FB.zip](https://github.com/myflashlab/webView-ANE/files/1099472/RichWebView_FB.zip)

We were not able to run the project you sent! But anyhow, we just create a Pure AS3 simple demo FlashBuilder project for you. Just add the ANEs to the ```lib``` folder and it should work just fine.

When copying the ANEs, make sure you are using the latest version of the dependencies. For example, the latest version of [AndroidSupport](https://github.com/myflashlab/common-dependencies-ANE/tree/master/androidSupport) ANE is 25.3.1. Make sure you are using that. And when using that, you must use AIR SDK 25+ The same thing goes with other ANEs. make sure you are using the latest ones.

**Comment by Bilbosax** [comment]
I will take a look at your Pure AS3 project in the morning. Because nobody else seems to be having a problem with the ANE, I figure I must be doing something wrong. I MAY have found a solution, but I don't understand why it works entirely. While developing, I always put my output folder in my web root directory using an absolute path like C:/wamp64/www/ANE-test. I read an obscure reference that some mobile devices don't understand "C:", so I changed my output folder to simply be ANE-test, and it worked!!! The reason I figure this out was by looking at the .log file. Before the Java.lang.NullPointerException error was being thrown, it was stating that it could not find my ANE-test-app.xml file in my output folder even though the file was clearly there. Do you understand why you can't use an absolute path to your output folder when using your ANE?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
