### ISSUE TITLE
Is it possible to use window.print()

### ISSUE THREAD

**Issue by ate864** [myflashlab/webView-ANE#17]
Hello!

i try to use : window.print()
is it possible?

Thank you

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
