### ISSUE TITLE
WebRTC not working

### ISSUE THREAD

**Issue by chasleries** [myflashlab/webView-ANE#170]
Hi.
I got a problem with WebRTC wich don't seems to work.
For exemple with the page https://simplewebrtc.com/demo.html : 

```
var ex:RichWebView = new RichWebView(stage);
			
RichWebViewSettings.ENABLE_BITMAP_CAPTURE = true;
RichWebViewSettings.ENABLE_COOKIES = true;
RichWebViewSettings.ENABLE_THIRD_PARTY_COOKIES = true;
RichWebViewSettings.ENABLE_GPS = true;
			
ex.openWebViewURL(0, 0, stage.stageWidth, stage.stageHeight, "https://simplewebrtc.com/demo.html");
```

Is there a setting to modifiy to get it work ?

Thanks

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
