### ISSUE TITLE
HTML input file type with openWebViewURL

### ISSUE THREAD

**Issue by code5381** [myflashlab/webView-ANE#172]
When I open URL using openWebViewURL, the html code '<input type="file" accept="image/*">' doesn't work.  

I want to upload my image in the mobile storage to the Server. 

Is it possible?

**Comment by myflashlab** [comment]
Have you been able to successfully load the html demo content we have placed as a sample content in our GitHub repository? If you run that, you can find a lot of helpful JS code which can get you started. But the code for you to upload your content to your server has really nothing to do with the ANE itself. To help devs get going faster, we have tried to put the sample [html/js](https://github.com/myflashlab/webView-ANE/tree/master/FD/bin/demoHtml) files.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
