### ISSUE TITLE
take ScreenShot in Starling

### ISSUE THREAD

**Issue by yooni126** [myflashlab/webView-ANE#173]
hi
i want to take screenshot and save it in starling
when i use this code :
```actionscript
_ex.requestBitmap();
private function onScreenshot(e:RichWebViewEvent):void
		{
			var bm:Bitmap = new Bitmap(e.param, "auto", true);
			//addChild(bm);    // i cant add this child in starling !
                       // Implicit coercion of a value of type Bitmap to an unrelated type DisplayObject.
			var jpgEncoder:JPGEncoder = new JPGEncoder(100);
			var byteArray:ByteArray = jpgEncoder.encode(e.param);

}
```
i see this error in debug mode:
//[Fault] exception, information=ArgumentError: Error #2015: Invalid BitmapData.

can u help me ?

**Comment by myflashlab** [comment]
Of course you cannot addchild a Bitmap object into Starling. This question is really related to the Starling platform not the ANE, but anyway, here's the solution:

I haven't played with Starling for a while but if I remember correctly, you first need to create a texture from your Bitmap ```var myTexture:Texture = Texture.fromBitmap(new Bitmap(e.param, "auto", true))``` and then create an Image object with it: ```var img:Image = new Image(myTexture);```

to be sure, read the documentation on Starling. Let me know if you have more questions on the ANE side?

**Comment by yooni126** [comment]
Thank u for your support 
But Now I have new Issue :|
var myTexture:Texture = Texture.fromBitmap(new Bitmap(e.param, "auto", true))
[Fault] exception, information=ArgumentError: Error #3766: RectangleTexture too big (max is the larger of 2048x2048 or the size of the backbuffer).
is there any way to take screenshot from current view ?

**Comment by myflashlab** [comment]
Taking screenshots from the current view is in our to-do list. Thanks.

**Comment by yooni126** [comment]
thank u , but can you say how long we must wait for this function ?

**Comment by myflashlab** [comment]
Can't say for sure just yet. will update this post as soon as we have a fixed schedule.

**Comment by 4malik** [comment]
Yes, texture maxSize is 2048. try to make result bitmapData for Texture and watch result quality.
You can do something like this:
```javascript
private function onScreenshot(e:RichWebViewEvent):void
{
	var _bitmapData:BitmapData = new Bitmap(e.param, "auto", true).bitmapData;
        var _scale:Number = 1;
        if (_bitmapData.width > 2048) {
                _scale = 2048 / _bitmapData.width
        }
        if (_bitmapData.height * _scale > 2048) {
                _scale *= 2048 / _bitmapData.height;
        }
        if (_scale < 1) {
                _bitmapData = scaleBitmapData(_bitmapData, _scale);
        }
        var _texture:Texture = Texture.fromBitmapData();
        mImage && (mImage.texture as Texture).dispose();
        mImage = new Image(_texture);
}

private function scaleBitmapData(bitmapData:BitmapData, scale:Number):BitmapData {
            var _width:int = (bitmapData.width * scale);
            var _height:int = (bitmapData.height * scale);
            var _transparent:Boolean = bitmapData.transparent;
            var _result:BitmapData = new BitmapData(_width, _height, _transparent);
            var _matrix:Matrix = new Matrix();
            _matrix.scale(_scale, _scale);
            _result.draw(bitmapData, _matrix);
            return _result;
 }
```

instead of dispose texture you can update it : https://forum.starling-framework.org/topic/update-a-texture

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
