### ISSUE TITLE
WKWebView support

### ISSUE THREAD

**Issue by nidiy** [myflashlab/webView-ANE#175]
Hello, 
    may I ask when can I support WKWebView?
     Also, I scroll on the IOS page seems very slow

**Comment by myflashlab** [comment]
moving to ```WKWebView``` is in our to-do list. will have more news soon.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
