### ISSUE TITLE
IOS multiple instances?

### ISSUE THREAD

**Issue by nidiy** [myflashlab/webView-ANE#177]
IOS webview can not multiple instances, The loaded URL will be overwritten by the last one

**Comment by myflashlab** [comment]
This is by design. you should create one instance of webview only. maybe we reconsider that but from experience, two instances of webview is lowering the app performance.

**Comment by nidiy** [comment]
A number of WebView instances are often used in a company's project, hoping to support multiple instances

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
