### ISSUE TITLE
openEmbeddedBrowser return false

### ISSUE THREAD

**Issue by AmeenAlHosani** [myflashlab/webView-ANE#178]
Hi, I am using Flash CS6, I bought RichWebView ANE
Air 25 & 26, android 6.0.1
I followed the instructions on this link
https://github.com/myflashlab/webView-ANE
theApp.apk Demo worked in my device
while testing EmbeddedBrowser (on same android device):
isEmbeddedBrowserInitialized return true
isEmbeddedBrowserSupported() return true
_ex.openEmbeddedBrowser("https://www.google.com/") return false
I don't think that there is a problem with RichWebViewSettings.EMBEDDED_BROWSER parameters

why openEmbeddedBrowser returning false

I am not using permissionCheck

Ameen Al Hosani
Kind Regards

**Comment by myflashlab** [comment]
Let's continue this discussion on this page: https://github.com/myflashlab/webView-ANE/issues/165
