### ISSUE TITLE
blank screen on load

### ISSUE THREAD

**Issue by Cyrillix** [myflashlab/webView-ANE#18]
Hi,

In our project, we use your ane to display our interface and it's working perflectly. 

But we have a little issue during load of our content, we see a blank page with a scrollbar that disappear after the load is done.

we have this effects  during 100ms I think.

is there a way to remove this effects ? Or maybe add the possibilty to add your web view in the stage when we want with addChild for example.

thanks.

**Comment by myflashlab** [comment]
Rich webview is happening on the native side and is on top of everything else in your flash project so it won't make sense to use flash's addChild method at all. but maybe you can create that effect by taking screenshots from your web page content.

about the initial load time, you can do an easy trick to avoid the white blank screen. listen for page load progress and create the webview with 1 pixel width and height so your flash app is still visible while the page is loading... and after the page load is complete, reszie the webview to fullscreen... that may help.

**Comment by Cyrillix** [comment]
Thanks for your answer , I'll try.
