### ISSUE TITLE
Cant compile with AIR 23

### ISSUE THREAD

**Issue by hans-ahrens** [myflashlab/webView-ANE#181]
When trying to compile with AIR 23 we get a missing resources error. This is triggered by the following extension: com.myflashlab.air.extensions.dependency.androidSupport

How can we fix this?

<img width="888" alt="screen shot 2017-08-21 at 17 18 59" src="https://user-images.githubusercontent.com/1682264/29526049-d861d53c-8694-11e7-84b5-b39e299bc85f.png">

**Comment by myflashlab** [comment]
Update your AIR SDK. 23 is just too old!

**Comment by hans-ahrens** [comment]
Ok, i got it to work with the latest Adobe AIR version
