### ISSUE TITLE
Embeddedbrowser - Toolbar

### ISSUE THREAD

**Issue by hans-ahrens** [myflashlab/webView-ANE#182]
Is there a way to hide the toolbar in the embedded browser?
Because it's visually not what we want to be displayed for the end user.

**Comment by myflashlab** [comment]
All the possible Android configurations for the custom-tabs is shown here: https://github.com/myflashlab/webView-ANE/blob/master/AIR/src/Main.as#L240-L253

Maybe what you need is to set 
```actionscript
RichWebViewSettings.EMBEDDED_BROWSER.android.enableUrlBarHiding = false;
```

Anyway, these are all the settings available for now.
