### ISSUE TITLE
IOS platform does not support using WebSocket

### ISSUE THREAD

**Issue by nidiy** [myflashlab/webView-ANE#183]
AIRSDK26,
 ANE v7.1.1
 can not use WebSocket, Calling WebSocket will exit APP.  but in the Android platform can be used normally

**Comment by myflashlab** [comment]
will you be able to provide us with more information on this and how we can test it? so maybe we can improve this if necessary?

**Comment by nidiy** [comment]
Use AIR26 StageWebView is normal, because air26 using WKWebView, please as soon as possible ANE support WKWebView

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
