### ISSUE TITLE
<v7.1.1> The arguments of InvokeEvent is gone. (on iOS)

### ISSUE THREAD

**Issue by ifalo-apps** [myflashlab/webView-ANE#186]
AIR SDK 26,
ANE v7.1.1
ios 10.3.2

```
NativeApplication.nativeApplication.addEventListener(InvokeEvent.INVOKE, onInvoke);
private function onInvoke(e:InvokeEvent):void
{
	trace(e.arguments.length);
}
```
When I launch my App by using URL Scheme, the e.arguments.length is always 0.
That is work fine on Andoird , and ANE v6.6.0 work fine on iOS and Android.

```
<iPhone> 
		<InfoAdditions>
			<![CDATA[
				<key>MinimumOSVersion</key>
				<string>8.0</string>
				
				<key>UIStatusBarStyle</key>
				<string>UIStatusBarStyleBlackOpaque</string>
				
				<key>UIRequiresPersistentWiFi</key>
				<string>NO</string>
				
				<key>UIPrerenderedIcon</key>
				<true />
				
				<key>UIApplicationExitsOnSuspend</key>
				<false/>
					
				<key>NSAppTransportSecurity</key>  
				<dict>  
					<key>NSAllowsArbitraryLoads</key><true/>  
				</dict>
				
				<!--required for webview GPS access-->
					<key>NSLocationUsageDescription</key>
					<string>I need location 1</string>
					
					<key>NSLocationWhenInUseUsageDescription</key>
					<string>I need location 2</string>
					
					<key>NSLocationAlwaysUsageDescription</key>
					<string>I need location 3</string>
				
				<key>UIDeviceFamily</key>
				<array>
					<!-- iPhone support -->
					<string>1</string>
					<!-- iPad support -->
					<string>2</string>
				</array>
				
				<key>CFBundleURLTypes</key>
				<array>
					<dict>
						<key>CFBundleURLName</key>
						<string>APP_ID</string>
						<key>CFBundleURLSchemes</key>
						<array>
							<string>go-myflashlabwebview-test</string>
						</array>
					</dict>
				</array>
				
			]]>
		</InfoAdditions>
		
		<requestedDisplayResolution>high</requestedDisplayResolution>
    </iPhone> 
```

The demo project should be easy to reproduce this issue. It is a matter of urgency, because it is a important feature of our upcoming game. Please check out as quickly as possible. Thank you very much!

EDIT: I can use the v6.6.0 instead, so it is not very urgent.

**Comment by myflashlab** [comment]
1. Are you sure this is not happening because of Adobe AIR SDK version? are you changing your AIR SDK version when seeing this problem?
2. The RichWebview ANE does not have anything to do with URLSchemes to begin with! Are you sure other ANEs in your project are not causing the problem?
3. When working with URLSchemes, have you considered using [Firebase](https://github.com/myflashlab/Firebase-ANE/wiki/I.1-Add-Dynamic-links)?

**Comment by ifalo-apps** [comment]
I tried a variety of combinations include switching AIR SDK version.
Above message just the result of my test.

**Comment by ifalo-apps** [comment]
When I use air sdk 30 beta, this issue is solved.
cheers

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
