### ISSUE TITLE
Problem with AirBridge.evoke

### ISSUE THREAD

**Issue by JokerDen** [myflashlab/webView-ANE#187]
Hi. I'm working on receiving actual userAgent via RichWebView. But have trouble similiar to #161 issue. AirBridge.evoke won;t execute and all code after it stops.

```
_webView = new RichWebView(Main.stageRef);
_webView.addEventListener(RichWebViewEvent.RECEIVED_MASSAGE_FROM_JS, handleMassage);
_webView.addEventListener(RichWebViewEvent.RECEIVED_MESSAGE_FROM_JS, handleMessage);
// what the difference between these events?

var dataSettings:HtmlDataSettings = new HtmlDataSettings();
dataSettings.baseUrl = null;
dataSettings.encoding = "UTF-8";
dataSettings.mimeType = "text/html";
dataSettings.historyUrl = null; // this property has no effect on the iOS side
dataSettings.data = "<html xmlns=\"http://www.w3.org/1999/xhtml\"><head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\"><script>'use strict';window.onload = function(){AirBridge.evoke('testing');alert(navigator.userAgent);}</script></head><body></body></html>";
_webView.openData(0, 0, 1, 1, dataSettings);
```
If you replace `AirBridge.evoke()` and `alert()`, alert shows normally (with correct userAgent).

Also i tried to put this code to onload function 
```
setTimeout(checkNow, 1000);
function checkNow() {
	if(typeof airBridge === 'undefined') {
		alert("A");
	} else {
		alert("B");
	}
}
```
but it always alerts A condition.

Is it possible to user AirBridge via `openData`? What I'm doing wrong? Platform is Android.

**Comment by JokerDen** [comment]
With `openWebViewLocal` AirBridge works fine.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
