### ISSUE TITLE
Unable to get data from AirBridge.evoke()

### ISSUE THREAD

**Issue by Bilbosax** [myflashlab/webView-ANE#188]
## Environment ##
* iOS Version: 9.3.5
* AIR SDK Version: 25

## Problem Description ##
I am trying to connect to an external webpage that I created that will be used to create a new user in my AIR app.  It is a PHP file not an HTML file, I don't know if that makes a difference.  I was able able to send a command from AIR to my webpage using _ex.callJS(), but I am unable to recieve a message from AIR using AirBridge.evoke().

**Here is a sample of my PHP file:**

```
<button id="photoButton" onclick="testClick()">UPLOAD PHOTO</button>
<script>
            function testClick() {
                AirBridge.evoke("Why Be So Dramatic");
            }
</script>

```
**And here is a sample of my AIR code:**

```
protected function init(event:FlexEvent):void {
		webView = new RichWebView(this.stage);
		// set optional RichWebview settings (apply these settings AFTER initializing the ANE and BEFORE opening a webpage)
		webView.addEventListener(RichWebViewEvent.RECEIVED_MESSAGE_FROM_JS, catchJavascriptMessage);
		RichWebViewSettings.ENABLE_BITMAP_CAPTURE = true;
		RichWebViewSettings.ENABLE_GPS = true;
		RichWebViewSettings.ENABLE_ZOOM = true;
		RichWebViewSettings.ENABLE_SCROLL_BOUNCE = false;
		RichWebViewSettings.BG_COLOR_HEX = "#FFFFFFFF"; // AARRGGBB
		RichWebViewSettings.ENABLE_AIR_PREFIX = true;
		RichWebViewSettings.USER_AGENT = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.36 (KHTML, like Gecko) Chrome/13.0.766.0 Safari/534.36";

		webView.openWebViewURL(0, AppVars.appHeight*.09, this.width, this.height*.85, "http://www.mywebsite.com/mypage.php");
}

protected function catchJavascriptMessage(event:RichWebViewEvent):void {
		trace("caught it");
		testLabel.text = event.param;
}
```

**And here is the part of my manifest dealing with iOS:**

```
<iPhone>
        <InfoAdditions><![CDATA[
			<key>MinimumOSVersion</key>
    		<string>8.0</string>
    		
    		<key>UIStatusBarStyle</key>
    		<string>UIStatusBarStyleBlackOpaque</string>
    		
    		<key>UIRequiresPersistentWiFi</key>
			<string>NO</string>
    		
    		<key>UIPrerenderedIcon</key>
		    <true />
        
		<key>UIDeviceFamily</key>
		<array>
			<string>2</string>
		</array>
			
		<key>NSAppTransportSecurity</key>
		<dict>
 		    <key>NSAllowsArbitraryLoads</key>
 		    <true/>
  		</dict>
    ]]></InfoAdditions>
    <requestedDisplayResolution>high</requestedDisplayResolution>
</iPhone>

<extensions>
    <extensionID>com.myflashlab.air.extensions.webView</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
</extensions>
```

Please let me know if you see anything that I am missing as I have spent the last two days slaving over this issue, and I am sure it is just an oversite on my part.  This is an iPad app, not an iPhone, so I don't know if that makes a difference.  Thanks for any help that you can provide.
(I also read that you used to have an AirBridge.js file that you injected to the HTML.  I don't know if your ANE has changed since those days, but I don't see an AirBridge.js file anywhere on my system.  Just thought I should mention that)

**Comment by Bilbosax** [comment]
I think I may have figured this one out on my own.  I noticed that the webView was not doing any of the form validation that you would expect in a normal browser on my iPad(I have no idea why), so i began to think that maybe the button click was not being heard by Javascript.  So I removed the <form> tags to make sure that my button was exposed, and voila!, it works now.  I guess I am going to have to do all the form validation myself as it does not appear to be supported using <form> tags in the mobile webView.

Please let me know if I am missing something!!!

**Comment by myflashlab** [comment]
The AirBridge is injected automatically to your web page by the ANE and as the ```_ex.callJS()``` command works, it means that you are doing everything right. but if the AIR side is not evoked by the JS calls, maybe that's because it's not being called at all.

So, you're saying that you removed ``the tags``` and it finally worked, could you please also explain which tags you moved? maybe this information helps other people with a similar question.

**Comment by Bilbosax** [comment]
Sorry, I actually did put the tag name inside of tag brackets and they got interpreted here as HTML HaHa!!

The tags that I removed were “form” tags. My button was inside of form tags, and I believe that the button click was not being heard for some reason. When I removed the form tags, everything worked as expected
