### ISSUE TITLE
Cannot dispose

### ISSUE THREAD

**Issue by matfabry** [myflashlab/webView-ANE#189]
hey guys

I cannot really dispose the richWebView.
Whenever I want to load a new page, I dispose the richWebView and create a new RichWebView(stage)

#1 
I created pages with setTimeout in JS sending a message to as3.
Then I load these pages one by one, disposing the richWebView every time.
I keep receiving these messages from all previously loaded pages.

#2
When I load a video file and then dispose the richWebView, I still can hear its audio.

This makes me think all the pages keep running in the background.
Or am I missing something?
Please advise.

## Environment ##
* iOS Version: 10.3.3
* AIR SDK Version: 27

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
