### ISSUE TITLE
SWC for the demo

### ISSUE THREAD

**Issue by timoisalive** [myflashlab/webView-ANE#19]
Hi,

I'd like to try the extension and you promise a free trial, but I can't seem to find the source code, swc or non-compiled anywhere in the repository. How should I use it in my project if I don't have the AS3 code? Thanks! :)

-Timo

**Comment by myflashlab** [comment]
You shouldn't need an swc for using an extension in your project. just use the .ane directly and also use the latest Air SDK 18 as it is today. all the required AS3 sample codes are also available in the FD folder (FlashDevelop project) if you check the document class .as file, you will know how to initialize the extension in your own project. works in Flash IDE, Flash Builder and Flash Develop of course.

**Comment by timoisalive** [comment]
I'm on IntelliJ and usually I always need the AS3 source outside the .ane file. I've included the ane in the project and the editor finds the classes and auto-imports them fine, but when I try to run I get an error:

[Fault] exception, information=VerifyError: Error #1014: Class com.doitflash.air.extensions.webView::MyWebView could not be found.

The src folder in FD or FB does not include the com.doitflash.air package at all.

**Comment by myflashlab** [comment]
sorry we have never used IntelliJ for compiling Air apps... yet I think if you can embed the .ane into your IntelliJ project, it should automatically find the classes.

**Comment by timoisalive** [comment]
Forgot to add the extensionID into the app descriptor, it compiled ok now. However, when I tried to make a MyWebView instance, I got the error #3500..

I think I gotta return to this a little later...
