### ISSUE TITLE
Erratic WebView Behavior

### ISSUE THREAD

**Issue by Bilbosax** [myflashlab/webView-ANE#191]
## Environment ##
* iOS Version: 9.3.5
* AIR SDK Version: 27

## Problem Description ##
I am using your Rich WebView ANE in my AIR app to try and take Stripe payments online.  Stripe has a javascript Module called Elements that allows you to take card payments.  When I run my PHP files containing Elements on a desktop browser, the Elements module behaves as it is supposed to.  It also works when I test the PHP scripts in safari on an iPad.  But in my AIR app, the Elements Module behaves erratically with the soft keyboard and tabbing between data fields.  I am testing on an iPad running version 9.3.5.  Display wise, Elements is behaving unpredictably and erraticly.  After I type in the credit card number, it is supposed to jump to the date field seemlessly, but it doesn't, the soft keyboard will scroll up and down the screen either once or twice(random), and then the cursor will either jump to the next field, or it will stay at the end of the previous field even though the keyboard does it's little dance.  So keyboard scrolling and moving from field to field are both random and erratic behaviors.  I don't really understand all this because my understanding is that a webview is simply a window to run the device's native browser in, not its own separate browser.  Am I wrong in my thinking?  Anyway, I have attached video links so you can view the behaviors I am talking about.  I hope you can give me some advice on anything that I might need to check.  Stripe is telling me that their Elements module is working in all major browsers on PC, Apple, and mobile devices, and that the problem must be the webview.  My testing on various other browsers on desktop and mobile would seem to support this theory.  Can you tell me if I might have a setting set up wrong that might be influencing this behavior?? 

Thanks!!

http://youtu.be/VHX_gl92SCA
http://youtu.be/De0unerfM9I

**Comment by Bilbosax** [comment]
I guess what I really want to know is this:  Is a webview a mini-browser that is packaged with AIR or in MyFlashLabs ANE, or is it a component provided by the operating system that that AIR has access to???

I don't know if the erratic behavior is a problem with iOS 9.3.5 and that it would not be a problem in a more modern operating system, or if it is a problem with AIR because they are packaging an outdated webview?  I don't have a more modern iPad to test my app on.  Does anyone know the answer to this???

Thanks!

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
