### ISSUE TITLE
requestBitmap() on a page with video stream shows a black rectangle

### ISSUE THREAD

**Issue by labcerouno** [myflashlab/webView-ANE#193]
* AIR SDK Version: all (except 28 beta, not tested)

I'm trying to request a bitmap from a webpage with video stream from Angel Cam/Click2stream, a page very similar to this https://langostinos.click2stream.com/. The bitmap shows the page correctly unless the video which appears as a black rectangle.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
