### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by Bilbosax** [myflashlab/webView-ANE#195]
## Problem Description ##
Just a simple question.  I am writing an Adobe AIR mobile app for both Android and iOS that uses the Rich Webview ANE.  In instances where a user loses internet connection and starts a new page in the webview, I would like to know if there is a way to set a Timeout in the webview, where if the page does not load by a certain amount of time, I can let the user know that they need to check their internet connection???

Right now, a user just sits indefinitely waiting and a page simply never loads.  Thanks for any help!!

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
