### ISSUE TITLE
Refresh Webview When App Regains Focus

### ISSUE THREAD

**Issue by Bilbosax** [myflashlab/webView-ANE#196]
## Problem Description ##
I am using the Rich Webview Ane in an AIR mobile app.  The problem that I am having is that when I minimize my app and use a couple of other apps, and then return to my app, sometimes the webview contains no content.  Is there some way to refresh the webview when the app regains focus on a mobile device??

Thanks for any help!!

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
