### ISSUE TITLE
Required Universal IOS Libraries

### ISSUE THREAD

**Issue by wigginsray** [myflashlab/webView-ANE#198]
Working in latest build of Adobe Animate 2018
AIR SKD 27 and 28 have been tested.

## Environment ##
* iOS Version: 11.2

I get the error "Invalid input." Error: libexOverrideNative.a, libexWebview.a, libexPermissionCheck.a are required to have universal IOS libraries. Please contact the ANE developer(s) to get the same.

I believe I have the latest versions of all the ANE's - I just downloaded them again today.

**Comment by wigginsray** [comment]
I'm an idiot. I copied my project from a Windows machine - including the AIR SDKs. I redownloaded the SDK's from Adobe for OSX and all is well. Maybe my goof will help some other goof.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
