### ISSUE TITLE
Question about handling Android file picker

### ISSUE THREAD

**Issue by blaber** [myflashlab/webView-ANE#2]
I've run into some limitations with StageWebView and it appears this UIWebView file upload limitation is also true for StageWebView (the file picker/chooser just doesn't pop up when the file upload form is invoked from Android): http://stackoverflow.com/questions/5907369/file-upload-in-webview

Is this a problem in your Android ANE as well?

**Comment by myflashlab** [comment]
@blaber if you can't upload from webView, you may use our extension and communicate with your AdobeAir app and let it take care of the job instead of webView! and besides, the extension is free to try with sample demo projects. feel free to run it and test it :)

**Comment by blaber** [comment]
Hmmmm...so this is for opening standard chooser forms for file uploads on
webpages.  As for my Adobe AIR code, it's pretty independent of web forms
like these, so I was hoping a WebView implementation would be able take
care of these basics.  According to my stackoverflow link it looks like
special mods need to be done for it to work; e.g., for lollipop to use
WebChromeClient.onShowFileChooser
<http://developer.android.com/reference/android/webkit/WebChromeClient.html#onShowFileChooser%28android.webkit.WebView,%20android.webkit.ValueCallback%3Candroid.net.Uri[]%3E,%20android.webkit.WebChromeClient.FileChooserParams%29>.
So would there be a way to access the extension's native Android code to
try out this mod?

**Comment by myflashlab** [comment]
I will note this down for next releases...

**Comment by myflashlab** [comment]
V3.0 will support file picker on both Android and iOS. to be released soon.
