### ISSUE TITLE
ios load problem

### ISSUE THREAD

**Issue by raresn** [myflashlab/webView-ANE#20]
Hey guys!
I`m trying to load a page using:
Main.webView.openWebViewURL(0, 0,width,height,"http://www.google.com");
then when I press a button I try to load another page:
Main.webView.openWebViewURL(0, 0,width,height,"http://www.otherpagehere.com");
But what happens is that url doesn't change - if the first page is scrolled a bit, it just scrolls back up.

I have this problem on iOS

**Comment by myflashlab** [comment]
This is actually what the extension is supposed to work. you see, whenever you call ```openWebViewURL``` or ```openWebViewLocal```, it means that a new webview window should open and if it is already open, then it won't work.

there are two workarounds though:
1. change url using links in your html page
2. call ```Main.webView.closeWebView();``` first and then open your new URL

**Comment by raresn** [comment]
It doesn't makes complete sense to me why I can't just navigate away without calling a function, BUT,
what you just said works great and I would like to thank you for the prompt response.
You now have a new client! :)

**Comment by myflashlab** [comment]
Hearing dev opinions will help us better improve our extensions and how they function. Thanks.
