### ISSUE TITLE
Exception creating RichWebView instance v7.1.3

### ISSUE THREAD

**Issue by JasonRaspison** [myflashlab/webView-ANE#202]
## Environment ##
* Android API Version: 23
* iOS Version: 10.2
* AIR SDK Version: 26

## Problem Description ##
When I try to create an instance of RichWebView in my code I always get this exception:
Exception fault: TypeError: Error #1006: value is not a function.
	at com.myflashlab.air.extensions.webView::RichWebView()
	at com.powerflasher.SampleApp::WebViewTest/init()[WebViewTest.as:33]
	at com.powerflasher.SampleApp::WebViewTest/onAdded()[WebViewTest.as:28]
	at runtime::ContentPlayer/loadInitialContent()
	at runtime::ContentPlayer/playRawContent()
	at runtime::ContentPlayer/playContent()
	at runtime::AppRunner/run()
	at AppEntryCommon/run()
	at global/runtime::AndroidMobileDeviceAppEntry()

This is only on the latest version of the ANE. If I grab the older v7.1.1 ANE (demo version) and use that the web view can be created and it works as expected. I've looked through the readme on how to set up my project and I cannot see anything different.

I created a sample app to test if it was just my setup. but i get the same exception (the stack trace above is from that)

I would've tried to use a full version of 7.1.1, but I can't find a download for that.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<application xmlns="http://ns.adobe.com/air/application/26.0">
  <id>com.powerflasher.SampleApp</id>
  <filename>WEBVIEWTEST</filename>
  <name>My Application</name>
  <versionNumber>1.0.0</versionNumber>
  <initialWindow>
    <content>WEBVIEWTEST.swf</content>
    <aspectRatio>portrait</aspectRatio>
    <fullScreen>false</fullScreen>
    <autoOrients>false</autoOrients>
    <visible>true</visible>
    <renderMode>direct</renderMode>
  </initialWindow>
  <android>
    <manifestAdditions><![CDATA[<manifest android:installLocation="auto">
    
    <uses-sdk android:targetSdkVersion="23"/>
    
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.LOCATION_HARDWARE" />
    
    <application android:enabled="true" android:hardwareAccelerated="true" android:allowBackup="true">
      <activity android:hardwareAccelerated="true">
        <intent-filter>
          <action android:name="android.intent.action.MAIN" />
          <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
        <intent-filter>
          <action android:name="android.intent.action.VIEW" />
          <category android:name="android.intent.category.BROWSABLE" />
          <category android:name="android.intent.category.DEFAULT" />
        </intent-filter>
      </activity>
      
      <!-- required for html file select buttons -->
	  <activity android:name="com.doitflash.webView.Pick" android:theme="@style/Theme.Transparent" />
	
	  <!-- required for customtabs support on Android -->
	  <receiver android:name="com.doitflash.webView.ChromeTabActionBroadcastReceiver" />
    </application>
  </manifest>]]></manifestAdditions>
  </android>
  <supportedProfiles>desktop extendedDesktop mobileDevice extendedMobileDevice</supportedProfiles>
  <extensions>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
    <extensionID>com.myflashlab.air.extensions.webView</extensionID>
    <extensionID>com.myflashlab.air.extensions.permissionCheck</extensionID>
  </extensions>
</application>
```

```actionscript
package com.powerflasher.SampleApp
{
	import avmplus.getQualifiedClassName;
	import com.myflashlab.air.extensions.nativePermissions.PermissionCheck;
	import flash.display.StageAlign;
	import flash.display.StageScaleMode;
	import flash.events.Event;
	import com.myflashlab.air.extensions.webView.RichWebView;
	import flash.display.Sprite;

	/**
	 * @author
	 */
	public class WebViewTest extends Sprite
	{
		private var _webView:RichWebView = null;
		
		public function WebViewTest()
		{
			stage.scaleMode = StageScaleMode.NO_SCALE;
			stage.align = StageAlign.TOP_LEFT;
			
			addEventListener(Event.ADDED_TO_STAGE, onAdded);
		}
		
		private function onAdded(event:Event):void
		{
			init();
		}
		
		private function init():void
		{
			_webView = new RichWebView(stage);
			_webView.openWebViewURL(0, 0, stage.stageWidth, stage.stageHeight, "http://www.google.co.uk/");
		}
	}
}
```

## Steps to Reproduce ##
I created an empty air project in FDT, implemented the code above and ran it. I get the exception no matter when I try to call new RichWebView()

## Known Workarounds ##
The only workaround I have found so far is to use an older version, however, the only older version I could find is the demo version on GitHub.

Thanks for any help.

Jason.

**Comment by myflashlab** [comment]
This is weird! This is what I can begin with. Can you confirm if the error happens if you have this line only?
```
_webView = new RichWebView(stage);
```

**Comment by JasonRaspison** [comment]
Yeah. As soon as I call new RichWebView(stage); I get the exception.

**Comment by JasonRaspison** [comment]
I've worked out what was causing this issue. Our project uses some other ANEs from flashlabs and the versions we had of some of the dependancies were out of date. This caused an exception to be thrown in the code of the constructor of the RichWebView ANE saying that a function relating to the ANE-LAB didn't exist. Updating our dependancies fixed this.

**Comment by myflashlab** [comment]
Aha, good, happy it’s fixed. Always make sure you have the latest version because using a mix of older versions together can create unpredictable errors :)
