### ISSUE TITLE
Camera from html5 input file

### ISSUE THREAD

**Issue by Tecnored** [myflashlab/webView-ANE#204]
Hi.
Does the capture="camera" property of an html5 input file work?
Always open the file selection instead of the camera to take a picture.

I am testing the component to buy it and this function is important for me.

TNK!

**Comment by myflashlab** [comment]
We have not tested this specific feature but it's an interesting one and if doesn't help, we'd be happy to help. The first thing to consider is to use the [permission ANE]() to give the camera permission prior for the webview to open camera. Let us know how does your tests go. If you can send us log messages in case of an error, that would be helpful too.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
