### ISSUE TITLE
how can i use webview ane 

### ISSUE THREAD

**Issue by moazatiani** [myflashlab/webView-ANE#205]
i am new silver club member ,so i want tutorial about how can i use webview ane by adobe animate or manual with steps for using this item to build android application

**Comment by myflashlab** [comment]
using the RichWebview is simple enough. first you need to implement the ANE into your project. You can do that manually or you may try the ANELAB software. If you are doing it manually, these videos can help you. https://www.youtube.com/playlist?list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O
When correctly implemented, check out the sample project in this repository and see how you should initialize the ANE and set its params. Sample project is a pure AS3 project which you can be inspired for your project even if it is AdobeAnimate IDE.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
