### ISSUE TITLE
Close/hide Embedded Browser

### ISSUE THREAD

**Issue by hpeide** [myflashlab/webView-ANE#206]
I have some problems with closing an openEmbeddedBrowser from actionscript?

My app is a dual app with web content which opens in an webview. I use Firebase external links in the web content to go back to activities in the app. All this work as expected, except I fail to close the active webview after the InvokeEvent is triggered. I've tried to use dispose, closeWebview and disposeEmbeddedBrowser methods and noting happen, the webview keep standing as a rock.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
