### ISSUE TITLE
Hide webview buttons

### ISSUE THREAD

**Issue by hpeide** [myflashlab/webView-ANE#207]
Is it possible to hide the 'Share' and 'Safari' button somehow? Or manipulate them with the callJS method?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
