### ISSUE TITLE
Open camera for input type file in Webview

### ISSUE THREAD

**Issue by winglovecola** [myflashlab/webView-ANE#208]
Hello,

I'm wondering how can I enable the camera in Rich WebView using the following html code:

`<input type="file" accept="image/*;capture=camera"/>`

this code only working in EMBEDDED_BROWSER mode but not in local webview. Please advice how can I make this to work in local webview.

Thank you.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
