### ISSUE TITLE
Problems building in Flash CC 2014

### ISSUE THREAD

**Issue by gmagge** [myflashlab/webView-ANE#21]
Would it be possible to see an example of this build using Flash CC? Just wondering as I keep getting an error when publishing. The error states there is a problem with the descriptor name. I've checked the name in the manifest and it matches what I put in in Flash, but no cigar. Thanks

**Comment by myflashlab** [comment]
make sure you are using the latest Air SDK and in your Air .xml manifest file, make sure you have at least 15.0 as your namespace```<application xmlns="http://ns.adobe.com/air/application/15.0">```

**Comment by gmagge** [comment]
That did it! Thanks for the assistance.
