### ISSUE TITLE
Airbridge

### ISSUE THREAD

**Issue by fix89** [myflashlab/webView-ANE#210]
Hi, I'm trying this demo ANE before purchase. How can I test the AirBridge? I don't understand what to add on JS

**Comment by myflashlab** [comment]
It's very simple actually. here's more information: https://github.com/myflashlab/webView-ANE#setup-javascript

And on top of that, you can learn more about JS setup on the sample project we have https://github.com/myflashlab/webView-ANE/tree/master/AIR/bin/demoHtml

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
