### ISSUE TITLE
Network Monitor doesn't work

### ISSUE THREAD

**Issue by DanielSLeblanc** [myflashlab/webView-ANE#211]
Having problems with an asp page, so I tried using the Network Monitor.
No data shows up.
Is there another way to see all the requests and responses?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
