### ISSUE TITLE
iOS crashes when loading a lot of websites during one session

### ISSUE THREAD

**Issue by xxxVBxxx** [myflashlab/webView-ANE#212]
## Environment ##

* iOS Version: 10.0.2
* AIR SDK Version: 29

## Problem Description ##
Hello. I'm using richWebView to show official website of the components, that I have in my app. And it works great for most of the cases (both iOS and Android ). 
But in particular case (iPhone 6+ OS 10.0.2) I got a crash. The app just goes down . There are no logs and even with adobe scout I couldn't manage to reveal anything.  
If you have similar experience please let me know. 

## Steps to Reproduce ##
I have to just open the app. 
And one by one try all the websites. After several websites loaded, the app crashes and closes.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
