### ISSUE TITLE
Rarely showing admob ads

### ISSUE THREAD

**Issue by LeapingSwan** [myflashlab/webView-ANE#213]
Hi

AIR SDK 30.0
iOS Minimum 8.0 or Higher

I am using the demo version of the Admob plugin until I am satisfied it works.

I am getting banner ads on rare occasions but most of the time they don't show on screen.  Traces show that they are being loaded (I am triggering the onBannerLoaded event ok).  This is true for my own ad IDs and also for the Admob test ID's.

I have checked my admob account but can see no problems there and in any event this also does not work with the test ad unit IDs.  Happy to provide my own ad unit ID's privately.

My code is:
```actionscript
		private function setUpAds() 
		{
			
			trace("OverrideAir.os " + OverrideAir.os);
			// initialize AdMob and pass in the Adobe AIR Stage and your AdmMob ApplicationCode
			if(OverrideAir.os == AdMob.ANDROID) 
			{
				trace("Initiate Android");
				AdMob.init(stage, "ca-app-pub-xxxxxxxxxxxxxxxxxxx")
				

			} else if(OverrideAir.os == AdMob.IOS) 
			{
			
				trace("Initiate iOS");
				
				AdMob.init(stage, "ca-app-pub-xxxxxxxxxxxxxxxxxx");
				
			}else{
				trace("Not iOS or Android")
			}
			
			AdMob.api.addEventListener(AdMobEvents.AD_CLOSED, onAdClosed);
			AdMob.api.addEventListener(AdMobEvents.AD_FAILED, onAdFailed);
			AdMob.api.addEventListener(AdMobEvents.AD_LEFT_APP, onAdLeftApp);
			AdMob.api.addEventListener(AdMobEvents.AD_LOADED, onAdLoaded);
			AdMob.api.addEventListener(AdMobEvents.AD_OPENED, onAdOpened);

			// listen to the banner Ad to get its final width/height in pixels so you can place it anywhere you like in your Air app
			AdMob.api.banner.addEventListener(AdMobEvents.SIZE_MEASURED, onBannerAdSizeReceived);
			
			
			
			trace("setUpAds completed");

		}


		
		private function showBanner(cEvent:CustomEvent)
		{
			trace("SB Constants.currentBanner " + Constants.currentBanner);
			AdMob.api.banner.init(Constants.currentBanner, ApiBannerAds.BANNER);
			
			adRequest = new AdRequest();
			
			adRequest.testDevices = [
				"zzzzzzzzzzzzzzzzzzzzzzzzzzzz"
				];
			
			
			AdMob.api.banner.loadAd(adRequest);
			
			

		}


		// If you wish to change the position of the loaded banner, which is (0, 0) by default, you should listen for AdMobEvents.AD_LOADED
		private function onAdLoaded(e:AdMobEvents):void
		{

			trace("onAdLoaded " + e.adType);
			if (e.adType == AdMob.AD_TYPE_BANNER)
			{
				trace("placing ad");
				AdMob.api.banner.x = Constants.MidX - (AdMob.api.banner.width / 2);
				AdMob.api.banner.y = Constants.MidY - (AdMob.api.banner.height / 2);
				trace("AdMob.api.banner.x " + AdMob.api.banner.x);
				trace("AdMob.api.banner.y " + AdMob.api.banner.y);
				
			}else{
				trace("no add position");
			}
	
		}
```
And this produces the following traces:
```
startBanner
SB Constants.currentBanner ca-app-pub-yyyyyyyyyyyyyy
e.errorCode -1
e.height 70
e.width 1559
e.toString() [Event type="onBannerSizeMeasured" bubbles=false cancelable=false eventPhase=2]
onBannerAdSizeReceived
onAdLoaded banner
placing ad
x = -217
y = 1183
AdMob.api.banner.x -217
AdMob.api.banner.y 1183
startBanner
SB Constants.currentBanner ca-app-pub-3940256099942544/6300978111
e.errorCode -1
e.height 70
e.width 1559
e.toString() [Event type="onBannerSizeMeasured" bubbles=false cancelable=false eventPhase=2]
onBannerAdSizeReceived
onAdLoaded banner
placing ad
x = -217
y = 1183
AdMob.api.banner.x -217
AdMob.api.banner.y 1183

```

**Comment by LeapingSwan** [comment]
Hi guys can you please take a look at this one?  I have been away on holiday for a couple of weeks but back at it now and could really do with some help on this.  It seems I'm so close to getting it working but not quite there.

Thanks

Stephen

**Comment by LeapingSwan** [comment]
A further update on this I have added Interstitial and Reward videos and both of these work as expected, so it's only the Banner ads that I am having a problem with.

Thanks

Stephen

**Comment by LeapingSwan** [comment]
I have discovered that I was using the Android unit test IDs when testing on an iOS device.  I have now changed this but it has not made a difference.  Banner adds, test or real, are still shown as loaded but are not being displayed.

**Comment by myflashlab** [comment]
Sorry about the late reply, it was a confusion because you have posted an issue about Admob ANE here in the RichWebView ANE.

here's an idea, but I'm closing the issue here as it's unrelated. feel free to open a new one in Admob Repository

Please activate the [OverrideAir debugger](https://github.com/myflashlab/Admob-ANE/blob/master/AIR/src/Demo.as#L154-L157)
```actionscript
OverrideAir.enableDebugger(myDebuggerDelegate);
```
and see if you can find more useful information there?

And besides, have you tried other banner sizes? for example [SMART_BANNER_PORTRAIT](http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/admob/ApiBannerAds.html#SMART_BANNER_PORTRAIT) or [SMART_BANNER_LANDSCAPE](http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/admob/ApiBannerAds.html#SMART_BANNER_LANDSCAPE)?
