### ISSUE TITLE
Why does it say Demo mode when I have the Master collection for WebView?

### ISSUE THREAD

**Issue by thatkidrich** [myflashlab/webView-ANE#214]
I have tried everything. Loading it from the downloaded zip and try installing it from the Labs App

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
