### ISSUE TITLE
 WebKitErrorDomain error 101

### ISSUE THREAD

**Issue by jonathonpitman** [myflashlab/webView-ANE#217]
Cannot load page due to " WebKitErrorDomain error 101"  Is this a string encoding issue ?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
