### ISSUE TITLE
%25 being added to my URLS

### ISSUE THREAD

**Issue by jonathonpitman** [myflashlab/webView-ANE#219]
My urls are setup like this

https://domain.com/main?id=q71Tgp8Omvp6tSvQzhClBvLW%2bcPZTFhj

When I try to open this page..  for some reason the webview is adding %25 right before the %2

https://domain.com/main?id=q71Tgp8Omvp6tSvQzhClBvLW%252bcPZTFhj

Any idea why this would be happening ?

**Comment by myflashlab** [comment]
The ANE encodes URLs to standard versions. That's probably what is happening. instead, try loading the following and see what happens: notice that ```%2b``` is changed to ```+```

https://domain.com/main?id=q71Tgp8Omvp6tSvQzhClBvLW+cPZTFhj

**Comment by jonathonpitman** [comment]
This doesnt work. The server expects the %2 to be there in the string.

**Comment by jonathonpitman** [comment]
Any progress ?

**Comment by myflashlab** [comment]
Well, we tested this but don't seem to be able to duplicate the problem. We are seeing the returned url from the ```RichWebViewEvent.PAGE_STARTED``` listener and the url is not changed. Can you better help us to duplicate the problem?

**Comment by jonathonpitman** [comment]
Correct... this is happening on iOS

**Comment by myflashlab** [comment]
We are in the process of rebuilding the whole ANE from scratch. that may fix the weird problem you are facing with URLs.

**Comment by jonathonpitman** [comment]
Any ETA on the release ?

**Comment by jonathonpitman** [comment]
Any updates on this?

**Comment by myflashlab** [comment]
We're hoping that the new ANE would be ready in a week or two. guys are working on that. The Android side is already completed but the iOS side needs more time.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
