### ISSUE TITLE
IOS7 crash on app launch (works fine on IOS8 and IOS9)

### ISSUE THREAD

**Issue by Barendnu** [myflashlab/webView-ANE#22]
When including the V3.0 webView-ANE in our project (Adobe Air SDK 19.0.0.190), the app crashes on startup on IOS7. Works fine on IOS8 and IOS9, but iPhone4 users cannot upgrade to anything newer than IOS7.

Maybe the ANE is not 32bit compatible for IOS?

**Comment by myflashlab** [comment]
I think maybe we should update the min requirement as we also have lost our old devices with iOS7 but I don't think that would be much of a problem because only 8% of devices are still using iOS < 8 according to apple https://developer.apple.com/support/app-store/
