### ISSUE TITLE
android keyboard on webview

### ISSUE THREAD

**Issue by mohammadfard1365** [myflashlab/webView-ANE#220]
hi.
 
if my loaded page have textbox and i click it , android native keyborad apear, but android keyboard show on top of webview and i can not see behind. webview must resize but not resize

please help me

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
