### ISSUE TITLE
Send a Header to RichWebView

### ISSUE THREAD

**Issue by Bilbosax** [myflashlab/webView-ANE#221]
## Problem Description ##
Does anyone know if it is possible to send a header using this ANE to perform HTTP Basic Authentication?  I do not want a login box to appear in the browser, I want to be able to pass the username and password in a header, but don't know how it is possible to pass it to this ANE.  Could someone please give me a basic outline of how you would accomplish this using a class in Flex in combination with the RichWebView ANE?

Thanks!!

**Comment by Bilbosax** [comment]
14 days with no comment.  Plus, I sent a direct email to MyFlashLabs for support, and no response.  I would rather hear "no, you can't send a header" than nothing at all.  The technical support with these guys is just....well, horrible.

**Comment by myflashlab** [comment]
Oh, sorry missed that. no , it's not possible yet but we are trying to make that possible with the new version of the ANE. A lot will be changed in the new release. we're working on it.... Sorry for missing the ticket.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
