### ISSUE TITLE
WebGL (three.js)

### ISSUE THREAD

**Issue by Tecnored** [myflashlab/webView-ANE#222]
Hello,
I am trying to load an external page in the webView (openWebViewURL) that uses three.js model.
The page is not seen correctly. You see everything but NOT the 3D model.
The same happens if I load the page locally.

Can you tell me if I have to configure something to be able to use webGL (three.js)

TNK !

PS: Both the online and the local page look correctly in all browsers.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
