### ISSUE TITLE
Window Dimension

### ISSUE THREAD

**Issue by RichPitul** [myflashlab/webView-ANE#223]
## Environment ##
* iOS Version: 11
* AIR 31.0.0.96

## Problem Description ##

When I trace or alert the dimensions of the window within flash I get correct sizes, in this current case 4096 by 3072; which is fullscreen in landscape of my IPad Pro, but then if I alert the size of the window from within the WebView it reports back that it is 1024 by 768.
```
alert($(document).width() + ":" +  $(document).height());
In my HTML I have this meta tag
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```
There must be something I am missing.

```xml
<application xmlns="http://ns.adobe.com/air/application/31.0">
  <id>com.c1ms.richardtest</id>
  <versionNumber>1.0</versionNumber>
  <filename>Test</filename>
  <description/>
  <name>Test</name>
  <copyright/>
  <initialWindow>
    <content>test.swf</content>
    <systemChrome>standard</systemChrome>
    <transparent>false</transparent>
    <visible>true</visible>
    <fullScreen>true</fullScreen>
    <renderMode>auto</renderMode>
    <autoOrients>true</autoOrients>
    <aspectRatio>landscape</aspectRatio>
  </initialWindow>
  <icon>
    <image29x29>logos/Icon-29.png</image29x29>
  </icon>
  <customUpdateUI>false</customUpdateUI>
  <allowBrowserInvocation>false</allowBrowserInvocation>
  <iPhone>
    <InfoAdditions><![CDATA[
  <key>UIDeviceFamily</key>
  <array>
    <string>2</string>
  </array>
]]></InfoAdditions>
    <requestedDisplayResolution>high</requestedDisplayResolution>
  </iPhone>
  <extensions>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
    <extensionID>com.myflashlab.air.extensions.permissionCheck</extensionID>
    <extensionID>com.myflashlab.air.extensions.webView</extensionID>
  </extensions>
</application>
```

```actionscript
var windowDimensions:Rectangle = new Rectangle(0, 0, stage.stageWidth, stage.stageHeight);
var mainPage:File = File.documentsDirectory.resolvePath("arena/ios.html");
richWebView.openWebViewLocal(0, 0, windowDimensions.width, windowDimensions.height, mainPage);	
```

**Comment by RichPitul** [comment]
I'd like to add the if I turn debugging on, I see some output from the RichWebView constructor, listing that the stageWidth and stageHeight are 4096x3072, but the nativeWidth and nativeHeight are 1024x768, and the _ratio is 0.25; this does explain why the internal dimensions of the webview are 1024x768; but not how to let them go higher as they should. 

Perhaps there is an additional setting I need to add to the xml?

**Comment by RichPitul** [comment]
Any way to get an update on this? Getting to the point that I'll have to figure something out and possibly switch back to the default StageWebView which doesn't seem to have this same issue.

**Comment by myflashlab** [comment]
We are working on a totally new RichWebview ANE. However, about this question, a workaround would be maybe to pass the dimention from AIR to JS directly instead of letting JS find the size?

The thing is that especially on iOS, the width/height returned from AIR is always different from the native window.

**Comment by RichPitul** [comment]
That's cool that there is going to be a totally new one; any idea on a timeframe on that? The dimensions are something I could definitely pass into the view from AIR; with this information is there a way to change the web view's window dimensions, and still keep it taking up the full screen? 

The main problem is that my site looks very low resolution when rendered at 1024x768. It even gets some of my mobile styling at that resolution when I would really prefer it to receive the high resolution css. I tried fooling around with the initial-scale viewport tag but that only works if I have the ENABLE_ZOOM RichWebView setting set to true, and then a user could also pinch and zoom the page which is not really what I want.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
