### ISSUE TITLE
Buid App on Android Studio

### ISSUE THREAD

**Issue by larrymeng** [myflashlab/webView-ANE#224]
Hi, I want to make webview supporting Flash in my Adnroid App and I see this ANE.
But I'm confused.
Can any body provide a completed and detailed example with Android Studio?
:)

**Comment by ROBERT-MCDOWELL** [comment]
unfortunately.. thanks Mr Job..
if you want to use flash on IOS and Android only puffin browser can do it

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
