### ISSUE TITLE
Local HTML files will not load

### ISSUE THREAD

**Issue by jonathonpitman** [myflashlab/webView-ANE#226]
None of the methods in your example seem to work to load local HTML files.  Is there an updated syntax or something ?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
