### ISSUE TITLE
ArgumentError: Error #3500: The extension context does not have a method with the name command.

### ISSUE THREAD

**Issue by laxmipa** [myflashlab/webView-ANE#25]
Hi, I bought the commercial version recently. I created app using Flash CC 2015. When i test it, i am getting below error.
ArgumentError: Error #3500: The extension context does not have a method with the name command.

Also, how do I load html string instead of file / url?

Thanks

**Comment by myflashlab** [comment]
> ArgumentError: Error #3500: The extension context does not have a method with the name command

This is a common error when the ane is not correctly embeded into your project. please make sure you that the .ane file is embeded into your project.

parsing html Strings is not yet available. we have it in our to-do list for V5.0 release which should be out in mid November.

**Comment by laxmipa** [comment]
Thanks. I am embedding the ANE in same way i embedded other ANEs. It seems,
it is working in real device. Do i need to test it in real device every
time? or is there a way to test it in windows / mac?

Thanks



On Mon, Oct 12, 2015 at 12:43 AM, myflashlab <notifications@github.com>
wrote:

> ArgumentError: Error #3500: The extension context does not have a method
> with the name command
>
> This is a common error when the ane is not correctly embeded into your
> project. please make sure you that the .ane file is embeded into your
> project.
>
> parsing html Strings is not yet available. we have it in our to-do list
> for V5.0 release which should be out in mid November.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/webView-ANE/issues/25#issuecomment-147290667>
> .
>



-- 
Regards
Lakshmi Ramakrishnan.

**Comment by myflashlab** [comment]
aha, yes, that could be the other reason. yes, this extension is using the built in native webview and needs to run on a real device only.

**Comment by myflashlab** [comment]
for anyone else having a similar problem, check this playlist https://www.youtube.com/watch?v=Oubsb_3F3ec&list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O
