### ISSUE TITLE
Hide Softkeyboard

### ISSUE THREAD

**Issue by Cyrillix** [myflashlab/webView-ANE#27]
Hi,

It could be nice to be able to hide/show softkeyboard when we have focus on input or textarea.

Thanks,

**Comment by myflashlab** [comment]
Thanks for your input. I wrote down this to be considered in future versions. yet, tell me if this could be a solution to your question? http://stackoverflow.com/a/8349838/247658

**Comment by Cyrillix** [comment]
Thanks for the link , I have implemented it with success but of course that's a lot better to have it in your ANE.

An other usefull things to have, is soft keyboard size, currentlly we detect it on stage resize.

**Comment by myflashlab** [comment]
I appreciate your inputs. These helpful notes will help us keep our extension updated with some handy features. I will add these to the to-do list board. thx.
