### ISSUE TITLE
Error Occured while packaging the application

### ISSUE THREAD

**Issue by manuims** [myflashlab/webView-ANE#29]
Hi,

When i package the flex mobile application with webView.ane file i am getting a package error as attached below in the link. Please help me to find a solution asap.
![error](https://cloud.githubusercontent.com/assets/15225649/10628401/85560ccc-77e2-11e5-8e34-a36f55cff147.PNG)

**Comment by myflashlab** [comment]
That's weird. the WebKit framework comes with AdobeAir SDK. are you sure you are using the latest Air SDK? also look into this folder on your Air SDK and see if the webkit framework is really there? "flex_sdk_4.6_air_sdk_19-190\lib\aot\stub\WebKit.framework" 

if it's not there, it probably means your Air SDK installation is broken and you should download and install Air SDK again.

**Comment by manuims** [comment]
Thanks for the prompt response and now i am using Apche flex 4.14.1 FP17 AIR17 which has WebKit.framework.
