### ISSUE TITLE
Ane is not working for me.

### ISSUE THREAD

**Issue by hesapyonetimi** [myflashlab/webView-ANE#3]
i bought ane and downloaded. When I create a new Webview instance,  But i get an error like this.
com.doitflash.air.extensions.webView.android::Android
Why?

**Comment by myflashlab** [comment]
it seems like you have not correctly embeded the ane into your project. use the sample codes available in github and just replace the .ane with the one you have purchased.

**Comment by myflashlab** [comment]
check this playlist https://www.youtube.com/watch?v=Oubsb_3F3ec&list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O
