### ISSUE TITLE
how to call custom  javascript:myFunction() from apache flex for ios using webview-ANE?

### ISSUE THREAD

**Issue by manuims** [myflashlab/webView-ANE#31]
Hi,

 I have an HTML page in server which i am loading in my ipad using openWebViewURL().
But i have a custom function named JS myFunction() in HTML page which should accept string from flex. 

Please guide me on how to achieve this using webview-ANE.

**Comment by myflashlab** [comment]
the sample codes here https://github.com/myflashlab/webView-ANE will teach you how to do it exactly... but basically, you will be able to call any public JS function like this ```_ex.callJS("yourJSFunction('your params')");```
