### ISSUE TITLE
disable bounce on iphone

### ISSUE THREAD

**Issue by Cyrillix** [myflashlab/webView-ANE#32]
Hi,

In order to have webview like an application on iphone , il could be nice to be able to disable bounce for our view.

it's possible with js via preventing touchmove , but it would be better to have it in a dedicate function with your ane.

Thanks

**Comment by myflashlab** [comment]
I'll write this down. thx.

**Comment by Cyrillix** [comment]
when do you plan to release this feaaure ?

thanks

**Comment by myflashlab** [comment]
We don't have it in our 2015 to-do list based on our recent company merge process but the good news is that we will soon add many new ANE updates and new ANEs... we are getting more focused and more organized. you can read the news here if you haven't seen it yet. http://myflashlab.com/myappsnippet/ Thanks for your patience but good things are about to happen :)

**Comment by Cyrillix** [comment]
We have solve this by creating our ANE to set theWebView.scollview.bounce = NO;

**Comment by myflashlab** [comment]
This feature is now added to the upcoming release. working on Android and iOS.
