### ISSUE TITLE
Severe Crash issue on Android 

### ISSUE THREAD

**Issue by raresn** [myflashlab/webView-ANE#34]
Hey guys,
We were ready to deploy our app to our customers +5000 employees and we are counting on this extension to work. Here is the problem:
- on an Galaxy S5 running Lolipop 5.0 when we load a page it causes the App to crash when we load a particular page.
Here is the trace on what is going on:
[Web View] - Loading URL: https://website-here/default.aspx?AuthTicket=f45f021e-2729-4f3e-9c24-ffb0aa84c1a1 6.701
[Web View] - page started to be loaded https://website-here/default.aspx?AuthTicket=f45f021e-2729-4f3e-9c24-ffb0aa84c1a1 8.892
Debug session terminated.

-This works on all tested iOS devices, on a Galaxy Note 3 running Lolipop 5.0, and a Note 8 Tablet running on 4.4.2

At the moment we are quite desperate - we need to get this working in the following few days or our business will suffer greatly. 
I am willing to be online and talk to you at any time of your convenience, share screen, debug, anything - just le me know.

Thank you.

**Comment by myflashlab** [comment]
you mean that specific url working on all other devices accept for Galaxy S5? Please check if that URL is working in the native browser app? or Adobe's StageWebView? if it fails there too, it means that specific device and Android V can't correctly parse the page or something like that and there's not much we can do to help but if it's working fine on other tests I suggested, then send us the demo app to test locally too.

**Comment by raresn** [comment]
This was due to an script running wild on the page we attempted to load. I am sorry for wasting your time.

**Comment by myflashlab** [comment]
We're glad the problem is resolved. Happy coding Flash :)
