### ISSUE TITLE
IOS focus management

### ISSUE THREAD

**Issue by Cyrillix** [myflashlab/webView-ANE#35]
Hi ,

In order to resolve some focus problem due to apple security implementation by apple

we loose focus it's not coming from user interaction

it could be nice to have the possibilty to define the following option of the UIWebview

theWebView.keyboardDisplayRequiresUserAction = NO;

see :http://stackoverflow.com/questions/6287478/mobile-safari-autofocus-text-field/7332160#7332160

thanks

**Comment by Cyrillix** [comment]
what do you think about it ?

**Comment by Cyrillix** [comment]
We have solve this by creating our ANE to set theWebView.keyboardDisplayRequiresUserAction = NO;

**Comment by myflashlab** [comment]
V6.0.0 will have this feature added. thanks.
