### ISSUE TITLE
DynamicFunc.as / passing arguments from JS to AS3

### ISSUE THREAD

**Issue by dommermuth** [myflashlab/webView-ANE#36]
Hello, this is just a note to future users.  In order to use this ANE it appears that the author expects you to use DynamicFunc to process the single parameter you can pass from JS to AIR.  

The problem is the DynamicFunc 'run' method very well may split your argument incorrectly.   Ultimately this may result the in the wrong number of arguments being passed to your flash function.  This in turn will break your app.

For, me the answer was simple.  From JS, I send a comma delimited string.  The first item in the string is the name of the flash function you wish to call.  Everything after is the parameters.  So, it may look like this:

JavaScript:

Bridge.call("myFlashFunction, arg1, arg2");

AS3

_richwebview = new RichWebView(stage, true, true, false, true); _richwebview.addEventListener(RichWebViewEvent.RECEIVED_MASSAGE_FROM_JS, onReceivedMessage);

private function onReceivedMessage(e:RichWebViewEvent):void
{
     var a:Array = e.param.split(",");
     var funcName:String = a.shift();		
     this[funcName].apply(null, a);			
}

For me, this was a more foolproof way of passing arguments from JS to AS3.

I'm amused that they say "MASSAGE" when I think they mean MESSAGE.  It's nice to think JS is capable of sending massages though.

:)

Anyway, the above is not complete code, but hopefully you get the idea.

**Comment by myflashlab** [comment]
Thanks for sharing @dommermuth user inputs will surely help us improve our ANEs in future versions. And thank you for noticing that miss-spelling. That was embarrassing :))

**Comment by dommermuth** [comment]
Ha!

Nothing to be embarrassed about.  The ANE is very helpful and appreciated.

Thank you.
