### ISSUE TITLE
Bridge.call() not working in callback

### ISSUE THREAD

**Issue by galaxybeing** [myflashlab/webView-ANE#37]
We have been able to use Bridge.call() successfully except in the callback function of a jQuery ajax call.  Any ideas why?

                        $.ajax({ 
                            type: 'POST', 
                            url: '/~bflportal/index.php/user/getSsotoken',
                            data: {'email': $.trim($("#username").val()), 'password': $.trim($("#pwd").val())},
                            dataType:'json',
                            success: function(response){
                                if (response['code'] == "1") {
                                    Bridge.call("ssotoken=" + response['ssotoken']);  // doesn’t work
                                } else {
                                    Bridge.call("login failed");  // doesn’t work
                                }
                            },

**Comment by myflashlab** [comment]
sorry but we are not JS or Ajax experts. can't be a help on that part.

**Comment by galaxybeing** [comment]
Well, perhaps you should.  For instance, do you realize that "call" is a reserved Javascript command to invoke a function in another scope?

Anyway this is the way to call the function from within an ajax callback:

Bridge.call.call(bridge,"ssotoken=lkjjljlkj");

"bridge" in this case is the scope of the object we want to run in.  Otherwise  bridge.OS in the call function will be undefined.

I"m not an expert in JS or Ajax either, but I"m not selling a piece of javascript along with my extension.   


Go here:
http://www.w3schools.com/jquery/tryit.asp?filename=tryjquery_ajax_ajax

and paste this in:

<!DOCTYPE html>
<html>
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>

function Bridge() {
  this.OS = "android";
}

var bridge = new Bridge();

bridge.OS = "ios";

Bridge.call = function($msg)
{
   alert(bridge.OS);
    alert($msg);
}

$(document).ready(function(){
    $("button").click(function(){
        $.ajax({url: "demo_test.txt", success: function(result){
            $("#div1").html(result);

          Bridge.call.call(bridge,"ssotoken=lkjjljlkj");
        }});
    });
});
</script>
</head>
<body>

<div id="div1"><h2>Let jQuery AJAX Change This Text</h2></div>

<button>Get External Content</button>

</body>
</html>

it works in this test page, but I haven't tested it on any mobile browsers yet. They may complain that you used "call" as a function.

**Comment by myflashlab** [comment]
I will note this down for the team to think of a better solution. maybe we should hire a JS guy :) The last time I checked with the PM guy, he said he's planing to remove the Bridge class altogether and possibly inject it dynamically so Air developers wouldn't have to do it themselves. we will keep you updated on the progress. thanks for the input.

**Comment by galaxybeing** [comment]
Even though that corrected the scope in the Bridge.call() function, on iOS I couldn't get it to send the data.  This was in a login page so it was just as it was loading the index page and I assumed it had something to do with that.  I wound up sending the date from the index page. Less desirable but it worked.  Also found that the call to set the os was coming too late so I had to set it myself.

**Comment by myflashlab** [comment]
with the release of V5.0 of RichWebview, we addressed this issue and now instead of using ```Bridge.call``` you can use ```AirBridge.evoke```

Please make sure to study the changelog and the demo codes carefully because we have also injected the Bridge JS file automatically so you don't have to insert it into your HTML content manually yourself.

If you have any questions, please open a new issue. 

Thanks.
https://twitter.com/myflashlab
