### ISSUE TITLE
Application Storage Directory support

### ISSUE THREAD

**Issue by sterlingwarrior** [myflashlab/webView-ANE#38]
I have tried to use both openWebViewLocal and openWebViewURL with and html file stored in the application storage directory.  I keep getting that the file does not exist.  Is there a way to use either of these will files stored in this directory?  If not, is it possible to support it?

**Comment by myflashlab** [comment]
with the current version, you should load your html content from documentsDirectory.

**Comment by myflashlab** [comment]
RichWebview V5 or greater will support this feature. please update yourself.
