### ISSUE TITLE
html input area keyboard issue

### ISSUE THREAD

**Issue by hesapyonetimi** [myflashlab/webView-ANE#4]
while trying to type a text in html input area that stays under the keyboard because of the positioning issue. so you cant see what you write. is there a way to solve this issue by ourselves or do we need to wait for the patch? this the screenshot: http://i.imgur.com/Zju9O9m.png

**Comment by myflashlab** [comment]
@hesapyonetimi I see your screenshot. well, this happens on any webView I think. you should think of a solution in your html code.
