### ISSUE TITLE
PDF support?

### ISSUE THREAD

**Issue by pdelia** [myflashlab/webView-ANE#40]
I am trying to open a PDF (in web or locally) but I can't see anything. Is this supported? And more specifically, can I use parameters like #page=xx like in a browser?

**Comment by myflashlab** [comment]
for displaying pdf in the best way in your app, you might consider opening it in Adobe acrobat app. http://www.myflashlab.com/product/pdf-reader-ane-adobe-air-native-extension/

**Comment by pdelia** [comment]
This is not an option I am afraid. Because of the app specs I have to display the pdf in a part of the screen. So from your answer I suppose PDF files are not handled at all by Richwebview?

**Comment by myflashlab** [comment]
Are you sure you have read the full description of our RichWebView ANE?! it is supported on both Android and iOS.

anyway, Although we have not tested the ANE by loading pdf files, but it seems to work ok on the iOS side according to http://stackoverflow.com/questions/2832245/iphone-can-we-open-pdf-file-using-uiwebview

on the Android side though, I think this page will show you the Android limitation. considering that the Android side of our ANE is based on the native Webview, this information should be valid http://stackoverflow.com/questions/2655972/how-can-i-display-a-pdf-document-into-a-webview

saying all that. we suggest you to download and run the ANE sample and test things for yourself. if it works the way you wish, then that's great, if it's not, you can always update this ticket so we can add the feature to our future to-do list. (use the FLashDevelop demo project to make sure it is uptodated. the FlashBuilder demo might be old)

**Comment by pdelia** [comment]
Hi again,

I was talking fot your link of PDF reader (which runs only on Android) not RichWebview.
I have tested the demo ANE in an iOS app but I could not see it (blank screen), this was my original post. I can send you my code to have a look if you like.

**Comment by myflashlab** [comment]
oops, I thought you're talking about the RichWebview. my mistake :) anyway. I am now totally confused when you say ```I could not see it (blank screen), this was my original post``` you can't see the webview view port? or the pdf?!

**Comment by pdelia** [comment]
I can't see the PDF. I tried an HTML page and works fine (even with anchors).

**Comment by myflashlab** [comment]
well, as I said, we had never tested to open a pdf using RichWebview. I will write this down now. thanks for your input @pdelia

**Comment by myflashlab** [comment]
for anyone interested, check this out in regard to this issue http://www.myflashlabs.com/how-to-open-parse-pdf-using-richwebview-ane/
