### ISSUE TITLE
locationChanging

### ISSUE THREAD

**Issue by galaxybeing** [myflashlab/webView-ANE#42]
stageWebView has a locationChanging event that allowed you to inspect the link location and change it if necessary.  For instance, if it is a .pdf, you could open it in Safari, and then cancel the rest of the event processing.  Is there any way to do this with webView?   Are you planning on implementing it?  I my case, my client has alread developed the website we are loading into webView, so it's going to be a pain to go in manually and change all the links they want to open in Safari.

**Comment by myflashlab** [comment]
@galaxybeing you're right, being able to preventDefault behavior for page navigations was one of the things that we hoped we can easily add to the ANE but we have not yet been able to find a way to make both native sides correctly dispatch the event to the flash side for the flash side to let it continue or prevent it...

saying that, we have already started investigating new ways of generating a similar behavior which may not look similar to StageWebView but will let devs to do the same things. Please get back for more news on when we are releasing the next version.
