### ISSUE TITLE
no communication between AIR iOS and Bridge JS

### ISSUE THREAD

**Issue by dommermuth** [myflashlab/webView-ANE#43]
Hello,  It seems that there is no communication the app and Bridge JS on iOS.

setFlashNative() never gets called.

This ANE is great on Android, but simply not working on iOS.

**Comment by dommermuth** [comment]
I am sending a var from the app to indicate to the site whether the device is iOS or Android.  With that I can ensure that Bridge.js works.  

setFlashNative() just never gets called from iOS.

**Comment by myflashlab** [comment]
setFlashNativeOS is called by the extension when the page is fully loaded. you don't have to call it at all. you should make sure your js files are correctly loaded.

**Comment by dommermuth** [comment]
Yes.  Everything is correctly loaded. I understood that it should automatically get called.  Of course, it's very difficult to debug without a console, but I put a JS alert within the setFlashNativeOS function and it simply never gets called. The result is, on iOS, that Bridge.js thinks the device is Android and uses NativeBridge.callFlash($msg) rather than window.location.  This result in a JS error.

I'm not sure why I've had so much difficulty getting this ANE to work on iOS. As you know, it's not just my project.  The original example you provide fails to work properly too and I've tested on several iOS devices in both Flash Develop and Flash Builder.

**Comment by myflashlab** [comment]
That's the beauty of being a programmer I guess! :) as you see in the issues, no one else has faced such weird problems that you experienced. I hope the rest of the project can go smooth and these documents would be a help to anyone else who might have a similar problem. anyhow, we are going to update our sample projects with the Latest version of FlashDevelop, CC and FB. cheers.

**Comment by dommermuth** [comment]
I did notice and it is peculiar.  I would expect that in time, someone else is likely to have an experience similar to mine. Maybe they'll be better able to identify the issue.  I would love an explanation.

In the mean time, I think time spent on functioning examples and clear documentation will ultimately serve your business well.

**Comment by myflashlab** [comment]
With the release of RichWebview V5.0 the bridge JS file will now be handled automatically from the native side and it will be automatically injected into your html pages so you don't have to insert it yourself. Please study the new demo files and read the changlog notices.

if you have a question or still a problem or anything, do feel free to open a new issue.

Thanks,
https://twitter.com/myflashlab

**Comment by myflashlab** [comment]
updated methods and workarounds here https://github.com/myflashlab/webView-ANE/issues/48
