### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by galaxybeing** [myflashlab/webView-ANE#45]
My client was complaining about the performance being slow so I dropped the fps to 4 from 30 when the browser was up.  That seemed to help quite a bit even though there was no animation or code running on enterframe.  It is expected to be slower than browsing the same site in mobile Safari, right?  Just because of the Air overhead.  Is there anything else that you can suggest to improve performance?

**Comment by myflashlab** [comment]
having the webview take the whole screen may help a bit more but it mainly depends on the Javascript running the page. if you can optimize the JS you will experience a better results I guess.
