### ISSUE TITLE
error in cc2015

### ISSUE THREAD

**Issue by bobsmo** [myflashlab/webView-ANE#46]
trying to get the example working  -  getting this error when using Flash cc2015

Scene 1, Layer 'Layer 1', Frame 1, Line 7, Column 35	1120: Access of undefined property C.

**Comment by bobsmo** [comment]
if I rem that line out I get another error   

ArgumentError: Error #3500: The extension context does not have a method with the name command.
	at flash.external::ExtensionContext/_call()
	at flash.external::ExtensionContext/call()
	at com.myflashlab.air.extensions.webView.android::Android/openWebViewURL()
	at com.myflashlab.air.extensions.webView::RichWebView/openWebViewURL()
	at richMap_fla::MainTimeline/frame1()[richMap_fla.MainTimeline::frame1:17]
	at runtime::ContentPlayer/loadInitialContent()
	at runtime::ContentPlayer/playRawContent()
	at runtime::ContentPlayer/playContent()
	at runtime::AppRunner/run()
	at ADLAppEntry/run()
	at global/runtime::ADLEntry()

**Comment by myflashlab** [comment]
Are you trying the ane on a simulator? If you do, please try running it on
a real device.

On Friday, January 8, 2016, bobsmo <notifications@github.com> wrote:

> if I rem that line out I get another error
>
> ArgumentError: Error #3500: The extension context does not have a method
> with the name command.
> at flash.external::ExtensionContext/_call()
> at flash.external::ExtensionContext/call()
> at com.myflashlab.air.extensions.webView.android::Android/openWebViewURL()
> at com.myflashlab.air.extensions.webView::RichWebView/openWebViewURL()
> at richMap_fla::MainTimeline/frame1()[richMap_fla.MainTimeline::frame1:17]
> at runtime::ContentPlayer/loadInitialContent()
> at runtime::ContentPlayer/playRawContent()
> at runtime::ContentPlayer/playContent()
> at runtime::AppRunner/run()
> at ADLAppEntry/run()
> at global/runtime::ADLEntry()
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/webView-ANE/issues/46#issuecomment-169811525>
> .
>


-- 
Sent from iPhone

**Comment by bobsmo** [comment]
Hi - Tried to publish it out of 2015CC but it hung up on error on line 7 and was unable to publish

if(_ex.os == RichWebView.ANDROID) C.log("Android SDK version: ", _ex.sdkVersion);

so i rem that line 7 and was able to publish.

But when viewing on my android phone it shows a blank screen  -  I'm trying to  display

_ex.openWebViewURL(0, 0, stage.stageWidth, stage.stageHeight, "http://www.google.com");

**Comment by myflashlab** [comment]
The C.log command is actually the debugger we're using in our
FlashDeveloper sample project, if you want to get read of missing errors,
you should either import the class or change it to the normal "trace"
method.

About the blank screen, well, first check if the "stage" is available when
you are calling it in the load url method?

Then also make sure your Air manifest .xml file is set correctly according
to the sample project?

On Friday, January 8, 2016, bobsmo <notifications@github.com> wrote:

> Hi - Tried to publish it out of 2015CC but it hung up on error on line 7
> and was unable to publish
>
> if(_ex.os == RichWebView.ANDROID) C.log("Android SDK version: ",
> _ex.sdkVersion);
>
> so i rem that line 7 and was able to publish.
>
> But when viewing on my android phone it shows a blank screen - I'm trying
> to display
>
> _ex.openWebViewURL(0, 0, stage.stageWidth, stage.stageHeight, "
> http://www.google.com");
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/webView-ANE/issues/46#issuecomment-169830791>
> .
>


-- 
Sent from iPhone

**Comment by bobsmo** [comment]
the example at https://github.com/myflashlab/webView-ANE
only shows a part of the xml manifest -  The part I added is 

<activity android:name="com.doitflash.webView.Pick" android:theme="@style/Theme.Transparent" />

but no change in the blank screen.

The other two suggestions - 
How do I go about checking if the stage is available ?

How would I go about turning  C.log to a trace method  (can I just // that?)

I went ahead and moved all the actionscript off of frame 1.  I got a different error in the simulator.  And same blank screen on a real device.

ArgumentError: Error #3500: The extension context does not have a method with the name command.
	at flash.external::ExtensionContext/_call()
	at flash.external::ExtensionContext/call()
	at com.myflashlab.air.extensions.webView.android::Android/openWebViewURL()
	at com.myflashlab.air.extensions.webView::RichWebView/openWebViewURL()
	at richMap_fla::MainTimeline/frame59()[richMap_fla.MainTimeline::frame59:17]

**Comment by myflashlab** [comment]
@bobsmo by reading your posts, we can guess that you are somehow new in Air programming and our job is not really to teach how devs should code AS3. not that we don't want to, it's just that we can't find the time for that. yet, we try to help you as much as we can. here are some hints to your questions but you can search online for exact solutions:

>  only shows a part of the xml manifest - The part I added is...

we have the full working sample project in the FD directory. here's the complete manifest .xml file for your reference: https://github.com/myflashlab/webView-ANE/blob/master/FD/application.xml

>  How do I go about checking if the stage is available?

How about a ```if``` clause?! ```if(stage){}```

>  How would I go about turning C.log to a trace method (can I just // that?)

C.log is an open sourced project which we are using in our demo projects just to visualize the trace methods! you can completly remove it in your own projects. https://github.com/junkbyte/flash-console

>  ArgumentError: Error #3500: The extension context does not have a method with the name command...

Bummer, This error shows that you have not correctly embedded the ANE in your project! check out the full manifest .xml file to see what you are missing. my quick guess is that you are missing the following lines:

```xml
  <extensions>
    <extensionID>com.myflashlab.air.extensions.webView</extensionID>
  </extensions>
```

Dear @bobsmo we'd be happy to arrange a TeamViewer or Skype call for a teaching session on these basic factors to Air developing. if you are interested, please contact us from http://www.myflashlabs.com/contact/

**Comment by bobsmo** [comment]
thanks for pointing out the FD folder.  When I bought this ANE the download zip did not have that folder.  From looking at the project it looks like a FLEX build.  When I install your "theApp.apk" it asks if I would like to install adobe Air on my device. 

I prefer to use Flash CC and Mobile Device Packaging . Which lets developers embed the air runtime.   If you are not using  Flash CC I'd be happy to troubleshoot this ANE with you. For example - I am able to attach both the ANE and the swc to my project.  Flash CC recognizes it and is able to generate an xml with  

<extensions>
    <extensionID>com.myflashlab.air.extensions.webView</extensionID>
  </extensions>

Let me know if you would like to develop with the Flash Pro CC and I'd be glad to troubleshoot your ANE.    It really does look like it might work for developers like me.  Since Goggle, Mapquest and Yahoo have all depreciated their map api for as3 -- yours is the only solution for us Flash Developers trying to use maps with GPS capabilities.   Thanks !

**Comment by myflashlab** [comment]
@bobsmo The commercial packages you download will hold the ANE only but you can always get the project samples from our github repository.

the FD folder is not actually a FLEX sample. it's a FlashDevelop sample and of course all our ANEs will work on Flash CC, FLashBuilder, FlashDevelop and mobile Flex projects. So, you are running Flash CC, that's great and the ANE is well supported on that.

Flash CC generates the manifest .xml file automatically for you. you need to stop that from your settings and instead edit the manifest manually.

>  When I install your "theApp.apk" it asks if I would like to install adobe Air on my device. 

Of course you can build in captive mode. we build a release mode so the package size users download will be smaller :)

>  Flash Developers trying to use maps with GPS capabilities.

Yes, using webview can be one option as right now, but we will soon build a Google Map ANE too. cheers.

**Comment by bobsmo** [comment]
Hey great - I got it to work on a real device - Note : The simulator will not display. You have to use a real device.

Here are the steps if you are using Flash CC Pro

-Download the ANE and get the example .xml file from https://github.com/myflashlab/webView-ANE/tree/master/FD

-Make sure you are using the latest SDK (Flash Pro CC will not automatically update to the beta SDK) - go here to download - http://www.adobe.com/devnet/air/air-sdk-download.html  - rename that folder to "AIR20" and drop it in you application folder "Adobe Flash CC 2015" - Add it in FlashCC  by >Help>Manage Air SDK  .  Choose the folder in File>publish settings>Target

create new Android app and use the actionscript at the example "AS3 API:" at https://github.com/myflashlab/webView-ANE

add the ANE in the File>Android Setting>General

also add them in the File>actionscript setting - using "Add SWC" "Add ANE" buttons.

Publish the project - Flash will create an .xml descriptor file.  Edit that file with a text editor and use the example at https://github.com/myflashlab/webView-ANE/tree/master/FD

Go back and recompile the .apk in Flash 2015 - but this time click the "manually manage permissions" box in the android settings>permissions   (so the new APK won't overwrite the .xml you just edited.)

works like a charm .

Looking forward to the Google Map ANE .  Thanks for the help.

**Comment by myflashlab** [comment]
Thanks for sharing @bobsmo
