### ISSUE TITLE
Error #3500: The extension context does not have a method with the name command.

### ISSUE THREAD

**Issue by PapaDeBeau** [myflashlab/webView-ANE#47]
Is it possible to debug/view the app on a desktop and not a device? I use the Flash CC 2015 IDE and I normally use this to test apps for speed, however, the RichWebView does not allow it as it is wanting it to use my Andriod device.

Here is the full error code:

ArgumentError: Error #3500: The extension context does not have a method with the name command.
        at flash.external::ExtensionContext/_call()
	at flash.external::ExtensionContext/call()
	at com.myflashlab.air.extensions.webView.android::Android()
	at com.myflashlab.air.extensions.webView::RichWebView()
	at com::RichWebViewClass()

And this line calls it: _ex = new RichWebView(this.stage, true,true,true,true); 

Thanks

**Comment by myflashlab** [comment]
Hi Ed,

For tech questions, please use the github issues page. Our dev team will be
there to help you faster.

Regards,
MyFlashLabs Team,
http://MyFlashLabs.com

On Wednesday, January 13, 2016, Ed <notifications@github.com> wrote:

> Is it possible to debug/view the app on a desktop and not a device? I use
> the Flash CC 2015 IDE and I normally use this to test apps for speed,
> however, the RichWebView does not allow it as it is wanting it to use my
> Andriod device
>
> Here is the full error code:
>
> ArgumentError: Error #3500: The extension context does not have a method
> with the name command
> at flashexternal::ExtensionContext/_call()
> at flashexternal::ExtensionContext/call()
> at commyflashlabairextensionswebViewandroid::Android()
> at commyflashlabairextensionswebView::RichWebView()
> at com::RichWebViewClass()
>
> And this line calls it: _ex = new RichWebView(thisstage,
> true,true,true,true);
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/webView-ANE/issues/47>.
>


-- 
Sent from iPhone

**Comment by PapaDeBeau** [comment]
Ok Thanks much! I wish there was a work around. It would be helpful. Let me know if anything comes up. Thanks again.

**Comment by PapaDeBeau** [comment]
I thought I did use the issues page. Where should I ask questions again? Do
you have a link?
Thanks

-Ed

**Comment by myflashlab** [comment]
That was a mistake email reply from our social manager, Neg :) she told me she had wrongly emailed you. you posted in the right page. please ignore that email.

**Comment by PapaDeBeau** [comment]
Ok, Thanks

I have another question regarding the scrolling speed that is lacking in my
app but not in your demo. I must be doing something wrong. Should I ask it
here or open a new question?
