### ISSUE TITLE
Sending vars in a function from website using JS to Actionscript?

### ISSUE THREAD

**Issue by PapaDeBeau** [myflashlab/webView-ANE#48]
I want to send vars from my webpage to actionscript. How can I do this? 

Here is what I am using but it's not working.

HTML
```
<a href="javascript:void(0);" onclick="AirBridge.evoke('toPlaySound('Hey there!','I am var 2')')" return false;>Send the vars! </a>
```

Actionscript:
```
public function toPlaySound(var1:String,var2:String)
		{
			trace("Does this work? " + var1 + " and " + var2 + "!");
			
		}
```

**Comment by PapaDeBeau** [comment]
I think I figured it out, or at least it seems to be working. I did this:

<a href="javascript:void(0);" onclick="AirBridge.evoke('toPlaySound(testing,And here I can put a string with spaces and it works!)')" return false;>Send the vars! </a>

But how do I add special characters in the string without breaking it... for example if put the following code it breaks because of the characters added. 

<a href="javascript:void(0);" onclick="AirBridge.evoke('toPlaySound(Yes,I won't break! Wait, yes I will!)')" return false;>Send the vars! </a>

**Comment by myflashlab** [comment]
you see, we have wrote a function in AS3 https://github.com/myflashlab/webView-ANE/blob/master/FD/src/com/doitflash/tools/DynamicFunc.as which parses a String into a function call. That's what we have used in the demo project as you have seen it.

yet, the best way to send data around, is maybe to encode the string using encodeURL standard on the JS side and then decode it on the Air side and besides that, for more complex data transfers, maybe you can even parse your data into a Json string first, then encode it in URL standards and then reverse it on the flash side.

**Comment by PapaDeBeau** [comment]
Right but how do I write the Javascript code in the html to call it?

**Comment by myflashlab** [comment]
let me explain this a bit more though.

first you set the listener to listen to when JS is trying to send a String to flash

```actionscript
_ex.addEventListener(RichWebViewEvent.RECEIVED_MASSAGE_FROM_JS, onReceivedMassage);

private function onReceivedMassage(e:RichWebViewEvent):void
{
	trace("onReceivedMassage: ", e.param);
	
	// optional use of DynamicFunc
	DynamicFunc.run(this, e.param);
}
```

when you receive the string from JS in ``e.param``` you may wish to use the DynamicFunc class to parse the string BUT you are not forced to use that class at all.

in simple words, you can setup your string first in JS side, (as suggested earlier, for complex data, you can create a json string in JS side and then encodeURL to make sure you are bypassing the special characters). As the sample shows, you can send data from js side like this ```"AirBridge.evoke('A STRING TO SEND TO AS3')"```

and then in the SA3 side, you can decode e.param and then parse the json to get all your initial data coming from the js side.

**Comment by myflashlab** [comment]
I should also add that if you can't send variables like 

```javascript
<scritpt>
var One = 'I am var one!';
var Two = 'I am var two!';
</script>
```

instead, use the json trick suggested in my other post.

**Comment by PapaDeBeau** [comment]
Ok, I think I got an idea. But I was hoping to use my custom function in as
like myCustomFunction (var1,var2,var3, etc..)

And from JS call it by ???

Airbridge.evoke('myCustomFunction(???)');

That's kind of what I was wondering. What JS can call a custom function and
send custom vars in that function. The example you showed only shows how to
send one string.

**Comment by PapaDeBeau** [comment]
Sorry to ask again. I am still waiting on a JS example on how to send a string with special characters.

For example how would I send this var to AS from JS?

<scritpt>
var One = 'This is totally awesome!';
var Two = 'I can\'t, simply can\'t believe this! ';
</script>

I have this in my AS and it's working.... It calls the custom function. I just need to know how to send custom vars through it from the JS side. Can you give me one one line code example? 

Again my AS has this:
_ex.addEventListener(RichWebViewEvent.RECEIVED_MASSAGE_FROM_JS, onReceivedMassage);

private function onReceivedMassage(e:RichWebViewEvent):void
{
    trace("onReceivedMassage: ", e.param);

    // optional use of DynamicFunc
    DynamicFunc.run(this, e.param);
}

and this:

public function toPlaySound(var1:String,var2:String)
		{
			trace("Who do you love the most? " + var1 + " and " + var2 + "!");
			
		}

and it works BUT... it is only passing strings without special characters. For example THIS WORKS in my code:
<a href="javascript:void(0);" onclick="AirBridge.evoke('toPlaySound('Hey there!','I am var 2')')" return false;>Send the vars! </a>

but THIS DOES NOT... 
<a href="javascript:void(0);" onclick="AirBridge.evoke('toPlaySound('C','I am var 2')')" return false;>Send the vars! </a>

or IF... I send an object, how do I send it from JS. That is what I am struggling with. Thanks

**Comment by PapaDeBeau** [comment]
As you can see I have been working VERY hard to get this answered... to no avail.

http://stackoverflow.com/questions/34813188/javascript-var-into-onclick-in-html/34813263?noredirect=1#comment57368932_34813263

**Comment by myflashlab** [comment]
@PapaDeBeau here's a working sample code from the solution I suggested earlier.

in your JS, create a button or link to call a JS function
```html
<button type="button" onClick="sendComplexDataToAir()">Send Complex Data To Air</button>
```

in your js code, create your Json and send it back to Air like this:
```javascript
function sendComplexDataToAir()
{
	var myJSONObject = 
	{
		"someData": 
		[
			{"var1": "value 1"},
			{"var2": "value 2"},
			{"var3": "value 3"},
			{"var3": "As long as you have a valid Json in JS, you can have it received on the Air side with no problem!"}
		]
	};
	
	// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify
	AirBridge.evoke(JSON.stringify(myJSONObject));
}
```

finally on the AS side, get the data and decodeURI it
```actionscript
private function onReceivedMassage(e:RichWebViewEvent):void
{
	trace(decodeURI(e.param));
}
```

**Comment by myflashlab** [comment]
and even to make it more friendly so you can even use the DynamicFunc class to directly run a function on the Air side, you make encode your JS json like this:

```javascript
function sendComplexDataToAir()
{
	var myJSONObject = 
	{
		"someData": 
		[
			{"var1": "value 1"},
			{"var2": "value 2"},
			{"var3": "value 3"},
			{"var3": "As long as you have a valid Json in JS, you can have it received on the Air side with no problem!"}
		]
	};
	
	// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify	
	var jsonStr = JSON.stringify(myJSONObject);
	
	// http://www.w3schools.com/jsref/jsref_encodeURI.asp
	var encodedStr = encodeURIComponent(jsonStr);
	
	// and finally send it to flash
	AirBridge.evoke('parseJson('+ encodedStr +')');
}
```
then, receive it on the Air side like this
```actionscript
private function onReceivedMassage(e:RichWebViewEvent):void
{
	DynamicFunc.run(this, e.param);
}

public function parseJson($str:String):void
{
	trace(decodeURIComponent($str));
}
```

**Comment by PapaDeBeau** [comment]
Thank you so much for all your help. I got it to work but found, still one issue.

Issue: If I use an apostrophe '
or if I use a dash - 
in my JS then I get this error: Error #1063: Argument count mismatch on com::RichWebViewClass/getAudioInfo(). Expected 1, got 2.

Example JS line: {"Title": "Let's change this up a little"} /// will break
or {"audioImage": "my-photo.jpg"} // will break

Your code works to send all the vars but seems to break with special characters. This seems to be a JS encoding issue and how would I fix this? Again thanks for all your great help. 

If you need me to post all the code like you did I can. But I think you get the idea of what may be happening.

**Comment by myflashlab** [comment]
@PapaDeBeau my best advice for you is NOT to use the DynamicFunc class for complex data transfers like this example. that is, to use the first sample sample I provided above.

DynamicFunc is just a temporary helper class which we are planning to work on it and make it a robust String parser class in future versions of the RichWebview ANE but as right now, you should use the actual string which is coming from JS directly if you are transferring complex Json strings.

but yet, if you insist on using the DynamicFunc class, you can make it support ```-``` or ```'``` or anything else, by modifying the regExp variables.

change ```STRING_PATTERN``` on line 47 to: (notice that I have added ```'``` and ```-```)
```actionscript
public static const STRING_PATTERN:RegExp = /[\w_!:.@\$\?%\s\/\(\)'-]+/g;
```

and also change ```valuePattern``` on line 146 to: (notice that I have added ```'``` and ```-```)
```actionscript
var valuePattern:RegExp = /\[?\{?((([\w_!.@\$\?%]+):?([\w_!.@\$\?%\s\/'-]+)?),?\s?)+\}?\]?/g;
```

**Comment by PapaDeBeau** [comment]
It worled! Thanks for your great support. It was enough for me to become a yearly member! :) I am excited.
