### ISSUE TITLE
BUG: Can't send apostrophe in JSON custom function. 

### ISSUE THREAD

**Issue by PapaDeBeau** [myflashlab/webView-ANE#49]
There is no way to send special characters in the string in JS.

```
<a href="javascript:void(0);" onclick="AirBridge.evoke('myCustomFunction(One,{var1: This can be sent!,Two: you can't send an apostrophe})')" return false;>Call my function in AS</a>
```

More on this here:
https://github.com/myflashlab/webView-ANE/issues/48#issuecomment-171583475

Issue on Stack:
http://stackoverflow.com/questions/34813188/javascript-var-into-onclick-in-html/34813263?noredirect=1#comment57368932_34813263

**Comment by myflashlab** [comment]
explained in details with sample code here so, I'm closing this one. if you have more question, please continue on the main thread. Thanks. https://github.com/myflashlab/webView-ANE/issues/48
