### ISSUE TITLE
drawViewPortToBitmapData not supported

### ISSUE THREAD

**Issue by MortimerNeuss** [myflashlab/webView-ANE#5]
Can you please expose the native drawViewPortToBitmapData functionality as well?

Mortimer

**Comment by myflashlab** [comment]
Yes, the Android side of bitmap export is ready and we are working on the
ios side. We will release a new version soon.

On Wednesday, July 15, 2015, Mortimer Neuß <notifications@github.com> wrote:

> Can you please expose the native drawViewPortToBitmapData functionality as
> well?
>
> Mortimer
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/webView-ANE/issues/5>.
>


-- 
Sent from iPhone

**Comment by MortimerNeuss** [comment]
Soon like days or soon like weeks?

Also, does your ANE works with Angular? The routing in Angular workes on the #anchor in the URL (test.com/#location-to-go) and not the paramter pattern (test.com/?var=0). Is the ANE still able to make JS->AS3 calls with strings passed?

**Comment by myflashlab** [comment]
Soon like days :) we are doing the final touches...

**Comment by MortimerNeuss** [comment]
That is good to hear. I coded my StageWebView Service class in a fashion to hot swap in case your ANE will come out soon. I assume it will be also available as a demo from this git repo too, to see how it performs, yes?

**Comment by myflashlab** [comment]
V2.0 now supports Bitmap screenshots.
