### ISSUE TITLE
Android video not playing correctly 

### ISSUE THREAD

**Issue by galaxybeing** [myflashlab/webView-ANE#50]
We have tested in ios and everything is ok.  Under Android, the embedded videos display black where the video should be and we only hear the sound.

**Comment by myflashlab** [comment]
yes, unfortunately HTML5 videos used in native webview on Android are crazy and behave differently on different Android versions. for the best practice to know how to workout videos on a webview Android, your best shot would be to search in Android forums as it's not something to be controlled via the RichWebview.

**Comment by galaxybeing** [comment]
These are Vimeo videos and they play fine in the default android browser.  I don't see what I can do to change anything.  I thought the webview components (yours and Adobe's) just take the default browser and inserts it into a component that can be placed in a mobile Air app.

**Comment by myflashlab** [comment]
After some googling, it seems like even native android devs are also having
trouble playing vimeo videos in their webview. Please send me a sample html
code you are using to embed a vimeo video and we'll investigate this more.
Thanks.

On Sunday, January 17, 2016, galaxybeing <notifications@github.com> wrote:

> These are Vimeo videos and they play fine in the default android browser.
> I don't see what I can do to change anything. I thought the webview
> components (yours and Adobe's) just take the default browser and inserts it
> into a component that can be placed in a mobile Air app.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/webView-ANE/issues/50#issuecomment-172359013>
> .
>


-- 
Sent from iPhone

**Comment by galaxybeing** [comment]
Can you give me an email address?   Then I can send you more and the log in credentials.

**Comment by myflashlab** [comment]
please contact us through myflashlabs.com and link to this page while you are sending the information. Thanks.

**Comment by Adrian-S** [comment]
Same problem, and after panicking all day, I realized it was all related to hardware acceleration not set in my manifest.

<activity android:hardwareAccelerated="true">
    <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
    </intent-filter>
</activity>

I only have version 4.0. And this is the only place I've added this attribute. Check your XML agains the one in this build found here: FD/application.xml

You will find one more reference to this attribute, but apparently this was the first one I've tried and it worked. No actual idea what all the attributes do... we just copy paste and pray it works.

Btw, nice job closing the issue without a solution. I didn't even think to look in my own backyard, after I saw this issue.

**Comment by galaxybeing** [comment]
Are you saying that will fix the vimeo videos?  I tried adding that but I still only get audio. I already had the activity and filter and just added the hardwareAcceleration="true"

**Comment by Adrian-S** [comment]
I did not test with vimeo videos, my problem was with all videos even the basic html5 video example from [w3schools](http://www.w3schools.com/tags/tag_video.asp). After adding the `hardwareAcceleration="true"` it worked fine. There is one more mention for this attribute here `<application android:hardwareAccelerated="true" android:allowBackup="true">` check the application.xml provided. Maybe you missed something.

One more thing you can do to test if it from you or not it to test against multiple urls. I've made a simple html from the w3schools example and tested with that. I have a local web server and was able to edit the html easy. You could do the same and add links to pages you want to test with. Test agains youtube and maybe videojs.com or any other more complex video player.

And if it helps, my app is set to:
```
    <renderMode>direct</renderMode>
    <depthAndStencil>true</depthAndStencil>
```

**Comment by myflashlab** [comment]
@galaxybeing actually what @Adrian-S suggested about setting ```android:hardwareAccelerated="true"``` is true for general video playback in webview. but playing iFrame videos like YouTube or Vimeo is a different story.

We did some tests and the result is the attached ANE. please use this ANE in your project and see if it plays fine now? That would be also great if you can do a iFrame test on a YouTube video to see if that also works?

we tested on this code
```html
		<iframe width="500" height="281" frameborder="0" allowfullscreen="" mozallowfullscreen="" webkitallowfullscreen="" src="https://player.vimeo.com/video/145693395">
		<!DOCTYPE html>
		<html lang="en">
		<head>
		<body>
		<div id="player" class="player player-1453471932204 js-player-fullscreen">
		<script src="https://f.vimeocdn.com/p/2.11.5/js/player.js">
		<script async="" src="https://ssl.google-analytics.com/ga.js">
		<script async="" src="https://f.vimeocdn.com/js_opt/modules/utils/vuid.min.js">
		<script>
		<iframe hidden="" src="https://f.vimeocdn.com/p/2.11.5/proxy.html" title="Vimeo LocalStorage Proxy" aria-hidden="true">
		</body>
		</html>
		</iframe>
```

here's the test ANE
[iFrameTestANE.zip](https://github.com/myflashlab/webView-ANE/files/100950/iFrameTestANE.zip)

**Comment by galaxybeing** [comment]
So I removed the old ane and added this new one.  Then every reference in my code could not find it, starting with the imports.  I ran "clean" but no dice.
	import com.doitflash.air.extensions.webView.MyWebView;
	import com.doitflash.air.extensions.webView.MyWebViewEvent;

So I removed it and put back the old one and all the references are fine now.  Any ideas?

**Comment by myflashlab** [comment]
You're using a very old version! Please check the sample codes from github
and update yourself with the new version first.

On Saturday, January 23, 2016, galaxybeing <notifications@github.com> wrote:

> So I removed the old ane and added this new one. Then every reference in
> my code could not find it, starting with the imports. I ran "clean" but no
> dice.
> import com.doitflash.air.extensions.webView.MyWebView;
> import com.doitflash.air.extensions.webView.MyWebViewEvent;
>
> So I removed it and put back the old one and all the references are fine
> now. Any ideas?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/webView-ANE/issues/50#issuecomment-174037941>
> .
>


-- 
Sent from iPhone

**Comment by galaxybeing** [comment]
I'm not sure what you mean.  I'm having problems with the version you just sent me in the iFrameTestANE.zip file.  That is a late a version as possible, no?

**Comment by galaxybeing** [comment]
I see what you mean.   Well we purchased it just before you made the change to myflashlab.  So how do I get the released version of the new ane? (I had my client purchase it, so I guess he would have gotten an email with a new link?

**Comment by galaxybeing** [comment]
Hey it's working with vimeo!  Thanks.  Now I just have to get the paid version.  How do I do that?

**Comment by myflashlab** [comment]
For the sake of this test, please use the current FrameTestANE.zip ane
version i sent you (only this version is addressing the iFrame video
problem) and to see how to embed it in your project, download the sample
codes from our github repository. Considering that you have been using a
very old version in your project you should expect a lot of changes. Maybe
the biggest change is about the JS auto injection thing. So please take
your time and use the sample files with the ANE version i sent here and you
will find vimeo working on the Android side too. Our Android team told me
they will need some time before they can release a newer version with
vimeo/YouTube bug thing fixed. But they also told me they can provide you
with a temp ANE including the fix so you won't be troubled in your project.
So, go ahead with the upgrade.

On Saturday, January 23, 2016, galaxybeing <notifications@github.com> wrote:

> I see what you mean. Well we purchased it just before you made the change
> to myflashlab. So how do I get the released version of the new ane? (I had
> my client purchase it, so I guess he would have gotten an email with a new
> link?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/webView-ANE/issues/50#issuecomment-174069044>
> .
>


-- 
Sent from iPhone

**Comment by myflashlab** [comment]
Cool. That's what we expected. Could you please confirm if it works with
YouTube also?

On Saturday, January 23, 2016, galaxybeing <notifications@github.com> wrote:

> Hey it's working with vimeo! Thanks. Now I just have to get the paid
> version. How do I do that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/webView-ANE/issues/50#issuecomment-174070852>
> .
>


-- 
Sent from iPhone

**Comment by galaxybeing** [comment]
OK, I'll test it with loading a youtube page.  But all the comm between the javascript and my app is not working anymore.

**Comment by myflashlab** [comment]
As I said before, you need to upgrade your code to the latest changes in
V5.1 and the js/air communications will be fixed again.

On Saturday, January 23, 2016, galaxybeing <notifications@github.com> wrote:

> OK, I'll test it with loading a youtube page. But all the comm between the
> javascript and my app is not working anymore.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/webView-ANE/issues/50#issuecomment-174071746>
> .
>


-- 
Sent from iPhone

**Comment by galaxybeing** [comment]
IT was a nightmare getting my client to insert all this bridge code into their php pages.  Now I have to have them take it all out and redo it. Not looking forward to it.  There was also a case where your test for IOS or Android didn't work so I had to write my own to get the bridge code to work correctly.  Hopefully that's fixed.

**Comment by galaxybeing** [comment]
Ug.  The other bad thing is that we just released the iOS version with the old ane, so my client's code is all modified to used the bridge code.  I can't change their code to use the new ane without breaking the released iOS version.  This just really complicates things.

**Comment by myflashlab** [comment]
I'm not sure what you are expecting us to answer right now but we are constantly moving forward to make this webview ANE better and better each day. I think you should consider upgrading!

**Comment by galaxybeing** [comment]
I'll respond through your private messaging system.

**Comment by galaxybeing** [comment]
I've been testing with both the 5.1 version and the beta version and there is no code injection happening.  The Bridge.call() JavaScript code is working with these versions, but the AirBridge.evoke() is not.  When I Alert(AirBridge) I get nothing.  Does the code injection check for the existence of Bridge and then not do the injection?

**Comment by myflashlab** [comment]
Please refer to this post https://github.com/myflashlab/webView-ANE/issues/55#issuecomment-179024496

**Comment by myflashlab** [comment]
Embedded videos will now work on Android also.

**Comment by galaxybeing** [comment]
As I tested to see if the device would stay awake through the whole video, which it does on Android (Galaxy S 6), I noticed some other issues.  The progress bar never appears on the bottom of the video.  We just get a Play button in the center.  When you touch that, it looks like the video loads, but doesn't actually play and the center button turns into a pause button.  Touching that turns it into a play button.  Touching that plays the video and turns the center button to a pause button. But it never turns off.  Hitting is once to pause the video, then again to play the video will then cause it to automatically fade out.  It takes 5 times of hitting the button in the center to get the video to play and the button to hide.

Android:
![android video pause btn](https://cloud.githubusercontent.com/assets/12906083/13029826/826e7722-d25c-11e5-87b7-ff5134cdafab.png)

iOS:

![ipad video](https://cloud.githubusercontent.com/assets/12906083/13029840/0906f462-d25d-11e5-8e64-e3e29ef758ae.PNG)

**Comment by galaxybeing** [comment]
I just tested the same video on the Galaxy s6 in the Chrome browser.

It loads similar to the iPhone, with the large play button in the middle and the TRT in the lower left corner.  When you hit play, it opens in a full screen player.  You can turn it landscape and make it full screen.  Hit the hardware back and it goes back to playing within the page, but still has the pause button on top.  Can't get it to play in the page without the pause button on top.  Here's the screen shots.

(starting off it would be a play button in the center.  After returning from the full screen player it changes to a pause button that won't go away.  But hit that twice and you get back to the FS player).
![screenshot_2016-02-13-16-47-53](https://cloud.githubusercontent.com/assets/12906083/13030559/7f2edbd4-d274-11e5-9d7f-18281168d2dc.png)

The full screen player
![screenshot_2016-02-13-16-52-05](https://cloud.githubusercontent.com/assets/12906083/13030564/b3220628-d274-11e5-850b-84c6d070f75f.png)

The full screen player turned landscape. (our app doesn't allow this, but I might have to if it worked.)
![screenshot_2016-02-13-16-50-53](https://cloud.githubusercontent.com/assets/12906083/13030565/c89daee4-d274-11e5-8e63-a1e1be83fb85.png)

Full screen player in FS mode
![screenshot_2016-02-13-16-46-31](https://cloud.githubusercontent.com/assets/12906083/13030569/fd0da3f0-d274-11e5-95a0-0ab02a62e9a2.png)

**Comment by bobsmo** [comment]
> Same problem, and after panicking all day, I realized it was all related to hardware acceleration not set in my manifest.
> 
> <activity android:hardwareAccelerated="true">
>     <intent-filter>
>         <action android:name="android.intent.action.MAIN"/>
>         <category android:name="android.intent.category.LAUNCHER"/>
>     </intent-filter>
> </activity>
> I only have version 4.0. And this is the only place I've added this attribute. Check your XML agains the one in this build found here: [FD/application.xml](https://github.com/myflashlab/webView-ANE/blob/master/FD/application.xml)
> 
> You will find one more reference to this attribute, but apparently this was the first one I've tried and it worked. No actual idea what all the attributes do... we just copy paste and pray it works.
> 

an update - I tried using this in my manifest - but ran into some probs --- I found the solution to run my .m4v video -  Iused this in my manifest

<manifestAdditions><![CDATA[<manifest><uses-permission android:name="android.permission.INTERNET"/><uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/><uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/><uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
       <application android:enabled="true">
                    <activity android:hardwareAccelerated="true">
    					<intent-filter>
        					<action android:name="android.intent.action.MAIN"/>
        					<category android:name="android.intent.category.LAUNCHER"/>
    					</intent-filter>
					</activity>
                  </application>
       </manifest>]]></manifestAdditions>
