### ISSUE TITLE
Use with Flash Professional?

### ISSUE THREAD

**Issue by galaxybeing** [myflashlab/webView-ANE#51]
I'm trying to use your webView ane with Flash Professional but when I try to debug on the device it reports that it can't find the references.

1172: Definition com.myflashlab.air.extensions.webView:RichWebView could not be found.
1172: Definition com.myflashlab.air.extensions.webView:RichWebViewEvent could not be found.

I've added it the normal way through the AS settings and tried both FP CS6 and FP CC.

**Comment by PapaDeBeau** [comment]
Hi, my name is Ed. I am not with myflashlab. I found them by chance and just started using their products. I use Flash CC as well for mobile development. 

Not sure if this will help you but I had some issue with the ANE too like you but I resolved them. I am sending a few screenshots to show you what I did. My guess is that you are not linking the ANE correctly - -  or - -  there is an issue with you path in the import. 

Here is a little video walk through of how to do it. Make sure you ANE is in the project folder and link to it this way in this video.

http://screencast.com/t/Imwkqsnk7LW0

I also called the RichWebEvent from a class in the com so I linked that correctly as well. May sure you copy and put the “myflashlab” folder in the com folder of your current project. 

Finally you will need to TEST on an Android Device. This ANE does not allow you to test in the Flash IDE. You must choose
Debug
Debug Movie
On Device via USB
Choose your device etc….

I hope this helps.  It’s nice to know another Flash Mobile developer. 


Good luck.
-Ed

P.S. In case you want to see some of the apps I developed using the Flash IDE and AS3 checkou this link: https://play.google.com/store/apps/details?id=air.WhisperingLight&hl=en

**Comment by myflashlab** [comment]
Thanks for the cooment @PapaDeBeau but I also should add that please make sure to upgrade to the latest version of the ANE. the reason is explained in details here: http://www.myflashlabs.com/urgent-fix-on-our-anes-required-for-air-sdk-v20-or-higher/

**Comment by galaxybeing** [comment]
Thanks Ed.  I've used ANEs with Flash Pro before and have never had this problem.  Plus i don't have the html files that your folder path leads to.  com.myflashlab.air.extensions.webView  
That path is usually embedded in the ANE somehow.  Where did you get the htmls files and if Flash is reading them shouldn't they be .as files?

**Comment by myflashlab** [comment]
@galaxybeing Please update this ticket if your problem is solved?

**Comment by galaxybeing** [comment]
I was not able to get the ANE to work with Flash Pro, but circumstances changed and I no longer need to for now.

**Comment by myflashlab** [comment]
We will soon upload Episode 3 of these videos explaining how ANEs are added into Flash CC. keep checking back https://www.youtube.com/watch?v=Oubsb_3F3ec&list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O

**Comment by mc3dev** [comment]
Hi, I am using the demo version ANE and run into the same problem with getting the RichWebView ANE to work in Flash Pro (Now Animate CC). I used AIR 20.0 for Android on Animate and AIR 17.0 for Android for Flash Pro CC 2015, none of them work. When will the Episode 3 be released? I cannot find it on Youtube. 

I really want to get this to work. Can you please advise? Thank you much.
