### ISSUE TITLE
Location of local web page for webview 

### ISSUE THREAD

**Issue by aggreymarsh** [myflashlab/webView-ANE#52]
I have gotten the  an online web page to load in my Flash Builder project but i dont know where is the flash builder project  should i put the html file . I tried it in the root but i was not successful.

aggrey

**Comment by myflashlab** [comment]
take this as an example:
```actionscript
_ex.openWebViewLocal(0, 0, stage.stageWidth, stage.stageHeight, File.documentsDirectory.resolvePath("webview/index.html")); // OR from File.applicationStorageDirectory
```

for as long as your file.exists() is true then it means you have set the path to your html file correctly. it must be in ```documentsDirectory``` or ```applicationStorageDirectory```

**Comment by myflashlab** [comment]
Let me know if there's anything else we can help you with? or we should close this ticket as resolved?

**Comment by aggreymarsh** [comment]
Yes the local web page view for me is not working .

I not sure where to put the local web page . I put it in the second and in
the root of the project folder but still no progress .


Aggrey

On Saturday, January 30, 2016, myflashlab <notifications@github.com> wrote:

> Let me know if there's anything else we can help you with? or we should
> close this ticket as resolved?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/webView-ANE/issues/52#issuecomment-177123557>
> .
>


-- 
Aggrey Marsh

1868-3205991

Aggreymarsh@gmail.com

**Comment by myflashlab** [comment]
As described in the comments and documentations, you have to put your local html content in ```File.documentsDirectory``` or ```File.applicationStorageDirectory``` other places won't work. 

my guess is that you are trying to load your local content from ```File.applicationDirectory```? that won't work.

**Comment by aggreymarsh** [comment]
where would i find the File.documentsDirectory ... in a flash builder
project


aggrey

On Sat, Jan 30, 2016 at 7:57 AM, myflashlab <notifications@github.com>
wrote:

> As described in the comments and documentations, you have to put your
> local html content in File.documentsDirectory or
> File.applicationStorageDirectory other places won't work.
>
> my guess is that you are trying to load your local content from
> File.applicationDirectory? that won't work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/webView-ANE/issues/52#issuecomment-177162006>
> .
>



-- 

Aggrey D. Marsh

Phone :18683205991

skypeid :aggreymarsh

7 Scott Street St Augustine,

Trinidad  W.I

The information contained in this email is confidential and intended only
for the addressee. If you are not the intended recipient (or have received
this e-mail in error), please notify the sender immediately and destroy
this e-mail. Any unauthorized copying, disclosure or distribution of the
material in this e-mail is strictly forbidden.

**Comment by myflashlab** [comment]
http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/filesystem/File.html
http://help.adobe.com/en_US/as3/dev/WS5b3ccc516d4fbf351e63e3d118666ade46-7fe4.html
https://www.google.com/search?q=%22File.documentsDirectory%22&ie=utf-8&oe=utf-8
