### ISSUE TITLE
Error #3500: The extension context does not have a method with the name command.

### ISSUE THREAD

**Issue by dani2003** [myflashlab/webView-ANE#54]
import com.myflashlab.air.extensions.webView.RichWebView;
import com.myflashlab.air.extensions.webView.RichWebViewEvent;
import flash.filesystem.File;
trace (RichWebView.VERSION) // result 5.1
trace (this.stage)	 //result [object Stage]
var _ex:RichWebView;
 RichWebView.clubId = "paypal-address-you-used-to-join-the-club"; 
_ex = new RichWebView(this.stage, false, false, false, false);
_ex.addEventListener(RichWebViewEvent.BACK_CLICKED, onBackClicked);
_ex.addEventListener(RichWebViewEvent.PAGE_STARTED, onPageStarted);
_ex.addEventListener(RichWebViewEvent.PAGE_PROGRESS, onPageProgress);
_ex.addEventListener(RichWebViewEvent.PAGE_FINISHED, onPageFinished);
_ex.addEventListener(RichWebViewEvent.RECEIVED_MASSAGE_FROM_JS, onReceivedMassage);
_ex.addEventListener(RichWebViewEvent.RECEIVED_SSL_ERROR, onReceivedError);
....
....
I use Flash cc 2014 .
Rich WebView.VERSION -  returns 5.1 then import the extension is correct.
How can I fix!

**Comment by myflashlab** [comment]
this is the most common question and the answer is very simply. it's either you have forgotten to add the the extension id into your manifest .xml file or you are trying to run on a simulator.

watch these videos and you'll find the detailed answer https://www.youtube.com/watch?v=Oubsb_3F3ec&list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O

FYI: we have not yet uploaded the video screencasting in FlashCC but yet, if yoy watch the current videos, you'll find the answer.

**Comment by myflashlab** [comment]
Let me know if there's anything else we can help you with? or we should close this ticket as resolved?
