### ISSUE TITLE
onReceivedMassage spelling error

### ISSUE THREAD

**Issue by galaxybeing** [myflashlab/webView-ANE#56]
The following events and function names are misspelled.  

RichWebViewEvent.RECEIVED_MASSAGE_FROM_JS
private function onReceivedMassage(e:RichWebViewEvent):void

Massage definition" "the rubbing and kneading of muscles and joints of the body with the hands, especially to relieve tension or pain."  It should be onReceivedMessage / RECEIVED_MESSAGE_FROM_JS

I would recommend leaving the existing for backward compatibility and creating new event and function names with the correct spelling.

**Comment by myflashlab** [comment]
That was embarrassing! :D Thanks for reporting it. will have it fixed in the next release.

**Comment by myflashlab** [comment]
is fixed in V6.0.0
