### ISSUE TITLE
Test if running within the WebView ANE

### ISSUE THREAD

**Issue by galaxybeing** [myflashlab/webView-ANE#57]
We need a way to test if the js code is running in the WebView ane or not.  If not, we send them to a page that directs them to download the app.

We need to test it here:

$(document).ready(function() {
    if (running in webView or app) document.location.href = '/~bflportal/download-splash/';
}

Now I"m sure I could come up with a scheme to send a message to the app and have it return something, and if nothing comes back in x milliseconds assume we are not in the app.  But that seems messy.   it would be great if there was something we could test for.  Is there an object or variable we can test for that will work on both platforms?

**Comment by myflashlab** [comment]
Well, if your JS is running in a platform where the ANE is not present, for example in mobile Safari or chrome browser, then this is your JS code which must decide and find about this.

you can set a timeout and then check if ```airBridge.OS``` is available or not. if it's not, it would mean that the injection has not happen which means that the user is not viewing the page using the RichWebview.

**Comment by galaxybeing** [comment]
from #55 
"the AirBridge.js is here https://github.com/myflashlab/webView-ANE/tree/master/FD/bin
what is important to be remembered is that it must be at the root of the assets folder which means, just next to the main .swf file."

So it has to be packaged into the app.  I need a solution for the apps already released and sitting on people's devices, which I don't think is possible.  I don't know how this situation came about.  We tested on our ipads and everything was fine.  But now we get reviews from people (one star of course)  saying that they are getting sent to the "you need to download the app" page and of course they click on the button for the apple store, download it again, get the same page, an on, and on.  I don't know why it was working in the first place.  But we overlooked this and I guess it is my fault.

**Comment by myflashlab** [comment]
@galaxybeing I'm not sure which version of the ANE you have used for releasing your app, but as you correctly mentioned previously, the js file is not something essential and can be placed inside your own html content.

What I suggested in my last message is concerning a situation when you are NOT adding the AirBridge.js manually into your pages. And it will be presented only with the injection method. In that situation, when ```airBridge.OS``` is available, it means your user is seeing your page from within your app.

**Comment by galaxybeing** [comment]
The problem with testing for airBridge.OS is that if it is nothing (null, not sure what it is in JS), JS craps out and stops executing.  I suppose I could create an airBridge and set the variable OS to "" and check for it being set or not.  Then if it gets injected, those will get overwritten.

**Comment by galaxybeing** [comment]
Nope.  Tried setting this up.

		function AirBridge()
		{
			this.OS = "none"; // set default value.
		}
		var airBridge = new AirBridge();

Now if I do a test

if (airBridge.OS != "none") {
	alert("// running in the app.  Do nothing.");
} else {
      // display download app page
}

It doesn't break javascript, but the injection does nothing.  Not sure how that works.  If it is doing the injection, there would be 2 of airBridge, and I think it will always reference the first one?  

I"m surprised this never came up while developing the ANE.  Can't you insert something into navigator.userAgent ?

**Comment by myflashlab** [comment]
We will investigate this and update you. thanks.

**Comment by galaxybeing** [comment]
I stayed up all night but I figured it out.

if (typeof airBridge !== 'undefined') {
	// running in the app.  Do nothing.
	//alert("// running in the app.  Do nothing.");
} else {
         // not running in app, display download app page
	document.location.href = '<?php echo Yii::app()->request->baseUrl; ?>/splash/';
}

With Javascript, typeof won't break the code.  Unlike AS3 where you can just use if (airBridge).  I mean, it could work that way if the gods wanted it to. I can't believe Javascript is the future.  Every time I go look something up I just find people arguing about how to do things with no definite answer. Its a language that's been hacked together for way too long.  What's the best way to define a class?  Wait, please don't answer that. ;)   Close it down.

**Comment by galaxybeing** [comment]
If you could add something to userAgent and it was easy to do that would be cleaner.  I found I had to used at least 1000 milisecond timeout to wait for the injection and I haven't tested on slower devices or devices slowed by lots of background stuff going on.  It has to be high enough to cover the worst case.  I guess it would be save to have it be 5 seconds.  The user might see the login page for a second or two before getting thrown to the download page, but that's not so bad.

**Comment by galaxybeing** [comment]
I have come up with cleaner solution than the one I previously posted. Set a global variable runningInApp to false, then when the app gets the event that the page has finished loading call a function that sets it to true.  Then when the timeout you started in document.ready fires, it can check that variable  and decide what it needs to do.  No dealing with injection or bridge code at all.

var splashTimeout = 0;
var runningInApp = false;

function appFinishedLoadingPage() {
	// called from the app after the page is loaded
	runningInApp = true;
}

function displayDownloadAppPage() {
	// called after load timer has run out

	if (!runningInApp) {
                // not in the app, tell them to download it!
		document.location.href = '<?php echo Yii::app()->request->baseUrl; ?>/splash/';
	}
}
		

$(document).ready(function() {
	var os = getMobileOperatingSystem();
	if (is_mobile() || os == 'ios' || os == 'android') {
		// we are on mobile.  Set a 5 sec timeout to display the "download app" page
		displayDownloadTimeout = setTimeout(displayDownloadAppPage, 5000);
	}
}

**Comment by myflashlab** [comment]
How about this: https://github.com/myflashlab/webView-ANE/blob/861e4e400b3443c8e96a8463b23c7cfdad49a631/FD/bin/demoHtml/index.html#L163-L184
