### ISSUE TITLE
Audio playing does not prevent timeout to lockscreen

### ISSUE THREAD

**Issue by galaxybeing** [myflashlab/webView-ANE#58]
While listening to audio playing, the screen dims and then locks and the audio stops playing.  Playing media should prevent the screen from timing out.  I've only verified this on iOS 9 iPad.

Videos seem to work correctly and prevent the timeout.

Here is an example.  I believe this is html5 audio.
<audio id="jp_audio_0" preload="metadata" src="http://142.4.9.234/~bflportal/audio/01%20Music%20For%20Gratitude.mp3"></audio>

**Comment by myflashlab** [comment]
Are you looking for this?!

```actionscript
NativeApplication.nativeApplication.systemIdleMode = SystemIdleMode.KEEP_AWAKE;
```

**Comment by galaxybeing** [comment]
I hope not.  Actually, If I play an media file in air, it will automatically prevent the device from sleeping until it is finished or stopped. If I play a media file in Safari, it will prevent the device from going to sleep until it is finished or stopped.  If I play a video file in your ANE it prevents the device from going to sleep until it is finished or stopped.  So it looks like the bug is just with audio files and your ANE.  So I think that's part of browser functionality.

Here's a web site I play frequently on my iPad.  It doesn't let it go to sleep.  We can test with it and see what happens.  I mean suppose I wanted to create a browser in my app that lets the user go anywhere.  I would have no way of telling if they were listening to an audio file.  So I would have to keep the device from going to sleep at all times, which would be unacceptable.  So I think it's got to be handled in the browser.  

http://www.npr.org/programs/fresh-air/

**Comment by myflashlab** [comment]
is this happening on both Android and iOS?

**Comment by galaxybeing** [comment]
On Android, on a Galaxy S 7, the screen goes dark and then locks, but the audio plays through.  I can have someone test it on a tablet device next week.  But I found some other issues that I'll report in the issue #50

**Comment by myflashlab** [comment]
We will look into this and update you as soon as possible?

**Comment by myflashlab** [comment]
It seems like this feature is not controlled by the webview as we were not able to find a native reference on that. If you know a native reference on this subject supporting iOS and Android, please update us and we will consider it for the next release.

**Comment by galaxybeing** [comment]
I've realized that I explained the issue incorrectly.  I'm closing this issue and have opened another one #66
