### ISSUE TITLE
When hiding the webView using the new .hide(true/false) command, take into account releasing the keyboard on Android

### ISSUE THREAD

**Issue by galaxybeing** [myflashlab/webView-ANE#62]
This is related to "On Android, attempting to type into an input textfield, keyboard does not appear" #60 

On Android with the webView instantiated but positioned offscreen, entering text in a Flash textfield is impossible because the device soft keyboard is never displayed.  Hiding the webView either by moving it off screen is preferable to destroying it, because it takes too long to reload a page from scratch (in our case it includes an auto login).

So if fixing #60  is difficult because the keyboard on Android can only be connected to the webView or the Air app, have the hide(true) command release the keyboard on hiding, and then reconnect it to webView on hide(false).

**Comment by myflashlab** [comment]
Please let me know if this issue is still valid after the release of the past couple of versions? I'm closing the issue now but if it is still valid, please DO re-open it. Thanks.
