### ISSUE TITLE
TypeError: Error #1009: Cannot access a property or method of a null object reference.

### ISSUE THREAD

**Issue by spadmore** [myflashlab/webView-ANE#63]
Hi using FlashBuilder with V6.0 of the RichWebView. Following is the error
**TypeError: Error #1009: Cannot access a property or method of a null object reference.**
Code Snippet Below
```actionscript
<?xml version="1.0" encoding="utf-8"?>
<s:View xmlns:fx="http://ns.adobe.com/mxml/2009" 
		xmlns:mx="library://ns.adobe.com/flex/mx"
		xmlns:s="library://ns.adobe.com/flex/spark" title="Home View Test"
		>
	<fx:Script>
		<![CDATA[
			import com.myflashlab.air.extensions.webView.RichWebView;
			import com.myflashlab.air.extensions.webView.RichWebViewEvent;
			import com.myflashlab.air.extensions.webView.RichWebViewSettings;
			
			public var _ex:RichWebView;
			
			// indicates the Android SDK version. you will need this when you are writting your JS logic when dealing with FileSelect input fields.
			
			function initWebView() {
				_ex	= new RichWebView(this.stage);	// NULL ERROR ON THIS LINE
				
				trace("Android SDK version: ", _ex.sdkVersion);	
			// add listeners
			_ex.addEventListener(RichWebViewEvent.BACK_CLICKED, onBackClicked);
			_ex.addEventListener(RichWebViewEvent.PAGE_STARTED, onPageStarted);
			_ex.addEventListener(RichWebViewEvent.PAGE_PROGRESS, onPageProgress);
			_ex.addEventListener(RichWebViewEvent.PAGE_FINISHED, onPageFinished);
			_ex.addEventListener(RichWebViewEvent.RECEIVED_SSL_ERROR, onReceivedError);
			_ex.addEventListener(RichWebViewEvent.RECEIVED_MESSAGE_FROM_JS, onReceivedMessage);
			_ex.addEventListener(RichWebViewEvent.SCREENSHOT, onScreenshot);
			_ex.openWebViewURL(0, 0, 250, 250, "http://www.myflashlabs.com/");
			}
```

**Comment by myflashlab** [comment]
1) are you sure ```this.stage``` is not null before passing it into the extension?
2) have you watched these video clips yet? https://www.youtube.com/watch?v=Oubsb_3F3ec&list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O

**Comment by spadmore** [comment]
Yes, I have done an test to see if it is null and it is not null. Do you
have any samples of this working in a Spark View?

- Shelon Padmore

**Comment by myflashlab** [comment]
If the Stage is not null, then it means that the extension is not embedded in your project correctly. Although the above video clips are showing the ANE usage in FB or FD, do make sure to watch them because there are some general rules you should notice when working with the ANEs, like running on a simulator will fail! and some more explained in the video.

**Comment by myflashlab** [comment]
Please update us if the problem is solved now?
