### ISSUE TITLE
Android 5.0.1 issue

### ISSUE THREAD

**Issue by burakbircanoglu** [myflashlab/webView-ANE#65]
I am trying it on android 5.0.1 and the app always is crushed right after picking an image.It works fine lower android versions with the same code.I m using your demo as3 code, and the advised js code on page.Does this mean that the ANE is not supporting 5.0.1?

**Comment by myflashlab** [comment]
It is supported on newer Android versions of course! Would you please be able to give us more information about the error? any logs? [logcats](http://developer.android.com/tools/help/logcat.html)?

**Comment by burakbircanoglu** [comment]
Well, as i said, i am using your codes.

The as3 codes are like:
	
	import com.myflashlab.air.extensions.webView.RichWebView;
	import com.myflashlab.air.extensions.webView.RichWebViewEvent;
	import com.myflashlab.air.extensions.webView.RichWebViewSettings;
	
	import flash.display.Bitmap;
	
	import flash.display.Sprite;
	import flash.display.StageAlign;
	import flash.display.StageScaleMode;
	import flash.events.Event;
	import flash.filesystem.File;
	import flash.text.TextField;
	
	public class Main extends Sprite {
		public function Main() {
			// support autoOrients
			stage.align = StageAlign.TOP_LEFT;
			stage.scaleMode = StageScaleMode.NO_SCALE;
			
			addEventListener(Event.ADDED_TO_STAGE,inits)
		}
		
		private function inits(event:Event):void {
			// TODO Auto-generated method stub
			var _ex:RichWebView = new RichWebView(this.stage);
			
			// add listeners
			if(_ex.os == RichWebView.ANDROID) trace("Android SDK version: ", _ex.sdkVersion);
			_ex.addEventListener(RichWebViewEvent.BACK_CLICKED, onBackClicked);
			_ex.addEventListener(RichWebViewEvent.PAGE_STARTED, onPageStarted);
			_ex.addEventListener(RichWebViewEvent.PAGE_PROGRESS, onPageProgress);
			_ex.addEventListener(RichWebViewEvent.PAGE_FINISHED, onPageFinished);
			_ex.addEventListener(RichWebViewEvent.RECEIVED_MESSAGE_FROM_JS, onReceivedMessage);
			_ex.addEventListener(RichWebViewEvent.RECEIVED_SSL_ERROR, onReceivedError);
			_ex.addEventListener(RichWebViewEvent.SCREENSHOT, onScreenshot);
			
			// set optional RichWebview settings (apply these settings AFTER initializing the ANE and BEFORE opening a webpage)
			RichWebViewSettings.ENABLE_BITMAP_CAPTURE = true;
			RichWebViewSettings.ENABLE_COOKIES = true;
			RichWebViewSettings.ENABLE_GPS = true;
			RichWebViewSettings.ENABLE_ZOOM = true;
			RichWebViewSettings.ENABLE_SCROLL_BOUNCE = false;
			RichWebViewSettings.BG_COLOR_HEX = "#FFFFFFFF"; // AARRGGBB
			
			_ex.openWebViewURL(0, 0, stage.stageWidth, stage.stageHeight, "http://jazzcript.com/index.php/pages/inputtest"); // OR from File.applicationStorageDirectory
			//_ex.openWebViewURL(0, 0, stage.stageWidth, stage.stageHeight, "http://www.kacak.net/sosyal/"); // OR from File.applicationStorageDirectory
			//_ex.openWebViewURL(0, 0, stage.stageWidth, stage.stageHeight, "http://www.google.com");
			
			function onBackClicked(e:RichWebViewEvent):void
			{
				if (_ex.canGoBack) _ex.goBack();
				else _ex.closeWebView();
			}
			
			function onPageStarted(e:RichWebViewEvent):void
			{
				trace("page started to be loaded");
			}
			
			function onPageProgress(e:RichWebViewEvent):void
			{
				trace("page loading: " + e.param + "%");
			}
			
			function onPageFinished(e:RichWebViewEvent):void
			{
				trace("page load completed");
			}
			
			function onReceivedError(e:RichWebViewEvent):void
			{
				trace("error = " + e.param);
			}
			
			function onReceivedMessage(e:RichWebViewEvent):void
			{
				trace("onReceivedMessage: ", e.param);
			}
			
			function onScreenshot(e:RichWebViewEvent):void
			{
				var bm:Bitmap = new Bitmap(e.param, "auto", true);
				this.addChild(bm);
			}
		}
	}
`


Here is the script codes which you advices to use.

`
window.onload = function() {

            var loadFileBtn = document.querySelector('.loadFileBtn');
            var fileInputField = document.querySelector('.hiddenFileInput');
            var img = document.querySelector('img');

            loadFileBtn.addEventListener('click', function()
            {
                fileInputField.click();
            }.bind(this));

            fileInputField.addEventListener('change', function(evt)
            {
                // get the selected file
                var theFile = evt.target.files[0];
                var _size = theFile.size;

                // you can check for the size of the selected image to restrict users from picking too large images
                //if(_size > 256000)
                //{
                //alert("please pick a file smaller than 250KB!\nYou are not limited to this size of course!\nThis is just a demo.");
                //return;
                //}

                // Android 2.3.6 browser does not support FileReader! so, if it is null, you should do something else accordingly
                if (typeof FileReader === "undefined")
                {
                    alert("Your browser is too old!\nUse another method to deal with the selected file.");
                    return;
                }

                // https://developer.mozilla.org/en-US/docs/Web/API/FileReader
                var reader = new FileReader();


                reader.onloadend = function (evt)
                {
                    img.src = evt.target.result;

                    if(evt.target.error)
                    {
                        // https://developer.mozilla.org/en-US/docs/Web/API/FileError
                        alert("error code = " + evt.target.error.code + "\nsee what this err code means:\nhttps://developer.mozilla.org/en-US/docs/Web/API/FileError");
                    }
                };


                if(theFile)
                {
                    reader.readAsDataURL(theFile);
                }
                else
                {
                    alert("error = file not found");
                }
            });
        };`

And this is the whole console log.

`[SWF] com.myflashlab.air.extensions.webView - 21,321 bytes after decompression
[SWF] Main.swf - 2,679 bytes after decompression
Android SDK version:  21
page started to be loaded
page loading: 10%
page loading: 10%
page loading: 27%
page loading: 27%
page load completed`

**Comment by myflashlab** [comment]
This is probably related to how JavaScript work on different devices. Please change the sample demo JS code so it will only show an alert instead of load the image in webview. if that works, which I think it will, then it means that the JS code must be fixed to work with that specific device. Moreover, the main job of the webview is to make the communication between Air/JS easy in mobile projects. All the JavaScript codes in the demo are just sample codes and not directly related to the ANE itself.

**Comment by myflashlab** [comment]
I'm closing this issue now but if you still have problems with this do let us know or re-open the issue. We are right now discussing the requirements to develop a new version of the RichWebView and your feedback would help us more. Thanks.
