### ISSUE TITLE
Playing streaming audio from a web page stops when device is locked.

### ISSUE THREAD

**Issue by galaxybeing** [myflashlab/webView-ANE#66]
Playing music or other audio is a fundamental feature of mobile devices.  Take any browser on a mobile device, put your headphones on, start playing an audio stream, lock the device and place it in your pocket and head down the street.

With RichWebView, if you start an audio stream and then press the device button to lock the device (or allow it to auto lock) the stream will stop playing.

Here are a couple of pages with audio streams, provided for example, that you can test with on any mobile browser and will not stop upon locking the device:

http://www.kqed.org/radio/listen/

http://player.chicagopublicmedia.org/#wbez

http://www.cdbaby.com/cd/jkdn

**Comment by galaxybeing** [comment]
This appears to be an iOS issue only.  Testing on Android, the audio keeps playing after the device auto locks.

**Comment by myflashlab** [comment]
We'll study about this and update you the soonest we can. Thanks.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
