### ISSUE TITLE
rotation landscape ios keep portrait width

### ISSUE THREAD

**Issue by Cyrillix** [myflashlab/webView-ANE#67]
Hi ,

When our app rotate from portrait to landscape on ios, our web view keep the width and height of portrait display.

We have this issue only on ios , android works.

We have tested our web view in safari on our phone and it works

**Comment by Cyrillix** [comment]
After some test, property height and width of RichWebView  class are good but contentHeight keep the same value after rotation to landscape

**Comment by Cyrillix** [comment]
we have solved this issue with our ane.

when we detect rotation we call our function from as3.

UIWebView.frame = CGRectMake(0,0,rootView.frame.size.width,rootView.frame.size.height)

**Comment by myflashlab** [comment]
@Cyrillix Would you please be able to send us a direct email? please do that from here: http://www.myflashlabs.com/contact/ Thanks.

**Comment by Cyrillix** [comment]
solved with RichWebView 6.3.0
