### ISSUE TITLE
webview on android 

### ISSUE THREAD

**Issue by aggreymarsh** [myflashlab/webView-ANE#68]
I have added the web view to my FB project on my mac and it works but it does not work on my android compiler on the PC . What could cause that ?

**Comment by myflashlab** [comment]
What error messages you are seeing? Have you watched these clips? https://www.youtube.com/watch?v=Oubsb_3F3ec&list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O

**Comment by majidHejazi** [comment]
Would you please update the state of this ticket? if you have more questions, please feel free to ask.
