### ISSUE TITLE
Controlling virtual keyboard 

### ISSUE THREAD

**Issue by ciaoamigo** [myflashlab/webView-ANE#69]
I have the same problem in Android. (Issues / 61)
The runtime automatically closes the virtual keyboard when the user taps(long press > 500ms) inside a webview.  

**I need to capture the event, how can I do?** _(Touch listener is not helpful)_

**Comment by myflashlab** [comment]
We are trying hard to find a solution to this problem. we'll keep you updated.

**Comment by dani2003** [comment]
Has anyone found any solution?
Helppppppppppppppppppppppp

**Comment by myflashlab** [comment]
We will update you the soonest we have a new release. Thanks for your patience.

**Comment by ciaoamigo** [comment]
It is necessary a plugin as https://github.com/driftyco/ionic-plugin-keyboard .
So I can scroll the page when the keyboard is visible.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
