### ISSUE TITLE
Softkeyboard overlapping inputfield 

### ISSUE THREAD

**Issue by Pandan** [myflashlab/webView-ANE#70]
Hi,
On Android I noticed that when the softkeyboard covers inputfields it does not automatically push the input(html content) up so it doesn't cover the input field. You can test with this. 
http://dev.schimpanz.com/androidtest/input.html
Testing the same url in a native browser on android it does. Is this an AIR combined with android issue?
On iOS is working as it should.

**Comment by myflashlab** [comment]
We have no control on how the keyboard pushes the content up on different occasions. Would you please tell us if this is happening on all different Android versions/models? On what devices have you checked it?

**Comment by majidHejazi** [comment]
Would you please update this ticket with an answer to the asked questions? Thanks.
