### ISSUE TITLE
useragent and X-Requested-By

### ISSUE THREAD

**Issue by ukeypad** [myflashlab/webView-ANE#72]
hello,

this ANE always send user-agent to Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.36 (KHTML, like Gecko) Chrome/13.0.766.0 Safari/534.36
and always add header X-Requested-With:air.packagename

can i change useragent or default phone's useragent?
can i remove header X-Requested-With header?

**Comment by myflashlab** [comment]
I will mark this question as an enhancement so we will consider it in the next release.

**Comment by ukeypad** [comment]
i tried shouldOverrideUrlLoading function and add header "X-Requested-With","mycustom"
it works, but load resource like <css> or <script> or <img> or <iframe> 
header added "X-Requested-With","my.app.id" automatically
i tried shouldInterceptRequest , but it's too difficult to make it.
please enhance this as soon as possible

**Comment by myflashlab** [comment]
Controlling the userAgent is now possible from V6.2.0. cheers.
