### ISSUE TITLE
Local HTML load fails

### ISSUE THREAD

**Issue by adamfoley** [myflashlab/webView-ANE#74]
Test device: Nexus 5, Android 6.0.1

Clicking **openWebView** box results in:

##  **Webpage not available**

The webpage at **app-storage:/demoHtml/index.html** could not be loaded because:

net::ERR_UNKNOWN_URL_SCHEME

**Comment by adamfoley** [comment]
Changing loading scheme to this resolves the problem:
`_ex.openWebViewURL(0, 0, stage.stageWidth, stage.stageHeight, "file://"+File.applicationStorageDirectory.resolvePath("demoHtml/index.html").nativePath);`

**Comment by myflashlab** [comment]
Thanks for the input.

**Comment by dannato73** [comment]
With Android 4.x/5.x your solution does not work.
Debugging this error:
TypeError: Error # 1034: Type Coercion failed: can not convert "file: /// data / data / xxxx / xxxx / Local Store / web / index1.html" to flash.filesystem.File.

**How do I use WebView with all versions?????**

**Comment by adamfoley** [comment]
**dannato73**, it sounds like you are using the **openWebViewLocal** method, which expects a `flash.filesystem.File` object.
