### ISSUE TITLE
android 4.4.4 file picker issue

### ISSUE THREAD

**Issue by ukeypad** [myflashlab/webView-ANE#75]
hello 
i tested extension for file upload.
android 4.4.4 device tells filename without extension
but when i test it with native browser it tells filename with extension
how can i do it?

**Comment by myflashlab** [comment]
The main job of the file picker is to let you have access to the selected image. if you have the file name with the extension and you wish to use the file name only, you can easily split the text using the ```.``` character in JavaScript or Actionscript right?

**Comment by ukeypad** [comment]
on android 4.4.4 tells filename without extension. (eg. 13   or image%2013 )
other android device tells full filename (eg. 20161212.jpg)
is android 4.4.4 bug?

**Comment by myflashlab** [comment]
We will try to investigate this more and update you as soon as possible. Thanks.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
