### ISSUE TITLE
softkeyboardbehavior not working

### ISSUE THREAD

**Issue by ukeypad** [myflashlab/webView-ANE#76]
in air application when i use stagewebview.. with &lt;softKeyboardBehavior&gt;pan&lt;/softKeyboardBehavior&gt; options.
when i touch input field then softkeyboard shows, if softkeyboard is front of input..then auto pan webview. so i can see input

but. when i use this extension 
when i touch input field, softkeyboard overlapped input field.. so i cannot see inputed text

how can i pan webview?

**Comment by dani2003** [comment]
I use native StageText it works fine (pan).

**Comment by myflashlab** [comment]
We are planing on probably building a new ANE which would take care of all events related to the keyboard. being able to manage the keyboard fully from an independent ANE might be a better solution to all different issues related to the keyboard. we will keep you updated guys. thanks for reporting.

**Comment by ciaoamigo** [comment]
Great......:)

**Comment by majidHejazi** [comment]
@ciaoamigo please follow the instruction [described here](https://github.com/myflashlab/webView-ANE/issues/61#issuecomment-215052184) and tell us if the problem with the StageText listener is solved on your side?
