### ISSUE TITLE
Hi, I'm sure that   app which include this ane  will be crash  on ios 6.1.3(ipad2)  even  you never use the ane

### ISSUE THREAD

**Issue by senshin998** [myflashlab/webView-ANE#78]
It's  a  terrible bug,You can not support ios 6 but do not crash。I think  ios app  can't  include this ane  until this bug is fixed。

**Comment by senshin998** [comment]
please help me !

**Comment by myflashlab** [comment]
We have no longer an iOS 6 so we didn't test the newer versions of the ANE with it. Maybe we should had upgraded min version required.

less than 5% of the iOS devices use iOS < 8.0 anyway https://developer.apple.com/support/app-store/

Anyway, please connect your device to your iMac and run the app while watching the logs. when the app crushes, please send us the log so we can see what might have gone wrong and send you a fix.

and even before doing that, please try to use the latest Adobe Air SDK for compiling your .ipa testing with at least Air SDK 19 is recommended.

Let me know how you go and we'll try to help you through as much as we can.
