### ISSUE TITLE
userAgent does not return expected "Android" in returned text.

### ISSUE THREAD

**Issue by galaxybeing** [myflashlab/webView-ANE#80]
The navigator.userAgent does not return the word "android" when running on an Android device.  We were using some standard userAgent parsing functions the just returned true if on mobile and false if not.  They are returning false on Android. 

your userAgent:
![image](https://cloud.githubusercontent.com/assets/12906083/14121354/1a5efa8a-f5c5-11e5-8809-6a911d01fdbb.png)

the phone's browser userAgent:

![image](https://cloud.githubusercontent.com/assets/12906083/14121391/457fabec-f5c5-11e5-9f1a-e4944ae0c92c.png)

**Comment by myflashlab** [comment]
We had to modify the userAgent to bypass the problem with the embedded video playbacks on Android devices on our latest version. we are working on a new release and will address the user-agent thing too so developers are able to set the user-agent manually from AS3. That might be a help to you too.

**Comment by galaxybeing** [comment]
Setting it from AS3 would not be fast enough in some cases like right after document ready.  I also had some problems where you were not setting the OS property of your class, or not setting it fast enough. So on each call to send a message to AS3, we check the os with one of these Javascript functions and then set your OS property just before it chooses the appropriate method for sending.  Of course, I didn't realize that it was just your plugin that was not sending "android" in its user Agent and could not figure out why all the message boards had not picked up on this yet :)
So it would be nice if the userAgent had the words to distinguish the os at $(document).ready()

**Comment by myflashlab** [comment]
controlling userAgent is now possible with V6.2.0. cheers.

**Comment by galaxybeing** [comment]
The changelog says (On Android devices, you need to set the useragent to *Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.36 (KHTML, like Gecko) Chrome/13.0.766.0 Safari/534.36* for YouTube or Vimeo players to work.)

But then it still does not say "android" anywhere.  Can I add it somewhere and still have Vimeo players working?  Like  (X11; Linux x86_64;Android)

**Comment by myflashlab** [comment]
Using V6.2.0 is giving you full control over the userAgent. saying that, although setting it to "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.36 (KHTML, like Gecko) Chrome/13.0.766.0 Safari/534.36" will make the YouTube/Vimeo embed videos to work, As you correctly mentioned it does not say Android anywhere in it.

So probably another userAgent must be used instead. we will have a look into this. That would also be great if you can also do a search on this.

**note**: This is not an issue with the ANE. it's actually a problem in WebView library in Android devices.
