### ISSUE TITLE
connect/disconnect bluetooth keyboard Android App Crash

### ISSUE THREAD

**Issue by vogttho** [myflashlab/webView-ANE#81]
My App crashes sometimes ( 20 %) after bluetooth keyboard connects or disconnects while StageWebView or webView-ANE is active.

Setting android:configChanges="orientation|keyboard|keyboardHidden" on the main activity could solve this problem. But this is not supported by Adobe http://help.adobe.com/en_US/air/build/WSfffb011ac560372f-5d0f4f25128cc9cd0cb-7ffc.html 

Steps to reproduce:
- Create Adobe Air Mobile Application
- Use StageWebViewor webView-ANE to load and display an external Website
- Run the Application on an Android Device
- Connect bluetooth keyboard to your Device
- Run the App
- After the page has loaded select and deselect text on the page and connect/disconnect your keyboard a few times
- The App will crash (unfortunately application has stopped)

The App does not crash if you destroy and reload StageWebView. But this is not an acceptable solution for my use case.

Is it possible to set android:configChanges="orientation|keyboard|keyboardHidden" inside the Extension?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
