### ISSUE TITLE
Does not work at all in iOS 8.3

### ISSUE THREAD

**Issue by adamfoley** [myflashlab/webView-ANE#82]
- FlashBuilder 4.7
- AIR v21
- iOS 8.3

Copied all of the iPhone app properties from the sample project into mine.  Provided URL never loads.  No page load event.  Nothing.  Tried opening local file along with remote URL, no luck either way.

ideas?

**Comment by myflashlab** [comment]
You mean the same application is not working on iOS 8.3 but it works on newer versions?

**Comment by adamfoley** [comment]
More or less, but the only device I have to test with is running 8.3, so I don't know if it would work in 9+. 

My test project is not identical, but it works just fine on Android 6.0.1 device.  On the iPhone (5C), I get a blank white screen after the demo version alert/notification.

**Comment by rodrigogermanlopez** [comment]
Doesn't work for me either.
Tested it on iphone 6+ (iOS 9.3.1) and ipad3 (iOS 9.3.1), all events are dispatched, but there's no webview rendering on the screen (I get the DEMO alert though).

**Comment by myflashlab** [comment]
Please try to send us device logs while the app crashes when your device is connected to iMac and xcode debug console is open. we're still not able to duplicate the problem.

And one more thing, please try to run the demo project with how the AS3 codes are organized and see if you still have the problem...?

**Comment by adamfoley** [comment]
How do I connect xcode debug console to my test app running on device?  Using xcode 7.3, I start the app and try debug->Attach to process but nothing is listed there.  To clarify, there is no _crash_, the richWebView object just does nothing beyond displaying demo prompt.

**Comment by myflashlab** [comment]
we'll look in to this further and update you as soon as possible. Thanks,

**Comment by MonkeyDoll** [comment]
I got exactly same issue with demo ane. Android work fine.
Also try to add 
<key>NSIncludesSubdomains</key><true/>
but still not working.

iPhone 6.
iOS 9.3.1
Flex SDK 4.15.0 AIR 21.

**Comment by alamboley** [comment]
Does the problem is solved? This issue sounds like a bumer, preventing me to try the ANE.

**Comment by jalendai** [comment]
I'm having the same problem. The exact same code works on Android, but not on iOS. When the code is running on iOS, RichWebView.openWebViewURL() doesn't seem to get executed at all. Thus I can't see the page started event, page progress and page finished event triggered. The screen is blank.

I've searched online for a couple of days. Can't seem to find anything related. We demoed our app to the client on Android, but stuck on the iOS package. May I ask if there's any progress on this issue? Or at least suggest an alternative? Thanks.

**Comment by adamfoley** [comment]
@jalendai I ended up writing my own webview ANE then later switched to a Cordova based project after AS/Flash requirements for my project were dropped.  I don't want to open source my code (pretty rough anyway) at the expense of myflashlab's revenue.  If they are interested in acquiring it in an effort to correct their own ANE they are welcome to contact me.

**Comment by jalendai** [comment]
Thanks for your feedback, adamfoley. My intention was to simply use an ANE to get things working quickly. But now I may have to either look for other similar ANEs or check with the boss if he's ok to build our own ANE. I guess you've been through all that.

**Comment by jalendai** [comment]
Good suggestion. I will give it a try later today. Thanks, MonkeyDoll.

**Comment by jalendai** [comment]
Hey MonkeyDoll, thank you very much for the suggestion. It works for me.

**Comment by myflashlab** [comment]
Correct, as stated [here](https://github.com/myflashlab/webView-ANE#demo-apk):
> NOTICE: the demo ANE works only after you hit the "OK" button in the dialog which opens. in your tests make sure that you are NOT calling other ANE methods prior to hitting the "OK" button.
