### ISSUE TITLE
net::ERR_UNKNOWN_URL_SCHEME - Android 6.x

### ISSUE THREAD

**Issue by dannato73** [myflashlab/webView-ANE#84]
With Android 4.x/5.x the solution (https://github.com/myflashlab/webView-ANE/issues/74) does not work.
Debugging this error:
TypeError: Error # 1034: Type Coercion failed: can not convert "file: /// data / data / xxxx / xxxx / Local Store / web / index1.html" to flash.filesystem.File.

**How do I use WebView with all versions.**

**Comment by myflashlab** [comment]
With v 6.2.0 we fixed a file address related issue on some Android devices.
Please let us know if you still have trouble with this? Thanks.

On Tuesday, April 19, 2016, dannato73 <notifications@github.com> wrote:

> With Android 4.x/5.x the solution (#74
> <https://github.com/myflashlab/webView-ANE/issues/74>) does not work.
> Debugging this error:
> TypeError: Error # 1034: Type Coercion failed: can not convert "file: ///
> data / data / xxxx / xxxx / Local Store / web / index1.html" to
> flash.filesystem.File.
>
> *How do I use WebView with all versions.*
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/webView-ANE/issues/84>
>


-- 
Sent from iPhone
