### ISSUE TITLE
RichWebView v6.1.0 Android -> Touch event with GoogleMap not fired.

### ISSUE THREAD

**Issue by fperreault** [myflashlab/webView-ANE#85]
Only on Android, the GoogleMap that we load into a "richWebView" don't works well. The touch event of the map are not fired correctly (can't drag the map). This bug was not present in v5.1. To reproduce it, load a url that contains a GoogleMap. You can use this url to test the issue: https://maps.google.ca/

**Comment by myflashlab** [comment]
Thanks for reporting this issue. we will be releasing a new version soon which will have this problem fixed.

**Comment by myflashlab** [comment]
In V6.2.0 this problem is addressed and fixed. Thanks.

**Comment by ruthlissly** [comment]
I still found this bug (can't drag the map) in richWebview V. 6.3.0.
Is there a configuration to fix it ?
