### ISSUE TITLE
Webview only showing in small frame and can't be resized

### ISSUE THREAD

**Issue by khevamann** [myflashlab/webView-ANE#86]
On android the webview is a small panel in the upper left corner, and I am unable to change the size, I have tried stage.stageWidth and just typing in the value 480

**Comment by myflashlab** [comment]
Are you using the latest version? 6.2.0? If you do, please let us know your
Android sdk version and model and also tell us if you had this problem on
older versions also?

On Monday, May 2, 2016, khevamann <notifications@github.com> wrote:

> On android the webview is a small panel in the upper left corner, and I am
> unable to change the size, I have tried stage.stageWidth and just typing in
> the value 480
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/webView-ANE/issues/86>
>


-- 
Sent from iPhone

**Comment by khevamann** [comment]
Yes I have updated to the newest version, 6.2.0. I have been testing it on an HTC M8 with android version 6.20.654.3

**Comment by myflashlab** [comment]
do you have this problem on a specific HTML file? Are you trying to load the file locally or is it a remote file? can you send us a demo apk to test?

**Comment by myflashlab** [comment]
We are not able to duplicate this problem and you didn't reply back on our last message, so I'm closing this issue now. But if you can get back to us with more information please DO open the ticket again so we can investigate this more. Thanks.
