### ISSUE TITLE
iframe - blocked a frame with origin null from accessing a cross-origin frame

### ISSUE THREAD

**Issue by laxmipa** [myflashlab/webView-ANE#87]
Hi,

I am using iframe to load another local html file in my main parent html file. When i call a parent function from iframe, it throws me the error "blocked a frame with origin null from accessing a cross-origin frame".
This error comes only in android. It works fine in iOS. It also works fine when use openWebViewURL in android.

This errors comes only when i load local html files.

Thanks

**Comment by myflashlab** [comment]
Did you test this with V6.2.0 because in the latest release we did some enhancements on Android devices.

If you still have the problem, would you please send us your html code so we can test it locally and find the problem? Thanks a lot.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
