### ISSUE TITLE
Close webview with closeWebView and starling in android 4.4.2

### ISSUE THREAD

**Issue by developOPQA** [myflashlab/webView-ANE#88]
When I close the Webview with closeWebView function, Starling textures become black, only it happens in version 4.4.2 of Android, I'm using adobe air 21, I tested on different devices with different versions of android and only happens in the with version 4.4.2, if I use hide (true) if it works, but I can not have 2 different webview.

**Comment by myflashlab** [comment]
check this out and maybe you can try these solutions to restore your context... https://www.google.com/search?q=starling+forum+black+android&ie=utf-8&oe=utf-8

**Comment by myflashlab** [comment]
would you please update us about this issue?

**Comment by developOPQA** [comment]
That way not get it to work, so to close hide use and matched to null the webview.

**Comment by myflashlab** [comment]
Do you still have this problem with the latest version of Starling?

**Comment by subdan** [comment]
I have the same issue. When I call closeWebView or dispose on Android all Starling textures become black.

**Comment by myflashlab** [comment]
didn't [this](https://github.com/myflashlab/webView-ANE/issues/88#issuecomment-219346875) help you?

**Comment by subdan** [comment]
No :(

**Comment by myflashlab** [comment]
This seems to be a problem on Samsung devices with Android 4.4.2 Anyhow, we are working on a new Webview release which a LOT will change about it. hopefully that would solve the problem.

**Comment by subdan** [comment]
>on Samsung devices 
I have issue on Sony xperia.

>new Webview release 
Great!

P.S. Is it possible to get a screenshot of viewPort area instead of full page. When I call `requestBitmap` for a page with a lot of text I get BitmapData with 300x10000 px size. It freezes my app and crash sometimes.

**Comment by myflashlab** [comment]
> screenshot of viewPort

That's in our to-do list also.

**Comment by subdan** [comment]
Great to hear that. Any ETA?

**Comment by myflashlab** [comment]
hopefully in Feb, or early Mar

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
