### ISSUE TITLE
The extension context does not have a method with the name command

### ISSUE THREAD

**Issue by painschen** [myflashlab/webView-ANE#9]
After starting this:
import com.doitflash.air.extensions.webView.*;
import com.doitflash.air.extensions.webView.ios.*
import com.doitflash.air.extensions.webView.android.*;
var _ex:MyWebView = new MyWebView(stage,true,true);
_ex.addEventListener(MyWebViewEvent.PAGE_STARTED, onPageStarted);
_ex.addEventListener(MyWebViewEvent.PAGE_PROGRESS, onPageProgress);
_ex.addEventListener(MyWebViewEvent.PAGE_FINISHED, onPageFinished);
_ex.addEventListener(MyWebViewEvent.RECEIVED_SSL_ERROR, onReceivedError);
_ex.openWebViewURL(0, 0, stage.stageWidth, stage.stageHeight, "http://www.google.de");

I get this in Flash 2015:

ArgumentError: Error #3500: The extension context does not have a method with the name command.
	at flash.external::ExtensionContext/_call()
	at flash.external::ExtensionContext/call()
	at com.doitflash.air.extensions.webView.android::Android/openWebViewURL()
	at com.doitflash.air.extensions.webView::MyWebView/openWebViewURL()
	at diwa_fla::MainTimeline/frame1()[diwa_fla.MainTimeline::frame1:49]
	at runtime::ContentPlayer/loadInitialContent()
	at runtime::ContentPlayer/playRawContent()
	at runtime::ContentPlayer/playContent()
	at runtime::AppRunner/run()
	at ADLAppEntry/run()
	at global/runtime::ADLEntry()

**Comment by myflashlab** [comment]
Are you running on a simulator? Try a real device. Let me know if that
helped?

On Thursday, July 23, 2015, painschen <notifications@github.com> wrote:

> After starting this:
> import com.doitflash.air.extensions.webView.
> *; import com.doitflash.air.extensions.webView.ios.*
> import com.doitflash.air.extensions.webView.android.*;
> var _ex:MyWebView = new MyWebView(stage,true,true);
> _ex.addEventListener(MyWebViewEvent.PAGE_STARTED, onPageStarted);
> _ex.addEventListener(MyWebViewEvent.PAGE_PROGRESS, onPageProgress);
> _ex.addEventListener(MyWebViewEvent.PAGE_FINISHED, onPageFinished);
> _ex.addEventListener(MyWebViewEvent.RECEIVED_SSL_ERROR, onReceivedError);
> _ex.openWebViewURL(0, 0, stage.stageWidth, stage.stageHeight, "
> http://www.google.de");
>
> I get this in Flash 2015:
>
> ArgumentError: Error #3500: The extension context does not have a method
> with the name command.
> at flash.external::ExtensionContext/_call()
> at flash.external::ExtensionContext/call()
> at com.doitflash.air.extensions.webView.android::Android/openWebViewURL()
> at com.doitflash.air.extensions.webView::MyWebView/openWebViewURL()
> at diwa_fla::MainTimeline/frame1()[diwa_fla.MainTimeline::frame1:49]
> at runtime::ContentPlayer/loadInitialContent()
> at runtime::ContentPlayer/playRawContent()
> at runtime::ContentPlayer/playContent()
> at runtime::AppRunner/run()
> at ADLAppEntry/run()
> at global/runtime::ADLEntry()
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/webView-ANE/issues/9>.
>


-- 
Sent from iPhone

**Comment by painschen** [comment]
i didnt check that at real device.. so it's not working at desktops for testing? it would be nice if you insert that feature, so i dont have to publish the app every time

**Comment by myflashlab** [comment]
for detailed information about this check this playlist https://www.youtube.com/watch?v=Oubsb_3F3ec&list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O
