### ISSUE TITLE
XMLHttpRequest cannot load

### ISSUE THREAD

**Issue by chanintorn-r** [myflashlab/webView-ANE#90]
Hi,

  When I try to use webView-ANE to load local html file it throw an error **XMLHttpRequest cannot load,  Cross origin requests are only supported for protocol schemes: http, data, https**.

  But if I use stageWebview it work well. Does this mean that the ANE is not support these kind of request?

 And this is html folder that I used. [https://github.com/driftyco/ionic-starter-tabs.git](url)

Thanks.

**Comment by myflashlab** [comment]
https://github.com/myflashlab/webView-ANE/issues/93

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
