### ISSUE TITLE
 mx.core::ByteArrayAsset is not defined.

### ISSUE THREAD

**Issue by mansari68** [myflashlab/webView-ANE#91]
I am trying to add this ANE to flash CS6 with AIR 20.0 SDK for Android, but when debugging, i get the following error.

ReferenceError: Error #1065: Variable mx.core::ByteArrayAsset is not defined.
	at global$init()
	at runtime::ContentPlayer/loadInitialContent()
	at runtime::ContentPlayer/playRawContent()
	at runtime::ContentPlayer/playContent()
	at runtime::AppRunner/run()
	at ADLAppEntry/run()
	at global/runtime::ADLEntry()

**Comment by myflashlab** [comment]
The error message does not seem to be related to the ANE at all! yet, make sure you are using the latest Air SDK and also watch these videos: https://www.youtube.com/watch?v=Oubsb_3F3ec&list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O

I'm closing the issue as it really does not feel to be related to the ANE, but if you have more information on this, do re-open it. Thanks.
