### ISSUE TITLE
Abstract scroller issues

### ISSUE THREAD

**Issue by galaxybeing** [myflashlab/webView-ANE#92]
I'm having some problems implementing the abstract scroller.  We had our own home built scroller but I didn't like the way it jerked sometimes, and I don't have time to mess with it, or I've spent too much time messing with it, so I thought I would drop your scroller in and it would fix all the problems.  It's not going so well.

First, it is scrolling too far.  I have a MC that I fill with icon buttons (disabled for now) setup to scroll horizontally. So I scroll it from right to left and when it gets to the end, instead of stopping at the end of the list of icons, it keeps going till it is almost to the left of the screen.  About 30 pixels stick out, so thankfully I can grab the. And drag to the right.  Why is it doing this and how do I correct it so that it stops scrolling at the right edge of the mask. (This mask is created in Flash Pro and set as a mask to the empty content movie clip.). How does your scroller determine the viewable area?  The mask, right?  Does it just use the mask attached to the scroll clip?

The second issue is that it doesn't stop when I touch the scrolled clip.  Say I drag right to left and let go. It keeps scrolling, and I see what I want so I touch to stop it.  But it just ignores my touch and keeps going.

Third, our scrolling clip had nothing but icon buttons on it. You only have one example and it doesn't have any buttons.  It would be nice if you had an example that had a button on it.  For our own rolled scrolling, we had the events sent to the buttons and they would determine if the mouse action was for scrolling or to click the button.  I imagine that we will have to keep some of that code in the buttons and then pass the event to your scroller if it is not a click.  Would be nice if your scroller had some of that built into it.  But if you can help me with the first two issues then I will attempt to get the buttons working later.

**Comment by myflashlab** [comment]
Any question regarding the scrollers, please ask here: http://www.myflashlabs.com/contact/ Thanks.
