### ISSUE TITLE
Webview permission.

### ISSUE THREAD

**Issue by ruthlissly** [myflashlab/webView-ANE#93]
Hi,
Did you open these two permissions ?

webSetting.setAllowFileAccessFromFileURLs(true);
webSetting.setAllowUniversalAccessFromFileURLs(true);

Thanks.

**Comment by myflashlab** [comment]
We are discussing the possibilities of development of a whole new version of the RichWebView. We will consider these settings in the new coming version. Thanks for your input.

**Comment by myflashlab** [comment]
Please update yourself to [V6.3.0](https://github.com/myflashlab/webView-ANE#changelog)
