### ISSUE TITLE
Can I pass a HTML string as url?

### ISSUE THREAD

**Issue by Seitei** [myflashlab/webView-ANE#94]
I need to call some JS functions inside the HTML wrapper, trying to detect when I'm pausing/playing a YT video.

In StageWebView I used to pass an HTML String with custom JS, however when I pass an url here, I get a Webkit error 101, I imagine that is because I have to use open openWebViewLocal instead?. 

Can you please point me out to an example of how to do it? Thanks.

**Comment by myflashlab** [comment]
As right now, passing a String for the webview content is not possible but we are planning to add this option in future releases. that's for sure. until then, you can load local html files with ```openWebViewLocal ``` Thanks.

**Comment by Seitei** [comment]
Yes, I did that, it was a bit more cumbersome maybe but it worked. Thanks
for your support.

On Wed, May 25, 2016 at 7:46 AM, myflashlab <notifications@github.com>
wrote:

> As right now, passing a String for the webview content is not possible but
> we are planning to add this option in future releases. that's for sure.
> until then, you can load local html files with openWebViewLocal Thanks.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/webView-ANE/issues/94#issuecomment-221478881>
>



-- 
*"Walking on water and developing software from a specification are easy if
both are frozen."*

**Comment by marcanw** [comment]
Any news about passing html code directly from a string?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
