### ISSUE TITLE
Capturing bitmapData from Youtube returns black image.

### ISSUE THREAD

**Issue by Seitei** [myflashlab/webView-ANE#95]
I'm trying to capture a snapshot from a paused Youtube video, however when I pause the video and request the bitmapData, all I get is a black background (instead of the video snapshot) and YouTube controls on top of it.

It seems like the actual video stream is missing.

Can you help me with this?, it's killing our design since we need to rely on the paused snapshots to display or hide our UI on top of that image.

Thanks.

**Comment by myflashlab** [comment]
I'm not sure you can do that! because video contents are usually rendered in GPU and taking a screenshot usually will miss that. It's not something to be related to how the ANE works. this problem exists on native apps also.
