### ISSUE TITLE
Touch event position not accurate.

### ISSUE THREAD

**Issue by Seitei** [myflashlab/webView-ANE#96]
Hi, I'm trying to capture Touch events, however the param.x an param.y offered by the event don't seem to represent the proper coordinate system.

Example, my RichWebView component has a width of 1024, and when I tap to the extreme right, I only get 512 as maximum value, it seems like it's halving it in two for some reason.

Would need some clarification on how it works exactly, right now I'm just multiplying the touch parameter by 2 but I'm not sure if this is how it's supposed to work.

Thanks.

**Comment by myflashlab** [comment]
Thanks for reporting this. This is now fixed in [V6.3.0](https://github.com/myflashlab/webView-ANE#changelog)
