### ISSUE TITLE
file picker crushed

### ISSUE THREAD

**Issue by shpe11** [myflashlab/webView-ANE#98]
just brought for the file picker, tested on samsung galaxy S 4 and file picked doesn't work

tested on your sample with an online page _ex.openWebViewURL 
in the page is a normal file input, and when "browse" button is taped, the app crashes(closes)

do we need additional permissions?
write/read from storage or something like this?!?!??

**Comment by myflashlab** [comment]
you do need and extra activity if you are trying the Android side. [read here](https://github.com/myflashlab/webView-ANE#air-xml-manifest)

If that doesn't solve the problem, please run [the demo .apk](https://github.com/myflashlab/webView-ANE/tree/master/FD/dist) on your target device and tell us how it goes.

**Comment by shpe11** [comment]
put the activity, worked to chose file, but crushed(closed - "unfortunately webview has stopped.") on submit the form where the file input was...

I used the code from here: https://github.com/myflashlab/webView-ANE/blob/master/README.md section Air Usage

why in the .zip there is no sample fla/as/xml for android? and what is com.doitflash.webView.Pick? do I need to get/include that extension too? although it worked choose file with the <activity android:name="com.doitflash.webView.Pick" android:theme="@style/Theme.Transparent" /> which have to be enclosed in <application></application> by the way

your sample works, but it does something else... it loads the file in the HTML, I want the file submited, even so I don't know where to get the HTML loaded in webview to see the HTML code inside...

**Comment by shpe11** [comment]
ok, used the sample .js and some function to write files...

function base64_to_jpeg($base64_string,$output_file) {
    $ifp=fopen("upload/".$output_file,"wb");
    $data = explode(',', $base64_string);
    fwrite($ifp, base64_decode($data[1])); 
    fclose($ifp); 
}

sending that encoded 64 data to server and decoded to ascii and write

**Comment by myflashlab** [comment]
Right, when you pick an image in WebView, depending on what OS version you are running on, you need to adjust your JS code to make sure it works on that version. Thanks for sharing your findings.
